freelawproject/courtlistener

cl/scrapers/management/commands/cl_scrape_opinions.py

Some minor changes mostly to get used to the concept of pull requests. Found these while getting a local instance bootstrapped with some content in the Solr index and PostgreSQL DB. 
* Removed `Required=True` for `--rate` as it has a default
* Since there's a default value and it's explained in the help text, this is sort of unnecessary
* Corrected an out-of-date package reference in `--courts` help text
* Simple change to keep things up to date with Juriscraper layout.

Cleaned up some settings in the cl_scrape_opinions.py command

---

cl/scrapers/DupChecker.py
cl/scrapers/tests.py

I was looking at the scrapers test cases and the ones currently failing seemed to be failing for odd reasons:
* `IngestionTest.test_ingest_opinions()` - was explicitly failing and implying a manual check of the database.
* changed to look for the exact count of the number of Opinion instances in the fixtures instead so the test can be autonomous
* `DupcheckerWithFixturesTest` - seemed to be looking for the wrong True/False condition based on previous refactor of the `DupChecker` class
* let me know if my assertion changes don't make sense as either the tests are wrong or the logic in `DupChecker.press_on()` is probably wrong
* also removed what seemed to be an unneeded call to `.setUp()` again...not sure why that's there but my guess is it's some older logic to try to create duplicates …

Scraper Tests: Changes to test Assertions

---

cl/settings/10-public.py
cl/users/tests.py

In trying to execute the tests in `cl.users.tests` I came across issues first with database connections not being dropped post-test execution. In looking around online in Django forums, I concluded using the production setting of `DATABASES['default']['CONN_MAX_AGE'] = 600` causes connections to hang when running in development environments. Dropping `CONN_MAX_AGE` to back to its default of `0` tells Django to not keep connections around (see https://docs.djangoproject.com/en/1.9/ref/settings/#conn-max-age). This is probably related to migrating (hopefully temporarily?) to PostgreSQL for the testing db.
Secondly, `test_set_password_using_the_HTML()` was failing and the rendered HTML seemed to imply things weren't valid coming into the view. Digging into the [Django …

Fixes for Users module tests

---

cl/search/management/commands/cl_dumpdata.py

Here's a Django management command class that is specific to CL and might help replace some of the old SQL data dumping scripts. It randomly selects a subset of Opinion primary keys and then uses them and the built-in Django serialization routines (used in Django's dumpdata command) to dump out Opinions, OpinionClusters, and Dockets.
Simple usage:
```
./manage.py cl_dumpdata -n 100
```
Where `-n` is the number of Opinions to select for the dump.
Right now I haven't written any tests, but if this works I'll round it out with some better logic and tests.

Quick and Dirty Data Dumper

---

cl/settings/05-private.example

Small tweak that helps fix the FreeLawMachine box and anyone that bases their local private settings off the example file.

Resolves TypeError in 05-private.example when creating a date object for FTM

---

cl/favorites/tests.py
cl/tests/base.py
cl/users/tests.py

In working through Ansible playbooks for the FreeLawMachine, I noticed it was odd to symlink the `phantomjs` binary into `/usr/local/phantomjs/`. Instead, I've been installing PhantomJS in `/opt` and symlinking the binary into `/usr/local/bin`, which seems more standard for manually "installing" software on Linux.
After doing this and running some of the CourtListener tests, I noticed they were failing because of hardcoded paths to `/usr/local/phantomjs/phantomjs` in the test logic in a few places.
This PR addresses those issues with tests and also cleans up the `webdriver` usage to minimize code duplication. This should make it easier to update in the future and also for people to do a quick swap to the Firefox webdriver if so inclined during testing.
_**NOTE**: this does require that on …

Rely on PhantomJS binary being in PATH instead of `/usr/local/phantomjs/phantomjs`

---

cl/assets/templates/base.html

Added tagline to header in base.html. I looked at it in the chrome developer tools and it appears to resize properly and stay under the image on the smaller screen sizes.

added tagline to header

---

cl/simple_pages/views.py

Most users tend to want PDFs displayed in their browsers.
Those who want otherwise can override (such as me).
But setting Content-Disposition: attachment does not allow most users
to see PDFs in their browers when they want to. It is undesirable and
counterproductive.
Possibly a better fix is to not specify Content-Disposition at all,
but I sat on this for 2 months without doign anything with that, so
let's go ahead with this.
Fixes #777.

views.py: Content-Disposition inline for PDF downloads

---

cl/api/urls.py

The `url` kwarg passed to `get_schema_view()` should be removed. It was causing the following problems:
1. Particularly for the [Swagger interface](https://www.courtlistener.com/api/swagger/), we were experiencing a weird bug where API calls would go to https://www.courtlistener.comhttps://www.courtlistener.com/api/api/rest/v3/dockets/, which has the base URL doubled up for some odd reason.
2. If the site is deployed anywhere but courtlistener.com, the URLs for the API schema views would be hardcoded to point to courtlistener.com nonetheless.
By removing the URL kwarg and letting the default value pass through, the Django REST Framework will automatically figure out the correct URLs for the user.

Fix calls to get_schema_view()

---

cl/opinion_page/urls.py
cl/simple_pages/urls.py
cl/urls.py
cl/users/urls.py

> I welcome refactorings.
Normally I don't, but the `mime_types` thing was confusing enough to me as a reader that I thought it was worth addressing, and one thing begat another. Passes `flake8` for PEP-8.

**/urls.py cleanup

---

cl/corpus_importer/tasks.py
cl/corpus_importer/tests.py
cl/lib/pacer.py
cl/recap/api_serializers.py
cl/recap/models.py
cl/recap/tasks.py
cl/recap/tests.py
cl/search/models.py

Pre-appellate cleanup. Please don't squash these commits, 
c0bce5a  and 71894af should stand on their own, and probably they all should:
* PEP8 cleanup of the files I expect to touch when wiring up Appellate
* `flake8` Caught a bug in reusing the `count` var in `recap/tasks.py`. Not clear if this was ever triggered live.
* Refactor out the RECAP `UPLOAD_TYPE`s per a discussion we had a long time ago because I'm going to touch them anyhow and it's really nice not to have to mess with a zillion files where a small handful would do, and scoping is good, etc., etc.
Let me know if you want the non-{ c0bce5a 71894af} broken out into a 3rd PR.
Nothing in this PR should actually change any behavior (except maybe the bugfix?)

pre-Appellate cleanup

---

cl/lib/pacer.py
cl/recap/api_serializers.py
cl/recap/models.py
cl/recap/tasks.py

This leaves unresolved the changes to the Docket object to support additional appellate fields, but should be enough to get it working initially and allow client testing.
This depends on #832. **Which has been merged*.*
~Unfortunately I think I have misunderstood how to create a pull request that depends on another pull request. Umm?~

2018.06.05.wire up appellate

---

cl/search/forms.py

An invalid date won't appear in the SearchForm.cleaned_data.
This causes a KeyError later when the error page tries to present
the search summary as a string.
Fix by checking whether the cleaned data contains the key first
and returning None when it doesn't.
fixes #819

Make invalid date in search not cause KeyError

---

cl/tests/base.py

According to @mlissner, these two lines are not needed anymore.
The motivation for removing them is that they cause errors like #877.
fixes #877

tests: remove unnecessary lines to configure path to chrome binary

---

requirements.txt

Add pip env marker to pyinotify to skip installing on mac
Otherwise we get this error.
```
Collecting pyinotify==0.9.6 (from -r requirements.txt (line 61))
Downloading https://files.pythonhosted.org/packages/e3/c0/fd5b18dde17c1249658521f69598f3252f11d9d7a980c5be8619970646e1/pyinotify-0.9.6.tar.gz (60kB)
100% |████████████████████████████████| 61kB 4.5MB/s
Complete output from command python setup.py egg_info:
inotify is not available on macosx-10.13-x86_64
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y_/sjt8100n43g69mtr9t588d6r0000gp/T/pip-install-nx4RSL/pyinotify/
```
Pip installs on other platforms are unaffected.
Read more about [pip environment markers][env-marker] here.
[env-marker]: …

Add pip env marker to pyinotify to skip installing on mac

---

cl/citations/find_citations.py
cl/corpus_importer/tests.py
requirements-test.txt

Pytest and pytest-django are better test runners for several reasons.
* The django test runner creates test databases on initialization even if
the tests that are run don't need the database. This is slow and inefficient.
Pytest [lazily creates the test database][pytest-lazy-db].
* [Other reasons][other-reasons].
Other changes:
* Lazy-load `find_citations.py:ALL_COURTS` when test runner is `pytest`.
* Make `cl/corpus_importer/tests.py` test classes that don't need
database access inherit from `unittest.TestCase` instead of `django.test.TestCase`.
There's nothing django-specific about these test classes.
Otherwise, pytest will still eagerly load the database.
* Mark `cl/corpus_importer/test.py:PacerDocketParserTest as needing DB access.
```
time ./manage.py test --noinput …
```

Add pytest as test runner

---

requirements.txt

to fix this error on travis-ci.com that occurred when pip installing reqs.
See https://github.com/psycopg/psycopg2/issues/594#issuecomment-331172198.
```
Collecting psycopg2==2.6.1 (from -r requirements.txt (line 58))
Downloading https://files.pythonhosted.org/packages/86/fd/cc8315be63a41fe000cce20482a917e874cdc1151e62cb0141f5e55f711e/psycopg2-2.6.1.tar.gz (371kB)
100% |████████████████████████████████| 378kB 3.6MB/s
Complete output from command python setup.py egg_info:
running egg_info
creating pip-egg-info/psycopg2.egg-info
writing pip-egg-info/psycopg2.egg-info/PKG-INFO
writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt' …
```

Upgrade psycopg2 in requirements.txt from 2.6 to 2.7

---

.gitignore

`cl/settings.py` say to override public settings in a new file
at `cl/settings/20-private.py`. Only `cl/settings/05-private.py`
is ignored from git right now. Let's ignore all `cl/settings/*private.py`
from git for convenience and safety.

Ignore all cl/settings/*private.py from git

---

.circleci/Dockerfile
.circleci/activate.sh
.circleci/config.yml
.circleci/configure-courtlistener.sh
.circleci/configure-postgres.sh
.circleci/pg_hba.conf
.circleci/pgpass

We'll start small with just testing one module, `cl.corpus_importer`.
Motivation: there's no CI/CD for this project right now. Humans forget to run
the test suite before merging.  This can lead to bugs getting deployed to
production.  Let's use circleci.com, a CI/CD platform that's free for open
source projects, to run tests. We'll use circleci.com instead of travis-ci.com
because Circle supports using custom Docker images as the test executor.
[Travis doesn't](https://github.com/travis-ci/travis-ci/issues/7726).
There are lots of dependencies that need to be
installed before the tests in this repo can be run.
`.circleci/Dockerfile` creates a Docker image that has test dependencies
preinstalled to speed up test executions. Installing all the test dependencies
at testing time would take …

Start automatically running tests on circleci.com

---

.circleci/config.yml
cl/stats/tests.py

in addition to corpus_importer tests.
Mark StatTests as needing DB access in accordance with pytest usage.

circleci: Run custom_filters and stats tests

---

cl/people_db/templates/view_person.html

Quick fix to update links to individual FJC biographies to point to the biography instead of the index to all biographies.

Update link to FJC biographies.

---

cl/opinion_page/templates/recap_document.html

When displaying the text (not PDF) of a document in RECAP, correct a
typo in the link to the original PDF.
"reading the original PDF" not "theoriginal"

fix(recap_document.html) typo: "the original"

---

cl/opinion_page/templates/view_docket.html

If you click on the "Get direct link to this row" button when viewing a docket in RECAP, it creates a link that doesn't work. The issue is that the name of the anchor has an extra hash (`#entry-1`) in it, which requires that the URL have two hashes (`##entry-1`). It's much more straightforward and expected to just remove the hash from the name of the anchor.
To reproduce: Go to https://www.courtlistener.com/docket/16428192/citizens-for-responsibility-and-ethics-in-washington-v-michael-r-pompeo and click on the share button by docket entry 6.
Currently it produces a link that doesn't work: https://www.courtlistener.com/docket/16428192/citizens-for-responsibility-and-ethics-in-washington-v-michael-r-pompeo/#entry-6
You can modify the URL such that it works by adding an extra hash: …

Fix anchors in docket view page

---

DEVELOPING.md

I got tripped up by this line in the documentation, and at first tried copying `05-private.example` to `11-private.py`, which didn't work. This PR fixes the filename, clarifying what the example file should be copied to.

Fix the name of a settings file in documentation

---

docker/courtlistener/docker-compose.yml

The [Selenium docker image documentation](https://github.com/SeleniumHQ/docker-selenium/blob/master/README.md#running-the-images) says that the host's shared memory should be mounted into the container. By default, docker provides only 64MB in `/dev/shm`, which is small enough that Chrome and Firefox tend to crash under load.

Pass host's shared memory to Selenium container

---

cl/alerts/tests.py
cl/favorites/tests.py
cl/search/tests.py
cl/tests/base.py
cl/tests/test_feeds.py
cl/tests/test_issue412.py

This PR changes all Selenium tests to use a separate `submit()` call to submit all forms, rather than passing a string ending with `'\n'` to `send_keys()`. This paves the way for using Firefox in Selenium testing, if that's necessary, plus I think it looks a bit nicer.

refactor(tests): send_keys('\n') => submit()

---

.github/workflows/black.yml
.github/workflows/tests.yml

This will do a shallow clone of the repository, which will speed things up. See also #1059.

Update to actions/checkout@v2-beta

---

cl/citations/columbia/consts_and_statutes.py
cl/people_db/import_judges/fjc_appointers.py

I noticed the code formatter is failing on two disused files with invalid syntax. This PR makes a couple quick fixes so that they can be parsed.

Fix syntax errors in old files

---

cl/tests/base.py

A new feature in recent versions of Chrome is sometimes causing actions from UI tests to be lost immediately after page navigations. Disable that feature as a workaround.
This is part of #1065. Upstream issue is at https://bugs.chromium.org/p/chromium/issues/detail?id=1033941. I have tested this locally, and it seems to have gotten rid of at least one intermittent failure source.

fix(tests): Disable "Paint Holding" in Chrome

---

cl/assets/templates/base.html
cl/search/templates/homepage.html

PR tweaks homepage to underline the opinions DB.  This brings it in line with css for the remaining archive search homepages.

feat(homepage): Add indicator on homepage that search is for opinions db

---

cl/cleanup/management/commands/fix_tax_court.py

Cleanup method added to function to fix wrong precedential status to roughly 8100 cases.  The tax court scraper incorrectly assigns precedential status to T.C. Memo cases.

1153 fix tax p status

---

cl/citations/find_citations.py
cl/citations/models.py
cl/citations/tests.py

This PR fixes the errors causing the new citation extraction code to crash. Two kinds of errors are addressed:
1. `IndexError`. If an _earlier_ index is being referenced (e.g., `words[reporter_index - 1]`), this is fixed by only allowing the code to run if `reporter_index >= 1`. If a _later_ index is being referenced (e.g., `words[reporter_index + 1]`), this is fixed by wrapping those lines in `try/except` blocks.
2. `UnicodeDecodeError`. This error is difficult for me to reproduce. What I've done here is to just change the code that triggered this stack trace (which was for a `ShortformCitation`) to mirror the exact way that we do string interpolation in the existing code (for a `FullCitation`, referencing `self.__dict__`). I'm honestly not sure if this will fix the problem, but if the …

Issue 1171 citation crashes

---

cl/citations/find_citations.py
cl/citations/models.py
cl/citations/tests.py

This changes the generated HTML to include the page numbers after an "Id." citation (or at least what we guess are the pages numbers) within the `<a>` tags. So now, e.g., this entire string will be linkified: `Id., at 325.`
I accomplished this by creating a subclass `IbidCitation` which inherits from `IdCitation`, and then overriding the `as_html()` method to tailor the generated HTML for each type of citation.

Issue 1173 id. citation page linkification

---

cl/citations/find_citations.py
cl/citations/tests.py
cl/lib/roman.py

This PR should hopefully fix the various regex errors described in #1182.
I first added some test cases to replicate those errors, and confirmed that they failed. Then, I refactored the `parse_page()` method to ensure that the parsed page is actually *returned* -- the regex errors were being caused by weird page numbers passing the parsing process, but not actually being returned in their parsed form. Thus, if those weird page numbers included a parenthesis or a backslash (for example), that character would make the generated regex unbalanced.
Because we're still using Python 2.7 and therefore don't have access to the fun new "walrus operator," I basically refactored the entirety of `parse_page()` in a way that I think is more intuitive and avoids repeating regex strings. I also had to …

Issue 1182 fix malformed citation regexes

---

cl/api/management/commands/cl_make_bulk_data.py
cl/api/tests.py

Simple PR that just tweaks the `psql` dump command to also output the `OpinionsCited.depth` field. I also added a test that doesn't really do much, but at least checks whether the mock `OpinionsCited` objects do indeed exist in the database.

feat(api): Expose citation depth data via bulk API.

---

cl/api/templates/bulk-data.html

I should have included these changes in #1184, but here they are now. Just updates the API documentation to reflect the new `depth` field for `OpinionsCited` objects.

fix(api): Updates Bulk API documentation for new citation data.

---

cl/users/forms.py
cl/users/migrations/0007_add_is_tester_field.py
cl/users/models.py
cl/users/templates/profile/settings.html

Added "is_tester" field to user profiles and updated settings view accordingly.
By introducing the new settings variables, users can choose to participate in beta testing of new features like the recommender system.

Let users test new features themselves

---

cl/search/forms.py
cl/search/templates/includes/order_by_dropdown.html

Added ability to sort by docket entry date, for users who've opted into beta features only to see if performance is acceptable. This feature is helpful for following new filings by keyword across all cases, even if the case itself is old.
Closes https://github.com/freelawproject/courtlistener/issues/1260

feat(search): added ability to sort by docket entry date

---

cl/alerts/management/commands/handle_old_docket_alerts.py

The previous query didn't excluded users if they had any alerts on
non-terminated cases. Thus, it only found users that *exclusively* had
terminated cases. This one finds users that have at least one
terminated case.

fix(alerts): Correct user query and optimize logger

---

cl/opinion_page/forms.py

Unfortunately our new uploader passed blocked statuses as "False" instead of False.  
Same is true for is date approximate.

Fix TN uploader bug

---

cl/citations/tasks.py
cl/citations/tests.py
cl/citations/utils.py

Fixes #1355. Solution is to just remove citations whose regexes are duplicates. Implementation is inspired by the existing `fuzzy_eq` and `fuzzy_hash` methods on the `Citation` object. Besides fixing the aforementioned bug (for which a test is added), this may also save us some CPU cycles -- since I think applying regexes is costly, and this will cut down on the number of (duplicate) passes we have to make through each opinion's HTML.

fix(citator): Removes duplicate citation regexes before modifying HTML.

---

cl/citations/tasks.py
cl/citations/tests.py

Fixes #1386 by making sure we remove `NonopinionCitation` objects _before_ we try calling `as_regex()` on them. Diff is messy because I also consolidated and moved this logic to the beginning of the `create_cited_html()` function, rather than duplicating it.

Issue 1386 fix nonopinioncitation hash

---

cl/search/views.py

I noticed today that when doing a person search, the state court tab doesn't have any entries. That's unfortunate, and it looks like it's been that while for quite a while. This should fix it.

fix(court picker): Show state courts on people search

---

cl/corpus_importer/tasks.py

InternetArchive uploader failed when it could not hash the string like object we create from the recap json. 
The fix is to turn the string like object into a bytes like object and feed that into the IA uploader.

fix(corpus_importer.tasks): Fix IA upload_recap_json bug

---

cl/citations/reporter_tokenizer.py
cl/cleanup/tests.py
cl/corpus_importer/import_columbia/analyze_import_exceptions.py
cl/corpus_importer/import_columbia/convert_columbia_html.py
cl/corpus_importer/import_columbia/html_test.py
cl/corpus_importer/import_columbia/parse_judges.py
cl/corpus_importer/import_columbia/parse_opinions.py
cl/corpus_importer/import_columbia/regexes_columbia.py
cl/custom_filters/templatetags/text_filters.py
cl/lib/pacer.py
cl/lib/string_diff.py
cl/people_db/import_judges/populate_fjc_judges.py
cl/recap/management/commands/pacer_iquery_scraper.py
cl/search/constants.py
cl/search/forms.py
cl/simple_pages/views.py

PR attempts to resolve the remaining python3 regex string requirements found in #1438.  
Python 3 dislikes a number of regex patterns and requires the flag r"" for these patterns.

fix(cl): Fix invalid regex sequences

---

cl/citations/find_citations.py
cl/citations/tests.py

#1444 PR fixes a bug in the citation disambiguation code.  
Previously disambiguation did not check if we had found a citation year before attempting to use citation year to disambiguate a citation.  Fix checks for citation year and adds two tests to handle with and without scenarios.

1444 failing cite disambiguation

---

cl/api/tests.py
cl/api/urls.py

#1439 PR creates a simple selenium test to validate the api root can load.  
Add test that django rest framework loads properly.
Give API root name to identify it
During the py3 conversion poetry failed to catch a necessary markdown
bump required by django rest framework.  This selenium test validates that
it is properly working.

feat(api/tests.py): Add test for django rest framework loading

---

cl/settings/10-public.py

PR updates AWS boto3 settings
AWS_QUERYSTRING_AUTH added to settings
AWS appends aws_access_key, signature, and expiration to
urls even though the files are already marked as public
This change removes the automatic appending of auth to the url strings

fix(10-public): Add AWS_QUERYSTRING_AUTH setting

---

cl/settings/10-public.py

PR updates financial disclosure importer
Update timeout on extraction to 43,200 seconds or 12 hours 60 * 60 * 12

feat(10-public): Bump timeout to 12 hours for disclosures

---

cl/disclosures/utils.py

Fix bug that failed to verify PDF filepath was not none.
Caused incorrect attempts to PDF nothing.

fix(disclosure.utils): Fix has_been_pdfed

---

LICENSE.txt

This corrects a mistake where the GNU General Public License
was mentioned instead of the GNU Affero General Public License
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

Clarify AGPL license

---

cl/tests/base.py

This implements #1309, reusing one Selenium browser instance per test class. While the Selenium documentation [doesn't recommend this](https://www.selenium.dev/documentation/en/guidelines_and_recommendations/fresh_browser_per_test/) it does seem to reduce test suite time by 12s for me, so it's impossible to say if it's bad or not.

Test setup refactor

---

cl/citations/annotate_citations.py
cl/citations/tasks.py

The only real change is on line 106 of `tasks.py`; everything else is just some typing clean up to hopefully help `mypy` catch this error in the future.

fix(citator): Fixes #1710 by deleting unmatched citations before save.

---

cl/corpus_importer/management/commands/harvard_opinions.py
cl/corpus_importer/tests.py
cl/opinion_page/templates/view_opinion.html

PR Updates Harvard Importer
Adds intensive method to check for duplicate content in scraped opinions or previously ingested opinions so as to avoid duplicates.  
If duplicates are found - citations are added where appropriate.
Citation adding code has been extracted to its own method.
Type hints has been update and improved

Update harvard importer

---

cl/lib/tests.py
cl/lib/utils.py
cl/opinion_page/views.py
cl/search/fixtures/test_objects_search.json

#1732 
This PR provides resolves issue #1732 and filters volume citations by page number.  
Currently we use Date filed which causes the list to be out of sequential order.

1732 citation page order

---

cl/corpus_importer/management/commands/harvard_opinions.py

PR addresses #1736 
Technically I think we should delete these opinions - but we can instead avoid them and log them for now.
Either way its probably good to check.

fix(harvard_opinions): Need to catch empty CL opinions

---

cl/lib/utils.py
cl/opinion_page/templates/volumes_for_reporter.html
cl/opinion_page/tests.py
cl/opinion_page/views.py
cl/search/fixtures/test_objects_search.json

PR for better citations
Issue #1599 -- Citation Look Up Tool: return opinion with contained page number
PR provides a better slug/url string for citations, volumes and reporters.
PR also makes citation volumes and reporter pages dynamically private.

Better urls for citations

---

cl/people_db/templates/view_person.html
cl/people_db/views.py

Only for judges with disclosures,
Add Financial disclosures to people page
linking directly to their annual filing
as a beautiful PDF

feat(Disclosures): Add financial disclosures to People page

---

cl/opinion_page/templates/includes/note_illinois_court_modal.html
cl/opinion_page/templates/view_opinion.html

Added comment for all opinions from the **Illinois Supreme Court** and **Illinois Appellate Court**, which warns about the 21 days period of time that a party is given to request a rehering, which might result in the nullification of the opinion or ruling. Also, that the court system is not updated immediately after this nullification takes place.
Complement to Juriscraper issue:
https://github.com/freelawproject/juriscraper/issues/405
#1800

Added comment about withdrawal of opinions in Illinois courts

---

cl/corpus_importer/tasks.py
cl/lib/celery_utils.py
cl/tests/runner.py

Added exceptions to handle when PACER free opinion scraper fails due to server response returning an invalid HTML page or other type of document.
Some court's servers block requests to scrap opinion documents. But if the returned page is not a proper HTML page, the parse fails and this error wasn't properly cought and logged.
Closes: freelawproject/juriscraper#418

Added exception when PACER free opinion scraper fails when response is invalid HTML page

---

cl/people_db/management/commands/cl_import_judges.py

PR fixes cl-import-judges management commands.
At some point code to assign authors to opinions was in the CL code base but that code no longer 
exists.  This simply removes the leftover code that causes import errors and/or clutter

refactor(cl_import_judges): Remove unused import code

---

cl/corpus_importer/management/commands/import_tn.py
cl/corpus_importer/test_assets/tenn_test_files/tn_corpus_test_asset.json
cl/scrapers/management/commands/cl_scrape_opinions.py
cl/search/models.py

There is a crash in Harvard opinions that is created when we have the incorrect citation type in our database (mostly from scraped opinions).  
I think we should trust eyecite more than juriscraper to identify the different citation types. 
Related to and hopefully a fix for #1851 
Related to #1850

Citation mismatch

---

cl/corpus_importer/management/commands/harvard_opinions.py

Fixes 1846
We have a bug in the validate date portion of the Harvard importer.
It would just crash is the date was a mysterious leap year, but unfortunately marks everything as approximate as well.
This PR resolves that bug, but we may need to undo the approximate / non approximate mistake.

1846 harvard date bug

---

cl/corpus_importer/management/commands/harvard_opinions.py

Fixes a bug we had found but not resolved
in washington. 
Here we are using our improved reliance of reporter-db to decide
the reporter type.

fix(harvard): Adds better support for reporter types

---

cl/corpus_importer/management/commands/harvard_opinions.py

Remove extra whitespace in citations that may
cause get citations to fail
Make glob paths generation systematic across the
variations.  We had a // double slash that
was showing up in the filepaths

refactor(harvard): Cleanup Harvard Importer

---

cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py
cl/scrapers/management/commands/cl_scrape_opinions.py

Simple one line fix.  Remove failed citations during scraping.
If a citation fails to parse, it should be logged
into sentry and the process should continue instead
of crash.

feat(cl_scrape_opinion): Remove failing citations

---

cl/citations/match_citations.py
cl/citations/tests.py

This should hopefully fix #1888. The latest versions of eyecite changed some of the modeling inheritance so not all `FullCitations` necessarily have the same metadata attributes (for good reason).
The first commit implements two tests that fail by reproducing the court attribute error. The next commit makes these tests pass by stubbing out the handling of journal and law citations for a future feature upgrade.

Issue 1888 - Fix citation metadata error

---

cl/api/management/commands/cl_make_bulk_data.py
cl/api/management/commands/make_bulk_recap_data.py
cl/api/tasks.py
cl/api/utils.py
cl/corpus_importer/management/commands/dump_opinions_as_html.py
cl/lib/utils.py
cl/scrapers/management/commands/scrape_harvard_ia.py

Previously if you add a court after bulk generation
which takes multiple days, the system will crash.

Add error handling for new courts in bulk generation

---

cl/assets/static-global/css/override.css
cl/citations/description_score.py
cl/citations/filter_parentheticals.py
cl/citations/tasks.py
cl/citations/tests.py
cl/opinion_page/templates/view_opinion.html
cl/opinion_page/templates/view_opinion_summaries.html
cl/opinion_page/urls.py
cl/opinion_page/views.py
cl/search/admin.py

This PR completes the main implementation of parenthetical functionality begun in #1903. It has two major contributions: 
- A heuristic utility function for ranking `Parenthetical`'s (i.e. the higher the utility, the higher up we should display it on the opinion page). It considers the wording of the text, the length of the text, and the citation count of the source opinion. The function returns a float score between 0 and 1, where 0 is the least useful and 1 is the most.
Because correctness is not objective for a metric like this, we've implemented our tests as head-to-head comparisons of real parentheticals. We've subjectively chosen the better one for each one and set the test to fail if the heuristic algorithm disagrees more than 10% of the time with our human choices.
- Frontend …

feat(parentheticals): Add ranking and frontend views for opinion parentheticals

---

cl/users/fixtures/authtest_data.json
cl/users/models.py
cl/users/tests.py

This solves #1923 @recap.email address generation function to be lowercased   
Added a test to verify the lowercase generation

Issue 1923 - Fix recap.email addresses need to be lowercased

---

cl/recap/tasks.py

Solves RECAP.email local variable `fq` referenced before assignment, instead of using `fq.user_id` changed directly by `user_pk`

Fix 1924 RECAP.email local variable 'fq' referenced before assignment

---

cl/citations/group_parentheticals.py
cl/lib/search_utils.py
cl/opinion_page/templates/view_opinion_summaries.html
cl/opinion_page/views.py

- Make the page description (i.e. the thing that shows in a Slack preview) use the representative from the top group, not the top-ranked summary.
- Slightly raise the similarity threshold for grouping.
- Add a waffle flag that'll let us turn caching on and off while this thing remains in beta so we can easily test any tweaks we make. We can take this one out if we don't want it but I thought it might be useful

Minor tweaks to parenthetical grouping

---

cl/citations/group_parentheticals.py

It still feels a tad aggressive to me. IMO burying a good parenthetical in an inapt cluster is worse than showing some slightly repetitive parentheticals.

fix(parentheticals): Increase grouping threshold to 0.5

---

cl/lib/management/commands/make_dev_data.py
cl/people_db/factories.py
cl/people_db/models.py
cl/recap/factories.py
cl/search/factories.py
cl/tests/providers.py
cl/tests/test_factories.py
docker/django/version.txt
docker/task-server/version.txt
poetry.lock
pyproject.toml

Fixes #1948. 
This PR introduces a new management command, make_dev_data, that can be used in two ways. Without and flags, it will just create some objects. It'll start by making a docket, and then it'll work its way down the chain of objects, making clusters, and opinions, and parentheticals:
manage.py make_dev_data
With flags, you can choose how many items you want:
manage.py make_dev_data --count 10
And you can choose what kinds of objects you want from the following dictionary:
```
FACTORIES = {
0: CourtFactory,
1: DocketFactory,
2: OpinionClusterFactoryWithParents,
3: OpinionFactoryWithParents,
4: ParentheticalFactoryWithParents,
5: PersonFactory,
6: FjcIntegratedDatabaseFactory,
}
```
For example, you can do:
manage.py make_dev_data --count 10 --object-types 1 2 3
That'd make you at …

1948 dummy data script

---

cl/alerts/views.py
cl/lib/ratelimiter.py
cl/opinion_page/views.py
cl/people_db/management/commands/cl_get_ftm_ids.py
cl/search/views.py
cl/visualizations/tasks.py

Django 3.2 got rid of harmful language in a few places. We switched
away from using 'master' for the main branch in git, and this removes
still more insensitive language.
I think allowlist and denylist are a bit clunkier than their
predecessors, but we'll get used to them, and they're what django
used, so it's fine.
Fixes: #1963

fix(dei): Don't use harmful language

---

cl/assets/templates/base.html
cl/custom_filters/templatetags/extras.py
cl/lib/context_processors.py
cl/opinion_page/templates/view_opinion.html
cl/recap/management/commands/pacer_iquery_scraper.py
cl/settings/05-private.example
cl/settings/10-public.py
cl/simple_pages/templates/includes/terms_history.html
cl/simple_pages/templates/terms/12.html
cl/simple_pages/templates/terms/13.html
cl/simple_pages/templates/terms/14.html
cl/simple_pages/templates/terms/latest.html
cl/users/templates/register/logged_out.html
docker/nginx/sites-available/courtlistener.com.conf

This is a fairly straightforward update to remove Matomo and swap in Plausible. This will make our migration to AWS much easier, since we won't be hosting Matomo anymore. 
A couple interesting bits:
1. I added a template tag that lets us only ping Plausible a tenth of the time. Because Plausible doesn't track across pages (by design!), this won't impact too much. We just need to remember that all of our stats are 10× larger than they seem.
2. One of our features is that we update any PACER dockets that get much traffic during the course of a day. We used to do this by hitting the Matomo API, so I updated it to use Plausible's. I think it should be fine, I tested pretty thoroughly locally, but we'll see when it goes live. I might have to come update it again. It does require an API key in …

1962 swap out matomo

---

cl/citations/parenthetical_utils.py
cl/opinion_page/templates/view_opinion.html
cl/opinion_page/templates/view_opinion_summaries.html
cl/search/admin.py
cl/search/factories.py
cl/search/models.py

Just fixes it in the template. I'm landing a handful of other small tweaks, fixes, and features too just to round things out as I went. See the git log for brief explanations. 
The core fix for this issue is in https://github.com/freelawproject/courtlistener/pull/1970/commits/a125a2a69eeb80b4e8e50c9d48a97e251e47f4a6

1969 duplicate representative clusters

---

cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py

In python 3.9 `|=` and `|` [operators changed](https://docs.python.org/3/whatsnew/3.9.html#dictionary-merge-update-operators) and were added as part of the built-in dict class to support merge and update dictionaries.
This change seems to cause the issue, before 3.9 |= worked as a compound operator and it worked for sets as follows:
```
a = {1,2}
b = {2,4}
a |= b
{1, 2, 4}
```
With celery chains, it worked adding a task to the chain.
```
c = chain(
process_free_opinion_result.si(
row.pk,
row.court_id,
cnt,
).set(queue=q),
get_and_process_free_pdf.s(row.pk, row.court_id).set(queue=q),
delete_pacer_row.s(row.pk).set(queue=q),
)
```
After applying: 
`c |= add_items_to_solr.s("search.RECAPDocument").set(queue=q)`
It was equivalent to:
```
c = chain(
process_free_opinion_result.si(
row.pk, …
```

Fixes free opinions scraper =| operator error

---

cl/stats/management/commands/send_events_email.py

This solves #2005 it was an easy fix, the problem was that `MANAGERS` is a tuple in settings, so when sending to MANAGERS is necessary to select the email address.
I checked other parts in the code where we sent messages to MANAGERS and they seem good.

2005 fixes error when sending to managers

---

cl/alerts/tasks.py
cl/lib/email_backends.py
cl/settings/project/email.py
cl/users/admin.py
cl/users/email_handlers.py
cl/users/tests.py

- Added a function to decide whether or not to add the address set in settings as a BCC to messages sent using the custom email backend.
Two new settings added:
`EMAIL_BCC_COPY_RATE = 0.1`
>  - 1: Every message is BCC'ed
>  - 0.5: Half of messages are BCC'ed
>  - 0.1: 10% of messages are BCC'ed
>  - 0: No messages are BCC'ed
`BCC_EMAIL_ADDRESS = "bcc@email.com"`
> - The email address to bcc. 
- Removed the BCC from the alerts task.
- Added email_address search field in the Email objects and also some filters to EmailFlag

2008 add a BCC to messages based on a given percentage

---

cl/api/utils.py

Added GET method to the `EmailProcessingQueueAPIUsers` permission class, to have access to the Email Processing Queue List for debugging purposes.

Added GET permission to recap email endpoint

---

cl/disclosures/tasks.py

PR fixes #1927
We should just set the value code to blank instead of None when None is listed on the form.  
A db fix was instituted for the 149 debts with None as the value code.

fix(disclosures): Set debt value to "" if None is returned

---

cl/settings/project/microservices.py

2 seconds is too short for many audio files
Doctor needs to add timeouts to tests.
bumped audio duration from 2 second to 30

fix(microservices): Update timeout length

---

.github/workflows/tests.yml
DEVELOPING.md

Update readme that states tests dont work without
aws access keys because that is not true anymore!

feat(developing): Drop AWS Keys in tests

---

cl/search/templates/includes/order_by_dropdown.html
cl/search/tests.py

Fixes #2070 
Sets filtering by relevancy and not just by last name.
This seems like a big win.

feat(people): Search judges by relevancy

---

cl/scrapers/tasks.py

Added a retry to `extract_doc_content` and `extract_recap_pdf` celery tasks, due to seems that sentry errors: `Connection aborted.', RemoteDisconnected...` are due to they are not retrying currently.
Also increased the max_retry to 2 for `process_audio_file`

Quick fix to retry cl-doctor tasks and avoid ConnectionError issue

---

cl/corpus_importer/tasks.py
cl/disclosures/tasks.py
cl/lasc/tasks.py
cl/recap/tasks.py
cl/scrapers/tasks.py

Fixed retries for tasks that were not retrying, below I describe the changes made:
- Added `PacerLoginException` on tasks that need PACER authentication.
- Added `RedisConnectionError` (`redis.ConnectionError`) on tasks that interact with Redis: `get_pacer_cookie_from_cache` and `get_or_cache_pacer_cookies`, this is the error that I could see on Sentry when the connection with Redis fails.
- Added `requests.ConnectionError` on tasks that interact with cl-doctor, this is the error I saw on Sentry that those tasks are raising and confirmed with local tests.
- Added `requests.RequestException` on tasks that made requests but we don't not precisely the request error.
-Some tasks that were retried manually, added extra exceptions that I noticed also could fail, like `PacerLoginException` and …

Fixes celery tasks retries

---

cl/corpus_importer/tasks.py
cl/recap/tasks.py
cl/scrapers/tasks.py

- Added new exceptions on tasks based on new events reported by Sentry.
- Added exceptions to retry some parent tasks, yesterday I avoided adding some exceptions to tasks that call other tasks inside that we were already retrying, however,  those tasks are being called as a function so there were no retrying.
`def fetch_attachment_page`: Added retries for `PacerLoginException`
`def get_pacer_doc_by_rd_and_description`: Added retries for `ConnectionError, ReadTimeout`
`def fetch_pacer_doc_by_rd`: Added retries for `PacerLoginException`
`def get_and_process_free_pdf`: Added retries for `ConnectionError, PacerLoginException, ReadTimeout`,  based on new events on sentry
`def process_recap_docket`: Added retries for `ConnectionError, ReadTimeout`  based on new events on sentry
`def …

Added new exceptions to retry tasks

---

cl/search/admin.py

Fix parenthetical admin search error: "Related Field got invalid lookup: iexact", search by foreign key id requires underscore notation instead of accessing _id column directly (https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields)

Fix parenthetical admin search error: "Related Field got invalid lookup: iexact"

---

cl/api/views.py

Add warning on Bulk API page directing users to the GitHub issue #1983

fix(api.views): Add msg for Bulk API Page during downtime

---

.github/workflows/lint.yml

There's an issue with the lint action, seems that the cache is not properly loaded.
So it's necessary to assign a key including the python version as described [here](https://github.com/actions/setup-python/issues/182#issuecomment-1151091964)

Solves lint action cache issue

---

cl/lib/pacer.py
cl/recap/tasks.py
cl/recap/tests.py

Here is a first approach of the method to check and log PACER connectivity from a given court.
I tried to get banned from a court hammering some courts with a lot of requests per second using Jmeter, I stopped it to avoid affecting court performance, however, I didn't get blocked from the court, so I couldn't get a real court block to test against it.
So I reproduced some IP bans to do some testing: 
- At the web server level (e.g: nginx/apache)
- At the firewall level
- Using IPtables
- To detect an IP ban at the web server level or firewall it was necessary to send a `GET` request and it returns a 403 status code.
- An IP ban with IPtables doesn't allow establishing a connection to the server, so it can be detected using a socket connection setting up a reasonable timeout.
Analyzing the …

Check and log PACER court connectivity

---

cl/alerts/templates/docket_alert_email.html
cl/alerts/templates/docket_alert_email.txt
cl/opinion_page/views.py

This is based on @lkj19zpdiDDe code described in #1003 just added some small tweaks and I tested it.
If the document is not available at the moment the Docket Alert is sent the link points to the docket entry with the URL parameter `?redirect_to_download=True` when the user clicks this link if the document is now available it redirects to the PDF hosted by Courtlistener if not it's redirected to PACER.
The text for this link is: `From RECAP if it's available` for the HTML version and `Download PDF from RECAP if it's available` for the txt version, suggestions for a better text are welcomed.

1003 Docket Alert PDF link redirection to local document if it's available or PACER if it's not

---

cl/corpus_importer/tasks.py
cl/recap/tasks.py
docker/django/version.txt
poetry.lock
pyproject.toml

Seeing that see that the is_pacer_court_accessible method didn't break anything after adding to `fetch_pacer_doc_by_rd ` task and confirming that the method is able to detect unavailable courts, the next step is to add the method to other celery tasks that were raising the `PacerLoginException` on sentry:
corpus_importer/tasks.py
`get_and_process_free_pdf`
recap/tasks.py
`fetch_attachment_page`
`fetch_docket`
Let's see if this help to detect some failing courts or we'll take a different approach to detect the root issue of `PacerLoginException`.
- Juriscraper Updated and added a Version Bump.

Add is_pacer_court_accessible method to more recap tasks and version bump

---

cl/recap/tasks.py
cl/scrapers/tasks.py
cl/scrapers/utils.py
cl/settings/project/microservices.py

Following up #2103, there were still some doctor requests issues on sentry, like:
Celery Tasks:
`ConnectionError`
[cl.recap.tasks.process_recap_pdf](https://sentry.io/organizations/freelawproject/issues/3348541548/?project=5257254&query=is%3Aunresolved+ConnectionError&statsPeriod=14d)
[cl.scrapers.tasks.extract_doc_content](https://sentry.io/organizations/freelawproject/issues/3321009155/?project=5257254&query=is%3Aunresolved+ConnectionError&statsPeriod=14d)
These celery tasks had 2 and 3 retries so I increased them to 5 retries.
[cl.recap.tasks.process_recap_email](https://sentry.io/organizations/freelawproject/issues/3389220753/?project=5257254&query=is%3Aunresolved+ConnectionError&statsPeriod=14d)
For this one, it was necessary to add the exception to auto-retry on …

Added and increased retries for failing doctor requests

---

cl/users/forms.py
cl/users/management/commands/cl_account_management.py
cl/users/templates/profile/delete.html
cl/users/templates/register/login.html
cl/users/tests.py
cl/users/utils.py
cl/users/views.py

This should be a fairly simple one:
- Fixes a bug on the account deletion page where we weren't building a URL correctly for people that had tags
- Makes it so we don't delete any account that ever logged in
- Simplifies the account deletion code into a function
- Sets stub accounts to `is_active=False`, something that shouldn't change anything but seems like a best practice

2140 do not delete good accounts

---

cl/alerts/templates/docket_alert_email.html
cl/alerts/templates/docket_alert_email.txt

`Buy on PACER` removed from docket alerts.
Let me know if it's needed an additional text change on the current download link.

Removed buy on PACER link from docket alerts

---

cl/opinion_page/feeds.py

This should help preformance of big dockets significantly. For exmaple, this RSS feed is too big to even load:
https://www.courtlistener.com/docket/15860894/feed/

Limit RSS feeds to 30 items

---

cl/alerts/tasks.py
cl/recap/tasks.py
cl/recap/test_assets/recap_mail_example_1

This solves two corner cases related to `@recap.email` users.
- If users add their @recap.email on PACER with a different case style, e.g: `UserName@recap.email` it was generating a `DoesNotExist` error since `@recap.email` addresses are lowercased.  To solve it now we lowercase `@recap.email` addresses before looking for the `UserProfile` on DB.
- If users add a wrong `@recap.email` on PACER by mistake, we won't be able to relate that email address with a CL user to send it the DocketAlert. In this case, we just ignore that @recap.email address.
As we talked about this case. It would be better to send an email to admins to inform them about this issue so we can recommend to the user to fix the problem. If it's ok I'll add this function on #2156 because I realize that this function would …

Fixes recap.email user doesn't exist

---

cl/alerts/templates/docket_alert_email.txt

I just noticed that for plain text emails we show the buy link even when `docket.pacer_url` can't be built. This copies the if statement from the HTML emails to the plaintext emails so the bug is removed.
If this looks good to you, let's go ahead and merge it once tests pass (or set it for auto-merge, if you like). If you do either of those things, it'll be our first test of a reviewed PR being auto-deployed.

fix(alerts): Don't show buy link in txt emails

---

cl/api/templates/includes/toc_sidebar.html
cl/assets/static-global/js/base.js

The Table of Contents (TOC) was unwieldy. Added bootstrap collapse classes/functionality to list elements that have a sub-list element. Clicking the [+] beside these elements expands the collapsed sub-list. JS should replace the [+] with a [–]. Clicking the [–] should collapse the sub-list. JS should replace the [–] with a [+].
Part of: #2029
Collapsed  
Expanded

feat(toc-sidebar): Add Collapsible Lists

---

cl/recap/admin.py

As we mentioned on #2211 to continue debugging the issue it would be good to have access to `PacerHtmlFiles` on the admin so that we could inspect the HTML files related to the Processing queues objects.

Added PacerHtmlFiles admin

---

cl/simple_pages/templates/coverage.html
cl/simple_pages/templates/help/recap_email_help.html

This is a small update to add info about the new funnel@recap.email trick. Alberto, do you see any reason why this wouldn't work?

Add info about funnel@recap.email

---

cl/alerts/models.py
cl/alerts/templates/docket_alert_new.html
cl/assets/templates/base.html
cl/opinion_page/templates/docket_tabs.html
cl/opinion_page/templates/includes/docket_alerts_button.html
cl/opinion_page/templates/includes/docket_alerts_modal.html
cl/users/templates/profile/delete.html

Added a custom model manager that allows us to count only Subscriptions Docket Alerts.
Changed on templates where using `docket_alerts.count` to `docket_alerts.subscriptions.count`

2222 Fixed Unsubscriptions count towards 15 alerts people get for free

---

cl/opinion_page/templates/view_opinion.html
cl/scrapers/management/commands/cl_scrape_opinions.py
poetry.lock
pyproject.toml

Bump juriscraper for tax court fix
Disable download from defunct tax court urls because they 
refuse to provide permanent links to court documents.

Update tax court opinions

---

cl/simple_pages/templates/help/recap_email_help.html
cl/users/templates/profile/recap_email.html

Responds to user feedback about copy/pasting their @recap.email address. They were getting spaces when doing so. This should fix that.

fix(html): Remove spaces to make it copy/pastable

---

cl/alerts/templates/docket_alert.html
cl/alerts/views.py

If a user tries to subscribe/unsubscribe to/from a Docket Alert that doesn't exist. Show a message and send a `404` error within the response.

Docket Alerts not found fix

---

cl/api/urls.py

By default, if `get_schema_view` doesn't receive a `patterns` parameter it generates API schema based on the global `urlpatterns`. Including webhooks viewset route. Generating the problem.
To solve it now we pass only the `cl.api.urls` paths to `get_schema_view` so that it only generates the schema based on API routes.

Exclude webhooks viewset from API swagger

---

cl/alerts/templates/docket_alert_email.html
cl/alerts/templates/docket_alert_email.txt

The header content for Docket alert was reordered:
HTML Docket alert:
Text Docket alert:
Let me know if that's ok.

Docket Alert header content reordered

---

.github/workflows/lint.yml

This seems to be a better solution for the mypy lint action issue described on #2125
The cache key was updated to be based on `full-python-version` (copied from [poetry](https://github.com/python-poetry/poetry/blob/master/.github/workflows/main.yml#L75) they used to have the same problem) so the link between the venv and the python binary works properly.

Solves mypy lint issue

---

cl/assets/templates/base.html
cl/audio/templates/oral_argument.html
cl/custom_filters/templatetags/extras.py
cl/custom_filters/tests.py
cl/lib/management/commands/make_dev_data.py
cl/opinion_page/templates/docket_tabs.html
cl/opinion_page/templates/view_opinion.html
cl/opinion_page/templates/view_opinion_authorities.html
cl/opinion_page/templates/view_opinion_summaries.html
cl/opinion_page/templates/view_opinion_visualizations.html
cl/people_db/templates/view_person.html
cl/simple_pages/templates/help/donation_help.html

This is another tweak in my efforts to make our SEO better. I think it might help. We have about 1M pages in Google that it thinks aren't canonical. I agree, so this tells good as such. Docs for canonical links are here:
https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls
Also includes:
- alphabetization of `{% load ... %}` tags that was bugging me.
- a tweak to the donation help page
- a tweak to `make_dev_data.py`.

2271 seo add rel canonical

---

cl/corpus_importer/management/commands/bulk_iquery_project.py

This bug snuck by me. The deal is that as we scrape, the data is
changing underneath us. So if we scrape a million un-terminated cases
today, kill the script and strat it on row 1,000,001 of un-terminated
cases tomorrow, that's not where we left off, because in the meantime
a bunch of cases were marked as terminated.

fix(client): Don't repeat open cases

---

cl/users/api_views.py
cl/users/signals.py
cl/users/tasks.py
cl/users/templates/emails/new_or_updated_webhook.html
cl/users/templates/emails/new_or_updated_webhook.txt
cl/users/tests.py

A new task was added to send admins a notification if a Webhook is created or updated.
The data shown in the email are:
Webhook ID: {{ webhook.pk }}
Webhook URL: {{ webhook.url }}
Webhook status: {{ webhook.enabled }}

2276 Send notification to admins if a Webhook is created or updated

---

cl/lib/recap_utils.py
cl/recap/management/commands/reprocess_recap_dockets.py
cl/recap/tasks.py
cl/recap/tests.py
cl/scrapers/tasks.py
cl/search/management/commands/cl_update_index.py

I've added the `add_items_to_solr` task after extracting recap.email documents.
Also added a new option `extract_missed_rd` to `cl_update_index` command:
`manage.py cl_update_index --extract_missed_rd`
This option will query recap documents that need content extraction and extract them.
After analyzing the existing code, I think the best option to retrieve recap documents that need content extraction is to use a query that takes the conditions of the `needs_extraction` property and also evaluating the document `text_plain` content passing it to `needs_ocr`. In the beginning, I was just thinking to do something like  `text_plain=""` to only extract documents that already don't have content but I think is better to use `needs_ocr` so we'll also consider documents that need OCR, this because …

2277 Add items to solr for recap.email and extract missed recap documents

---

cl/recap/mergers.py
cl/search/models.py

This is a different approach from #2294 to solve #2144.
As you suggested, now we're using DB locking to avoid duplicated entries. For this, we're using select_for_update and transaction.atomic()
I tested multiple possibilities to get the DB lock like:
`DocketEntry.objects.select_related("docket").select_for_update().get_or_create(docket=d, entry_number=docket_entry["document_number"])`
Here, other transactions that create/update objects with a foreign key to the related docket are locked until the transaction that created the lock is committed. However, race condition continues to happen here, and duplicated docket entries were created.
Seems that it works like:
- First transaction: 
```
with transaction.atomic():
DocketEntry.objects.select_related("docket").select_for_update().get_or_crea …
```

2144 Avoid duplicate docket entries due to race conditions when adding or updating docket content using a DB lock.

---

cl/opinion_page/templates/volumes_for_reporter.html
cl/search/templates/advanced.html

This just handles two small cases:
1. Sometimes, apparently, google knows about URLs like:
https://www.courtlistener.com/opinion/?q=dateFiled:[2018-10-01T00:00:00Z+TO+2018-10-31T00:00:00Z]
That's not a valid URL (the parameters wouldn't do anything). But they're enough to throw off Google, so we must tell Google what the correct canonical URL is.
2. Google doesn't like these URLs because they lack canonicals as well: https://www.courtlistener.com/c/idaho/40/
We have about a million pages where Google isn't happy with the canonical situation, but these two examples prevent the other 999,996 from getting fixed. So...let's see if this helps.
Ugh. Fun stuff.

feat(seo): Add more canonical tags

---

cl/lib/middleware.py

On XML responses, it might not be present, as we saw with sitemaps.xml.
Fixes: #2307

fix(middleware): Check for context_data

---

.github/dependabot.yml
docker/django/Dockerfile
poetry.lock
pyproject.toml

Seems this is related to: https://github.com/python-poetry/poetry/issues/6328 
Upgrading poetry to the latest version 1.2.1 seems to solve the issue.
- iPython version downgrade reverted
- Removed iPython from dependabot ignore

2318 Fix ModuleNotFoundError: No module named 'pkg_resources' when bumping dependencies

---

cl/donate/templates/donate.html
cl/people_db/templates/financial_disclosures_viewer.html
cl/search/templates/homepage.html

Right now, stupid Google is refusing to crawl 900,000 pages because a few pages have errors. The error? Not having a canonical tag. This adds such a tag to three of the pages that failed. Knowing Google, it'll probably want these tags added to more pages as soon as these three pages are fixed. 
Stupid Google.

fix(seo): More canonicals

---

cl/alerts/tasks.py
cl/alerts/templates/docket_alert_email.html
cl/alerts/templates/docket_alert_email.txt

In the last set of docket alert changes, now we pass a list of docket entries to the email template instead of a QuerySet. So the count method is not working within the docket alert template. 
To fix it now the docket entries count is passed directly to the template.

Fix a misspelling in docket alerts

---

cl/recap/tasks.py
cl/recap/tests.py
poetry.lock
pyproject.toml

This is the fix for https://github.com/freelawproject/juriscraper/issues/570 needed in CL. In addition to the the Juriscraper fix: https://github.com/freelawproject/juriscraper/pull/571  
The issue first happens in CL when opening/reading an email from S3, so initially we try to open the file using `UTF-8`. If it fails then we try using `iso-8859-1`.
Once the Juriscraper fix is merged and released I'll update the Juriscraper version here.

Fix UnicodeDecodeError when reading the email file

---

cl/assets/templates/403_csrf.html
cl/assets/templates/404.html
cl/assets/templates/429.html
cl/assets/templates/500.html
cl/simple_pages/templates/contact_thanks.html
cl/simple_pages/templates/honeypot_error.html
cl/users/templates/register/logged_out.html
cl/users/templates/register/login.html

One of our users recently reported that they saw a Django error page (the yellow and gray one you usually see with DEBUG=True), because they got a CSRF error. I had no idea, but these are shown even when DEBUG=False and, well, they're not very helpful! 
This lands a custom error page that Django will automatically use to deal with this. Small thing, but helpful.
This also fixes some bootstrap class name typos that I bumped into.

Add a custom error page for CSRF errors

---

cl/assets/templates/base.html

When logged in, the newsletter block includes the user's email address. When printing, it's undesirable to have the email address included.
Given the lack of reason to include the newsletter block at all in a print out, I propose to remove it.

Hide newsletter block when printing

---

cl/lib/microservice_utils.py
cl/lib/search_utils.py
cl/recap/tests.py

This solves: #2304
If during a RECAPDocument extraction the file doesn't exist in the storage we catch the error and clean the file-related fields in DB for that RECAPDocument.
The fields cleaned are:
```
filepath_local
sha1
date_upload
file_size
page_count
is_available
```

2304 Clean up RECAP document file-related fields in DB when the file is missing in the storage

---

cl/corpus_importer/tasks.py
cl/recap/tasks.py
poetry.lock
pyproject.toml

As commented in #2162 these errors were being raised when trying to download a PDF but it's not available.
The problem was that these errors were being logged as an error in `update_rd_metadata` so they were also sent to sentry.
So I removed the error logger for these downloads, the error message continues being registered in the related `PacerFetchQueue` and logged as a warning from Juriscraper.
Also, I realized that we were not marking as successful the `EmailProcessingQueue` objects after correct processing. So I added the method to mark it as successful.

2162 Avoid logging unavailable recap documents errors to Sentry

---

cl/users/tasks.py

This is the PR that removes the current retry email celery tasks so it can be merged a week after #2336 is merged. Once there are no more related celery tasks enqueued.

Remove retry email system celery tasks

---

cl/assets/static-global/css/override.css

If an opinion contains a larger image, this overflows on desktop and mobile version:
Desktop version:
Mobile version:
I added a small css class to force images to set max-width to 100% and height to auto so it fits in the opinion container
Desktop version fixed:
Mobile version fixed:

Prevent images inside opinion from overflowing

---

poetry.lock
pyproject.toml

This Juriscraper update fixes PACER PDF downloads returned after a redirection.

build(deps): bump juriscraper from 2.5.25 to 2.5.26

---

cl/api/templates/emails/failing_webhook.html
cl/api/templates/emails/failing_webhook.txt
cl/api/utils.py
cl/lib/email_utils.py
cl/recap/tests.py
cl/users/signals.py
cl/users/tasks.py

This PR implements the disabling webhook logic discussed in #2208 
We'll send email notifications to users every time a webhook event fails according to the following table:
1st failure, Don't notify.
**2nd failure, Notify**
3rd failure, Don't notify.
4th failure, Don't notify.
**5th failure, Notify**
6th failure, Don't notify.
**7th failure, Notify**
**8th failure, Disable webhook and send notification about the webhook disabled.**
- If a user has many failing  Webhook events we'll send notifications for each webhook event until their parent Webhook is disabled.
- A Webhook is disabled when one of their related Webhook events fails to be delivered after the 8th try (initial try +  7 retries).
- This only will disable the parent Webhook. A user can have other Webhook types pointing to the …

2208 Disabling webhooks after consecutive failures

---

cl/api/management/commands/cl_retry_webhooks.py
cl/recap/tests.py

Added  `delete_old_webhook_events`  to the daemon, this method is going to be executed once a day at 12:00 UTC (4:00 PDT).
I set it to delete webhooks events older than 90 days.

Delete old webhook events periodically

---

.github/workflows/lint.yml
cl/api/management/commands/cl_retry_webhooks.py
cl/api/templates/emails/webhook_still_disabled.html
cl/api/templates/emails/webhook_still_disabled.txt
cl/api/utils.py
cl/recap/tests.py
cl/users/signals.py
cl/users/tasks.py

This PR adds a feature that sends an email notification to users if one of their webhooks is still disabled 1, 2, and 3 days after it was disabled.
This is the email template:
- The task is executed within the same webhooks daemon command, however, since this feature needs to be more reliable about being executed once a day some changes were needed.
- The problem that we realized about the `delete_old_webhook_events` method, is that if a previous iteration lasts more than one minute the task might be not executed that day since the execution was scheduled for an exact hour and minute.
- To solve the problem I increased the time window when the task can be executed (10 minutes) and to ensure the task it's executed only once a day I added a Redis key to check if the task was already …

2389 Send notifications if a webhook endpoint is still disabled.

---

cl/alerts/api_serializers.py
cl/alerts/api_views.py
cl/alerts/filters.py
cl/alerts/tests.py
cl/alerts/views.py
cl/api/templates/includes/toc_sidebar.html
cl/api/templates/rest-docs-vlatest.html
cl/api/templates/webhooks-docs-vlatest.html
cl/api/urls.py
cl/simple_pages/templates/help/recap_email_help.html

DocketAlerts API added as required in #2385 
- Support for Docket Alerts CRUD operations on operations `/api/rest/v3/docket-alerts/`
- Added documentation for docket alerts endpoint in REST docs and linked from Webhooks docs.

2385 Added DocketAlerts API

---

cl/recap/factories.py
cl/recap/mergers.py
cl/recap/tasks.py
cl/recap/tests.py
poetry.lock
pyproject.toml

This PR adds support to process and merge appellate attachment pages using the `AppellateAttachmentPage` parser.
As we talked about, the best approach to merge attachments for appellate docket entries is to mimic the appellate docket page where if a docket entry has attachments there is not a main `RECAPDocument`.
- When an appellate docket page is uploaded and docket entries created a main `RECAPDocument` is created for each docket entry.
Then when adding appellate attachments we use the main RD to identify the docket entry where the attachments should be merged in. Then in the following step, the main RD is transformed into an attachment and updated its metadata like the document `description` and `attachment_number`.
- I also noticed a potential issue in case an appellate docket page …

Added support for process and merge appellate attachment pages

---

cl/recap/factories.py
cl/recap/tasks.py
cl/recap/tests.py
cl/tests/providers.py

This PR fixes https://github.com/freelawproject/juriscraper/issues/583 it was not a Juriscraper issue but Courtlistener one.
The problem happens when processing a recap.email notification that contains a valid docket entry but not a magic number at all e.g:
```
<tr><td><strong>Document Number:</strong></td>
<td>
<a href="https://ecf.dcd.uscourts.gov/doc1/04519643911?caseid=228127&de_seq_num=1225&magic_num=" 
>176</a> 
</td></tr>
```
In multi-docket NEFs only one docket entry contains a valid magic number and the remaining ones don't have a magic number like in the example above.
So we iterate through docket entries to check which is the one with the magic number and set the right parameters to download the document in a next step. The problem is that we have been receiving some …

Fix process a recap email notification with no magic number

---

cl/corpus_importer/tasks.py
poetry.lock
pyproject.toml

- Removed court-specific code from `get_document_number_for_appellate` method, so now we'll always look for document numbers in PDF documents and fall back on the download confirmation page.
- Updated Juriscraper to `2.5.28`

Removed court-specific code and bump juriscraper to 2.5.28

---

cl/recap/tasks.py
cl/recap/tests.py

This fixes #2410, I checked the file referred to this error,  it exists and can be processed properly. Seems the issue here was for some reason the email processing couldn't find the file at that moment (maybe a delay or error in S3). 
In order to handle errors like this I thought it's a good idea to add retries for `FileNotFoundError` when opening the S3 file.

2410 Added retries for recap.email FileNotFoundError

---

.dockerignore

I added the 'media' directory to the dockerignore file as this was causing the docker image to take longer to build locally, this happened because if you download files using the management commands to download files from IA this can increase the directory size a lot making the context size bigger.

Add media file directory to dockerignore

---

cl/alerts/tests.py

This solution is the same one I added as part of #2431 however I was thinking that this test is going to continue failing tomorrow (30th and 31st) and in case you need to deploy something tomorrow you can merge this PR to fix the issue. Since I'll be off tomorrow.
> Fixed the test_send_search_alert_webhooks_rates that checks all the rates for sending search alerts. And monthly alerts cannot be run on the 29th, 30th, or 31st, so it was failing (since today is 29th) added time_machine to mock the date.
Then I could solve the merge conflict in #2431 if it's needed.
Thanks in advance.

Fix send_search_alert_webhooks_rates test in case is needed

---

cl/corpus_importer/tasks.py
cl/recap/tasks.py

I've been checking errors on sentry related to `PacerLoginException`.
The task that is raising these errors is `fetch_attachment_page`, checking some related PACER fetch queue objects in CL I detected that most of the tasks succeed after retries (attachment page downloaded and merged or invalid attachment page due to document unavailable). I couldn't find a single one logged into sentry that failed (processing status), there might be some since there are thousands of errors on Sentry, but well this means that even though there are `PacerLoginException`, retries help to fetch most attachment pages properly.
The problem is that all of these `PacerLoginException` are being logged into sentry due to the issue we found some time ago when checking Doctor errors, if a celery task is called …

2160 Avoid sending PacerLoginExceptions to sentry within retries when getting attachment pages from PACER

---

DEVELOPING.md

If you develop on Windows, you will probably run into some issues when trying to run a test that requires selenium.
I've added a solution in the doc for that issue so anyone can run the tests.

Document tip for selenium tests in windows and wsl

---

.github/workflows/sentry-release.yml

This PR fixes the sentry release action, now using the official action from `getsentry`.
Seem to work well.

Sentry release action changed to getsentry/action-release

---

cl/alerts/tasks.py

This PR removes the unused webhooks docket alert task that now lives in `cl/api/tasks.py`
So now should be safe to remove it.

2454 Removed old webhooks docket alert celery task

---

poetry.lock
pyproject.toml

Fixes Kansas and associated courts
Fixes scraper for Kansas scrapers after they appear to have updated their website 
and changed the URL.  No longer requires selenium.

feat(poetry): Bump juriscraper

---

.github/workflows/codeql-analysis.yml
docker/django/Dockerfile

See: https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

feat(ci): Upgrade CodeQL

---

cl/assets/templates/base.html
cl/assets/templates/includes/introducing_notes_modal.html
cl/favorites/tests.py
cl/tests/base.py
cl/tests/test_issue412.py
cl/tests/test_visualizations.py
cl/users/urls.py

This adds a pop-up that shows up once to everybody that's logged in.
The modal is the following:
A `introducing_notes` cookie is set with an expiration of 10 days since we'll remove the modal in a week.
I'll open an issue to remember this should be removed in a week.
- Added redirect from the old favorites URL to the new notes URL.

Added introducing notes modal

---

cl/assets/static-global/css/override.css
cl/audio/templates/oral_argument.html
cl/favorites/static/js/save-notes.js
cl/favorites/tests.py
cl/opinion_page/templates/docket_tabs.html
cl/opinion_page/templates/includes/add_note_button.html
cl/opinion_page/templates/includes/de_filter.html
cl/opinion_page/templates/includes/rd_metadata_headers.html
cl/opinion_page/templates/opinion.html
cl/users/templates/includes/notes-row.html

This PR solves these [comments](https://github.com/freelawproject/courtlistener/pull/2466#issuecomment-1397813325) and #2478.
- Removed Add note duplicated code by using a template include.
- Fixed `notes.html` semgrep suggestions, now using template tags to generate items URLS.
- Yeah, the `hidden-md` worked to hide the ordering text buttons in medium screens, and removed unnecessary CSS.
- About CSS under `min-width: 768`, since we're reusing the main search box CSS which text and placeholder font-size is 16px, this size seems too big for the desktop version:
So these CSS reduce the `font-size` to 12px for screens over 768px, so it looks like this:
On mobile, the 16px is fine: 
But let me know if is ok the 16px also on desktop so I'll remove that CSS. 
- Removed the yellow background …

2478 Complete Notes follow ups

---

cl/api/tests.py

Since `WebhooksProxySecurityTest` will fail if `cl-webhook-sentry` container is not running, I've added a better error message to this test, so developers could check first that `cl-webhook-sentry` is running.

Improve webhook proxy test error message

---

cl/assets/static-global/js/base.js
cl/users/templates/register/register.html

I checked  #2475 error and reproduced it, it happens when an additional register form request is sent before the new user is saved in DB, so the username constraint prevents duplicated users.  This can happen either if the server or the user connection is slow during the registration. 
In order to prevent multiple sign-up requests I added some JS code to disable the register button on submit, so the user is not able to click it again.

2475 Disable register button on submit to avoid duplicate register

---

cl/api/templates/webhooks-docs-vlatest.html
cl/corpus_importer/api_serializers.py
cl/recap/tests.py
cl/users/templates/includes/docket_alert_webhook_dummy.txt
cl/users/templates/includes/docket_alert_webhook_dummy_curl.txt

This PR adds the `docket id` to the docket alerts webhook payload.
- Updated docket alert webhook test dummies.
- Also updated webhooks documentation to describe the change. I also noticed we're referring to the `RECAPdocuments` API instead of the `Docket alerts` API in the CURL example in the documentation, so I fixed it.

fix(webhooks): Added docket id to docket alerts webhooks payload

---

cl/recap/tests.py

I checked the test error in the appellate attachments tests that fails randomly, the problem is that using `DictFactory` the `attachment_number` is randomly generated and when this number is the same for the two attachments in the factory, the tests failed since only 1 attachment is created instead of 2. In order to solve it I made the attachment numbers fixed for this factory.

Fixes appellate attachments tests

---

.github/workflows/lint.yml
cl/api/templates/bulk-data.html
cl/api/views.py
cl/lib/bot_detector.py
cl/simple_pages/templates/help/coverage_fds.html

This is a a small PR to make it so that we detect the Mastodon crawler on CourtListener. By doing this, we should start getting open graph images on certain pages on CourtListener when Mastodon crawls. Their crawler is described here: 
https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json#L3037-L3040
This also adds the financial disclosures to the bulk data docs, since I noticed it was missing.

Tweak: Add mastodon bots to the open graph detector 

---

cl/assets/static-global/css/override.css
cl/audio/templates/oral_argument.html
cl/opinion_page/templates/opinion.html
cl/opinion_page/templates/volumes_for_reporter.html
cl/people_db/templates/view_person.html
cl/search/templates/includes/search_result.html

This PR creates a new single-property CSS class: "select-all." The class is then applied to five template pages. 
The purpose of the new class is to improve UX as proposed in issue #2518 by enabling easy, single-click selection of non-href instances of a docket number text element wherever they may appear on CL. See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) for more details on this CSS property.
Note that the new class was **not** applied to [line 10 in rd_metadata_headers.html](https://github.com/freelawproject/courtlistener/blob/e791704e4c544d5c87490e5ba3b773fa9e0ec1a6/cl/opinion_page/templates/includes/rd_metadata_headers.html#L10) because this is an href instance of the docket number. Adding this new class to an href-wrapped element may result in unwanted …

re #2518 add select-all class to non-href 'docket' numbers

---

cl/opinion_page/templates/includes/rd_metadata_headers.html
cl/opinion_page/views.py

This PR update the `date_filed` on the document page to show the time if is available in the docket entry.
**Time available (with the court timezone).**
**Time not available, only show the date.**

2544 Updated datefiled on document page to show time if available

---

cl/lib/model_helpers.py
cl/lib/tests.py
cl/recap/mergers.py
cl/recap/tests.py

As commented on #2472 this PR introduces the following changes to avoid overwriting dockets due to a bad `docket_number_core` match.
There is a new helper function `clean_docket_number` used by `make_docket_number_core` and `confirm_docket_number_core_lookup_match`, this function cleans the `docket_number` and returns it after recognizing is a valid docket number for a district, bankruptcy or appellate docket (now they must start with two digits, so it matches `dd-d+ format`). It also checks that there is only one valid docket number in the string, if there is more than one or no valid docket number matched an empty string is returned.
So that this method helps us to avoid generating docket numbers for invalid numbers like:
```
Nos. C 123-80-123-82
Nos. 212-213
```
Or if there is more …

2472 Fix overwritten dockets due to docket number core

---

cl/assets/static-global/css/override.css
cl/custom_filters/templatetags/pacer.py
cl/opinion_page/templates/includes/de_list.html
cl/opinion_page/templates/includes/rd_download_button.html
cl/search/models.py

As requested in #2254 this PR removes the PacerDash integration.
As a result, the buttons have been restored to their original state prior to the inclusion of PacerDash.

2254 Removed PacerDash integration

---

cl/simple_pages/templates/help/alert_help.html

- Fixed the default tab to show appellate for partial and no rss feeds tabs in coverage, otherwise the incorrect content is shown (District in Appellate tab by default).
- And removed appellate from Full RSS Feeds since we don't have a full one already.

Fixed RSS Feeds coverage tabs

---

cl/opinion_page/templates/docket_tabs.html

This PR adds the new `select-all` CSS class merged in #2545 to one additional instance of the `docket.docket_number` prop in the docket entries view of the recap archive. I missed this one in #2545.
I also searched for `docket_number`, `docket_Number`, `docketnumber`, and `docketNumber` to see if there were any other instances of this prop that I might have missed the first time through but I found none where adding the new class would be desirable.

add select-all class to docket # on docket page per comment on PR #2545

---

cl/corpus_importer/management/commands/troller_bk.py
cl/corpus_importer/tests.py
cl/recap/mergers.py

This PR contains the following tweaks and improvements that we talked about yesterday:
- Fixed court names that were incorrect.
- Using `map_pacer_to_cl_id` to lookup courts like `neb` or `azb`.
- Reviewing the docket we checked [yesterday](https://www.courtlistener.com/docket/7201587/kristina-m-sosa/) I realized the reason docket entries were not imported is because this belongs to a district court and we were not importing anything after 2018-04-18, the file we were importing was the wrong one. I chose the file incorrectly and we used the one that contained lines removed after 2018-04-18 so that in yesterday test we didn't imported anything. But this mistake helped to realize that the threshold date to start omitting RSS feeds from `district_pacer_courts` should be 2018-4-20 instead of …

Troller BK importer tweaks and improvements.

---

.github/workflows/lint.yml
poetry.lock
pyproject.toml

- bump juriscraper to 2.5.35
- fixed poetry version to 1.3.2 for lint action due to a dependency conflict on 1.4.0

build(deps): bump juriscraper from 2.5.34 to 2.5.35

---

cl/corpus_importer/management/commands/troller_bk.py
cl/corpus_importer/test_assets/import.csv
cl/corpus_importer/tests.py

This implements two of the performance improvements commented on in #2091.
- Moved the `add_items_to_solr` to celery, which took almost half of the processing time in large files with new entries, so this should help a lot.
- Download files concurrently and add them to a `queue` so that we can have some files ahead in memory so no download waiting time when there are files in the queue.
This was implemented using `Threads` and `Queue`, at the beginning the Queue is empty so `download_files_concurrently` starts by downloading `FILES_BUFFER_THRESHOLD` files in case there are less than this number of files in the queue (so the queue don't grow to the infinite, this number might be tweaked according to the behavior in production but in general, 3, I think it should work well).  If the queue …

Troller BK performance improvement by downloading files concurrently and make add to Solr async.

---

cl/alerts/templates/docket_alert_email.html
cl/alerts/templates/docket_alert_email.txt
cl/corpus_importer/tasks.py
cl/recap/tasks.py
cl/recap/tests.py
poetry.lock
pyproject.toml

As required in [#2536](https://github.com/freelawproject/courtlistener/issues/2536) in this PR, we detect whether email content coming from `recap.email` should be sealed or not and mark it accordingly.
The logic works as follows:
- If a `recap.email` attached document was properly downloaded using the magic link, then it's marked as `is_sealed = False`
- If a recap.email attached document has a `magic_number` but the download was unsuccessful, then it is marked as `is_sealed = True`.
- If a `recap.email` attached document does not have a `magic_number`, then an additional check is performed. The document is queried on PACER, and if a receipt page is returned, then it is marked as `is_sealed = False`.
- If the returned page is not a receipt, it means that it is not available on PACER and …

2536 Detect and flag sealed content coming from recap.email

---

cl/corpus_importer/tasks.py
cl/recap/tasks.py
cl/recap/tests.py
poetry.lock
pyproject.toml

Minute entries from `recap.email` do not have an attached document, so they do not have a `pacer_doc_id`.
This PR adds support for adding entries from `recap.email` without a `pacer_doc_id`, removes a previous validation related to `pacer_doc_id`, and includes a couple more tweaks where the `pacer_doc_id` was required.
- Now the required field to confirm a valid notification is the `pacer_case_id`, which is now obtained from the case URL when there is no attached document.
- Added a test related to `recap.email` minute entries.

2571 Add minute entries from recap email

---

cl/users/views.py

This PR fixes the 500 for unauthorized `WebhookEvent` detail view.
Instead, a 404 error will be displayed.
Let me know if this is ok!

2535 Fix 500 error displaying a webhook event detail when you're not the owner.

---

cl/users/templates/profile/delete.html
cl/users/tests.py
cl/users/utils.py

As requested in #2490 this PR removes user-related history events when a user account is deleted.
- The following user history objects are deleted: 
`DocketAlertEvent`, `AlertEvent`, `NoteEvent`, `UserTagEvent`, `DocketTagEvent,` and `WebhookHistoryEvent`.
- Also `Webhook` and `WebhokEvents` objects are removed when deleting the account.
- `MonthlyDonation` history events are preserved.
- `SCOTUSMap` are not tracked by `pghistory`.
-   Updated the Delete page description to indicate that also Webhook and WebhookEvents will be removed.

2490 Nuke user related history events when deleting user account

---

cl/users/tests.py

- The tests have been updated because creation events are no longer tracked by pghistory.

Fixed tests for nuke history objects when deleting account

---

.github/workflows/lint.yml
cl/recap/management/commands/clean_up_appellate_entries.py
cl/recap/management/commands/remove_appellate_entries_with_long_numbers.py
cl/recap/tests.py

According to #2461, this PR includes a command to clean up duplicated entries after appellate courts enabled document numbers.
In order to avoid unnecessary DB queries, and due to the occurrence of duplicated entries since the court enabled document numbers, I reviewed when courts enabled document numbers so we could only look for duplicated entries after an appellate court enabled numbers.
Thus, I reviewed all the courts that currently use numbers (ca5 and ca11 enabled numbers recently). Other courts have not recently enabled numbers, so I checked older cases from appellate courts that use numbers.
ca2: Uses numbers since older cases I could check in CL.
ca3: Uses numbers  in January 2020
ca4: Uses numbers since older cases I could check in CL.
ca5: Started using numbers on Jan 10, 2023 …

2461 Cleanup duplicated appellate entries after courts enabled document numbers

---

cl/corpus_importer/management/commands/harvard_opinions.py
cl/corpus_importer/tests.py
cl/recap/mergers.py
cl/scrapers/management/commands/cl_scrape_opinions.py
cl/scrapers/management/commands/cl_scrape_oral_arguments.py
cl/scrapers/tests.py
cl/scrapers/utils.py

This PR solves the issue described #2513.
- When creating a new opinion or oral argument using `cl_scrape_opinions`, `cl_scrape_oral_arguments`, or `harvard_opinions`, instead of just creating a new docket alongside the opinion or oral argument, a new method `update_or_create_docket()` is called, which looks for the docket. If the docket exists, it will be updated with the opinion metadata; otherwise, a new `Docket` object will be created.
- The method uses `find_docket_object`, which looks for the docket by `court_id`, `pacer_case_id=None` (since data from opinions or oral arguments don't contain a `pacer_case_id`), and `docket_number`. Internally, `find_docket_object` looks for the docket by `docket_number_core` or `docket_number` and `pacer_case_id=None`.
- I noticed that the …

2513 Look for existing dockets before creating a new one when adding opinions or oral arguments.

---

cl/assets/static-global/js/base.js
cl/opinion_page/templates/includes/redirect_to_pacer_modal.html
cl/opinion_page/templates/recap_document.html
cl/opinion_page/views.py

As required in #2601 this PR introduces a modal instead of directly redirecting to PACER if the document is not available:
- If the user has RECAP extension installed:
- If the user doesn't have the RECAP extension installed:
- This new URL is only for bots right? The docket alert email links continue using the `redirect_to_download` one.
- Also working on this I noticed a JS error message on pages other than the sign-up page.
This is due to the code we added some time ago to deactivate the sign-up button when is clicked. So the form is submitted only one time. To solve it, added an additional condition to only add the listener when the form and button exist in the document instead on all pages.

2601 Redirect to PACER with modal instead of immediately

---

cl/corpus_importer/management/commands/claims_activity_project.py
poetry.lock
pyproject.toml

This PR adds a new command:
`/manage.py claims_activity_project`
By default, it will query reports for all bankruptcy courts from January 1, 2017 to the current day and for the specified creditors.
The command also accepts optional arguments, `date_start`, `date_end`, and `courts`, in case a specific query is needed.
`/manage.py claims_activity_project --date_start 2023-3-24 --date_end 2023-4-3 --courts areb`
The command will create a directory in `/courtlistener/cl/assets/media/claims_activity/` to store the reports and one additional directory for each creditor.
The command works as follows:
- For each bankruptcy court and creditor, do the following:
- Check if an HTML report exists for the court and creditor. If so, skip querying the report. Otherwise, do the query for the court, …

Added claims activity  command

---

cl/custom_filters/templatetags/extras.py
cl/users/templates/profile/alerts.html
cl/users/views.py

Makes the headers of docket-alerts clickable to toggle sort order by the different columns
This only adds the sorting capabilities to docket alerts.  The code can be used with other lists.  All that needs to be done is to add the tags from extras.

Fixes: #2637 Add Sorting Option to Lists

---

.gitignore

Ignore directory/sub-directory settings files for emacs. This will allow for developers to use emacs with CL specific settings, such as indenting rules in templates.

Allow for directory wide settings for the one true Editor

---

cl/api/webhooks.py

I reviewed the entire process of sending webhooks, but I couldn't find anything that might be causing the empty webhook payload `{}` described in https://github.com/freelawproject/bigcases2/issues/128
I made a change on sending the JSON data as bytes using the `data` parameter in the request, I changed it to use the `json` parameter and send a Python dictionary instead. This is just in case there is a problem with encoding the payload (although it would be rare since it would fail every time).
I also added a condition to raise a `ValueError` in case the Python dictionary is empty before sending the request. This way, if there is a problem that I'm not seeing, this exception will help us trace the problem and solve it.
If we continue to receive the empty error in bigcases and no error is …

Raise an error on empty webhook payloads

---

cl/corpus_importer/management/commands/list_of_creditors_project.py
poetry.lock
pyproject.toml

This PR adds a new command `list_of_creditors_project `
That can be run with the following params:
`manage.py list_of_creditors_project --court cacb --file /opt/courtlistener/cl/assets/media/list_of_creditors/cacb-chap-7-2022-first-100.csv --offset 10 --limit 20 `
The command extracts the rows from the CSV to get the docket number and office of each case. Then with this data and using the `PossibleCaseNumberApi` the `pacer_case_id` is retrieved.
Using the `docket_number` and the `pacer_case_id` we query the List of creditor's reports and get the data of each case, store the HTML file (if the command crashes we can run the command again omitting querying reports we already have).
Then the creditor's data is stored in a txt file and an additional CSV file for each txt file is created, in …

List of creditors project

---

docker/django/Dockerfile

Using gthread workers should prevent uploads from timing out at 3 minutes.
See docs:
https://docs.gunicorn.org/en/stable/settings.html#timeout

Switch to gthread workers to prevent upload timeouts with sync workers

---

cl/corpus_importer/tasks.py

As requested in #2597 we needed to spread the free opinion scraper to avoid DB huge CPU spikes.
The whole process is the following:
-  Get and save the free document report rows for each court (`get_and_save_free_document_reports`).
-  Process the free opinion row and save it to the database (`process_free_opinion_result`)
- Download the PDF and save it (`get_and_process_free_pdf`)
- Do the OCR for required items (`ocr_available`).
In the first task (`get_and_save_free_document_reports`) the DB work is creating all the `PACERFreeDocumentRow` for the results returned, in order to slow down this process I added a delay of 0.5 seconds between each row creation.
For `process_free_opinion_result` and `get_and_process_free_pdf`, these are tasks that are already throttled at `2/s` and `1/s`, …

2597 Spread free opinion scraper to avoid DB huge CPU spikes

---

docker/courtlistener/docker-compose.yml

With release 112.0 of Selenium the selenium tagged tests started failing.
As a quick fix we are pinning to the previous version.

Pin the version of Selenium Grid to 111.0

---

cl/corpus_importer/management/commands/list_of_creditors_project.py
cl/corpus_importer/tasks.py
poetry.lock
pyproject.toml

In this PR, the `list_of_creditors_project` command was modified to support querying multiple court CSV files simultaneously.
The `--court ` param was removed.
A new param  `--files` was added, this param needs a list of the court CSV files to be processed, and each file needs to be named with the format `court_id.csv` e.g: `cacb.csv` `caeb.csv`, etc. 
Also, a new param is `--base_path ` (optional), by default is `/opt/courtlistener/cl/assets/media/list_of_creditors` this is the path where the CSV files from the previous param (`--files`) are stored.
e.g:
`manage.py list_of_creditors_project --files cacb.csv caeb.csv canb.csv casb.csv gamb.csv gasb.csv njb.csv scb.csv wawb.csv`
Will process all the rows of each file, the command considers the file with more rows to iterate over all the …

List of creditors project performance improvement

---

cl/corpus_importer/templates/ca_judges_input.html
cl/opinion_page/templates/volumes_for_reporter.html
cl/search/templates/search.html
cl/users/templates/profile/visualizations.html
cl/users/templates/profile/visualizations_deleted.html
cl/visualizations/templates/gallery.html

With the new pagination code the include template commands inserted the "only" keyword.  This strips the context of all variables that are not explicitly passed to the included file.
One of the variables that was stripped was the get_string.  This MUST be there in order for the parameters of the get to propigate within the pagination.

2694 Search pagination broken

---

cl/corpus_importer/management/commands/list_of_creditors_project.py
cl/corpus_importer/tasks.py

This PR fixes the Celery queue set and also the `TypeError` raised when saving the txt file when the list of creditors is empty.

Fix set celery queue on List of creditors project command

---

cl/opinion_page/templates/includes/de_filter.html

The docket page navigation buttons within the filter bar loses any parameters that are on the current page.  That means that it is possible to loose sort order and other parameters.

Add {{ get_string }} to docket page navigation within filter bar

---

cl/scrapers/tasks.py

Fixes another `ResourceWarning` like those in #1414.

Remove unused DEVNULL file handle which isn't closed properly

---

cl/corpus_importer/management/commands/list_of_creditors_project.py
cl/corpus_importer/tasks.py
poetry.lock
pyproject.toml

This PR adds some changes to the list_of_creditors command:
- It is now necessary to set the following environment variables: `CLIENT_PACER_USERNAME` and `CLIENT_PACER_PASSWORD`, in order to avoid using PACER credentials in settings when they are not set.
- The `--queue` parameter is now required.
-  In order to be able to retry tasks that fail when getting the list of creditors POST param. The query process is divided into `query_post_param()` if this fails the task will be retried. If a valid POST param is returned `query()` will be executed and the list of creditors returned.

List of creditors project tweaks

---

cl/corpus_importer/management/commands/list_of_creditors_project.py

This PR applies the fix for the list of creditors `--limit` param, so the limit considers the total processed records instead of rows.

Fix --limit in List of creditors command

---

cl/assets/static-global/css/override.css
cl/opinion_page/forms.py
cl/opinion_page/templates/citation_redirect_info_page.html
cl/opinion_page/tests.py
cl/opinion_page/views.py

The citation lookup tool was designed to easily convert reporter,
volume, page into a citation URL which then redirects to the correct
item, if found.
We have eyecite, which can parse a text and extract a citation.  The
code was revamped to provide a single field which is capable of taking
a citation.
EyeCite then parses that and turns it into a reporter, volume, page and
redirects to the correct item, if found.
This appears to be much cleaner, it allows for cut-and-paste options,
and in general looks like it is a better user experience.
All the `/c/` lookup URLs still work the same way, and the Citation
Lookup Tool home page still has a list of reporters that can be browsed.
Fixes: #2735

2735 citation lookup revamp

---

cl/stats/views.py

It's failing b/c our replica Db is too old. We need to update that DB then revert this commit, but in the meantime, k8s is sad because it thinks our pods are down.

fix(checks): Set postgres to be perma-working

---

docker/django/Dockerfile

I'm suspecting that [with only 1G of memory](https://github.com/freelawproject/courtlistener/issues/2640#issuecomment-1515499685) workers are getting OOM killed. Lets try reducing the threads to see if that helps reliability. Looks like 2-4 threads is [recommended](https://docs.gunicorn.org/en/stable/settings.html#threads).

Reduce threads to try and improve reliability.

---

cl/api/utils.py
poetry.lock
pyproject.toml

In this PR, the client IP for API logs is now being retrieved from the header `CloudFront-Viewer-Address.`
> In a dev environment, this header is not available. However, I added a temporary middleware that adds the "CloudFront-Viewer-Address" to the request. I realized that the `get_header(request, "CloudFront-Viewer-Address")` method used in the `ratelimiter` doesn't retrieve the header if it is set as `CloudFront-Viewer-Address`. This is because the `get_header` method converts it to uppercase and adds `HTTP_`, so the header to look for is `HTTP_CLOUDFRONT_VIEWER_ADDRESS`. However, in the [documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/adding-cloudfront-headers.html), I couldn't find a reference stating that the actual header is …

Get client IP for API logs from CloudFront

---

cl/custom_filters/templatetags/text_filters.py
cl/search/fixtures/test_objects_search.json
cl/search/templates/indexes/opinion_text.txt
cl/search/tests.py

Initially, I thought this issue would be directly solved in Elasticsearch,  but a more detailed investigation revealed that it wasn't.
The issue is not related to the search engine itself, but the method through which the HTML content of opinions is indexed.
It is common for Unicode characters to be represented as HTML entities in HTML. For instance, `§` is represented as `&#167`;.
When indexing the opinion HTML content using the `opinion_text.txt` template, HTML tags are removed but HTML entities are not decoded. So in order to solve this problem I added a new template filter `html_decode` that decodes HTML so that Unicode chars are properly rendered and indexed.
This solution can't be applied right now working on Oral Arguments and ES, since it doesn't contain HTML content. But once …

1486 Fix unicode not rendering properly in search results

---

cl/settings/django.py

We didn't set the default before, which broke a few things like the admin site. We also didn't set staticfiles when not in prod, so this fixes that too.
Fixes: #2759

fix(settings): Fix STORAGES for django 4.2

---

cl/lib/search_utils.py
cl/search/tests.py

This PR fixes #739. 
Queries such as `"leave to file" AND amicus` were being incorrectly transformed into `"leave AND to AND file" AND amicus` leading to a wrong query.
I didn't find additional conjunctions being added around the `AND` or any other conjunctions.
In order to solve this problem in `make_fq`, now queries are split into `phrases` (words enclosed by `"`) and `words` (not enclosed by `"` and not containing whitespace characters). Then conjunctions are added only between words and phrases (omitting conjunctions within phrases).
Also added an additional check and `q.count('"') == 2` here:
```
if (q.startswith('"') and q.endswith('"')) and q.count('"') == 2:
return f"{field}:({q})"
```
So only phrases like `"leave to file"` are passed directly to Solr while phrases like `"leave to …

739 Fix phrase + conjunction fielded search

---

cl/lib/test_helpers.py
cl/search/tests.py
cl/settings/third_party/elasticsearch.py

According to #2629 I have confirmed that emojis are searchable with the current Elasticsearch analyzer.
Added a related test to confirm it.
But I found an issue related to highlighting emojis. The problem lies with the `word-delimiter` filter and its settings, as it splits the Unicode representation of emojis (e.g., U+2696). Consequently, the highlighting process fails to correctly match the emoji within the content.
To address this problem, the solution is to utilize the `preserve_original` setting within the `word-delimiter` filter. By enabling this setting, not only will the tokens be split as before, but the original tokens will also be preserved in the index. This modification allows for proper highlighting of emojis, ensuring they are correctly matched within the content.
The …

2629 Make emoji's searchable in Elasticsearch

---

cl/lib/model_helpers.py
cl/lib/search_utils.py
cl/lib/tests.py
cl/search/tests.py

I applied the same solutions as in #2770:
- Added a proximity query to match docket numbers like `1:21-bk-1234` as `21-1234` in both query strings and the docket number filter box.
- Cleaned the docket number before passing it to Solr to ensure that documents like 1:21-bk-1234 can also be found as 1:21-bk-1234-ABC.
- Added tests for Solr search.
The changes were similar to those made for ES, with some minor variations. Once this is merged, I will update #2770 to resolve any potential merge conflicts since some of the same files were modified.

1645 Fixed search other forms of docket number

---

docker/courtlistener/docker-compose.yml

Now that our selenium python client is updated we should be able to update the docker image.

Update Selenium Grid to use 113.0

---

cl/audio/models.py
cl/lib/date_time.py
cl/lib/search_index_utils.py
cl/lib/tests.py
cl/opinion_page/feeds.py
cl/people_db/models.py
cl/search/feeds.py
cl/search/models.py

The problem here was a bug in `midnight_pt` (renamed from `midnight_pst`) since this method is also used in `Feeds` and not only for indexing dates into Solr, I think it was worth fixing it in general.
Previously, midnight_pst constantly returned a UTC offset of `-7:53` hours rather than the correct offsets: `-7` hours for PDT and `-8` hours for PST. Consequently, this led to erroneous time conversions for dates within PST time, with the offset of -7:53 hours indicating a day earlier than the actual day.

864 Dates in search results vary from those in database

---

cl/api/templates/bulk-data.html
cl/corpus_importer/tasks.py
cl/simple_pages/templates/help/donation_help.html

This removes pandas from the import path in hopes of making things a bit slimmer at least.

2640 reduce memory

---

cl/search/apps.py
cl/search/elasticsearch_files/synonyms_en.txt
cl/search/signals.py
cl/search/tests.py

As required in #2676,  this PR includes a signal receiver to ensure that indexed objects remain synchronized when changes occur in related foreign key objects.
By default, Django Elasticsearch DSL provides receivers for signals such as `post_save`, `post_delete,` and `m2m_changed` in order to keep the main document in sync with the Elasticsearch index.
However, in cases where certain document fields depend on foreign objects, such as the `Docket` in this case, the document is not updated in the Elasticsearch index when the related object changes. To address this, I've added a signal receiver triggered by the `Docket` `post_save` event, which updates the corresponding `AudioDocument` in the Elasticsearch index.
We'd be able to add additional documents to be updated on the `Docket` …

2676 Add signals receivers to keep related indexed objects in sync

---

cl/recap_rss/management/commands/scrape_rss.py

Yeah, the `scrape_rss` `RssFeedStatus` checker was out of control. It wasn't waiting when `--iterations == 0` (loop forever) since the condition to wait was `remaining_iterations > 0` which is a negative value when `--iterations` is `0`.
So the fix is to also include `options["iterations"] == 0` to the condition to wait.

2795 Fix RSS Status checking is out of control

---

cl/asgi.py
cl/settings/django.py
docker/django/Dockerfile
poetry.lock
pyproject.toml

Migrate from WSGI to ASGI

---

cl/workers.py
docker/django/Dockerfile

We need to override the default uvicorn [`CONFIG_KWARGS`](https://github.com/encode/uvicorn/blob/0.22.0/uvicorn/workers.py#L20) to disable lifespan protocol.

Disable lifespan protocol in UvicornWorker

---

README.md
cl/recap/tasks.py

Lets see if we can operate on the zip file bytes without reading the full zip file contents into memory.

Avoid reading zip file fully into memory

---

cl/users/forms.py
cl/users/templates/register/register.html
cl/users/tests.py

We're currently experiencing a distributed attack on the `/register/` endpoint. That'd be pretty much no big deal and would end eventually, when they got bored, except that:
1. Our rate limiter works using IP addresses, so this one being distributed has gotten around that.
2. This has eaten up our ability to send emails via SES:
Sentry, God bless it, has been going crazy with this, since each failed email throws an error. That's how I noticed this was happening.
Soooooo....anyway, this adds a hidden captcha to the register page. Hopefully it'll fix the problem. I haven't tested this because the URL is broken anyway, and testing hcaptcha on dev is difficult, so I'll merge if basic tests pass, and then I'll try it live and watch if the SES charts get better.

fix(forms): Add hcaptcha to /register/

---

.github/workflows/semgrep.yml

When run, `semgrep-action` emits the warning:
```
Unexpected input(s) 'publishDeployment', 'auditOn', valid inputs are ['entryPoint', 'args', 'config', 'publishToken']
```
`publishDeployment` was removed from the action by its maintainers, because it was confusing and unnecessary, given `publishToken` (see returntocorp/semgrep-action#366).
`auditOn` was deprecated in returntocorp/semgrep-action@bb59ba9 and later removed in returntocorp/semgrep-action@6b8098b, because "Semgrep's [underlying] audit mode setting will be removed by 2022 May".
Remove both, as they do nothing but trigger the warning.

chore(workflows): remove deprecated inputs from Semgrep workflow

---

cl/opinion_page/templates/opinion.html

Misuse of `opinions_sidebar.html`, which expects a `list[OpinionCluster]`, for a `list[SCOTUSMap]` generates the correct text (fortunately), but an incorrect URL. Fix this by uncritically copying the `opinions_sidebar.html` include and adapting for the case of visualizations.
Fixes: #2839

fix(opinion_page): correct visualization sidebar links

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docker-build.yml
.github/workflows/lint.yml
.github/workflows/semgrep.yml
.github/workflows/sentry-release.yml
.github/workflows/tests.yml

When run, the majority of the workflow warnings mentioned in #2828 are:
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
```
Node.js 12 actions are deprecated. https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
```
And these can be resolved by upgrading offending actions to more recent versions. After that, the patch adds Dependabot integration so that, prospectively, action upgrades are easier to manage.

chore(workflows): upgrade workflow actions

---

cl/citations/tests.py
cl/lib/test_helpers.py
cl/people_db/factories.py
cl/search/factories.py
cl/search/tests.py

In this PR I added some extra tests to confirm how Judges search works currently under Solr, so we can replicate the same search behavior when moving to ES:
- Order by search relevance and dates.
-  Advanced search queries.
- Search API tests.
- Also replaced fixtures by factories

2810 Added additional search tests for Judges before moving to ES.

---

.github/workflows/codeql-analysis.yml

Address the two remaining warnings from the workflow:
```
1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
```
```
An error occurred while trying to automatically install Python dependencies: Error: The process '/usr/bin/python3' failed with exit code 1
```

chore(workflows): Address CodeQL warnings

---

.github/workflows/docker-build.yml
.github/workflows/lint.yml

When run, the lint and build workflows emit the warning: our workflows:
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
The disabling (initially set for 31st May 2023) has been postponed indefinitely. Nevertheless, the deprecated command should be replaced. Here a minor adjustment will suffice - do it.

chore(workflows): update steps to use new environmental files

---

poetry.lock
pyproject.toml

- Juriscraper release that fixes iquery page parsing mentioned in #2819
@mlissner I guess we can now do normal deployments, right? Since the PostgreSQL issue has been resolved? I'd rather confirm before merging this one.

build(deps): bump juriscraper from 2.5.50 to 2.5.51

---

scripts/make_bulk_data.sh

I've confirmed that the issue in #2852 was due to the version of the PostgreSQL client. 
I tweaked it to install the latest available version `apt-get install -y postgresql-client` (as in Dockerfile) instead of pin version 15.

2852 Fixed make_bulk_data postgresql-client version

---

cl/api/templates/webhooks-getting-started.html
cl/assets/static-global/js/base.js
cl/assets/templates/includes/social_links.html
cl/opinion_page/templates/includes/opinions_sidebar.html
cl/opinion_page/templates/opinion.html
cl/search/tests.py
cl/users/templates/includes/webhook-event-detail.html
cl/users/templates/includes/webhooks_htmx/webhooks-test-webhook.html
cl/visualizations/templates/visualization.html

In anticipation of #1432 (adding Content Security Policy headers), HTML event handlers (`onclick`) need to be replaced. There are only a handful of uses in CourtListener. This branch removes them.

chore(security): replace use of HTML event handlers

---

cl/lib/email_backends.py
cl/lib/ratelimiter.py
cl/lib/redis_utils.py
cl/settings/project/email.py
cl/tests/cases.py
cl/users/tests.py
cl/users/urls.py
cl/users/views.py

This PR fixes #2815.
This PR introduces the following changes:
- Adds a helper function called `get_path_to_make_key`. 
This helper method allows us to use the `path` attribute of the `request`  object as a key to throttle requests. This approach creates a counter that's not linked to the user object or the users' IP but to the path of a page. This counter will update its value every time a user fires a `POST` request to the URL. 
- Adds the new ratelimit decorator to the **registration**, **reset the password**, **change the password**, and **request email confirmation** views.
- Adds a new variable(`SENT_EMAILS_THRESHOLD`) to define the maximum number of emails that can be sent per 24-hour period.
- Adds a helper method to create a counter for emails using Redis.
This helper method …

feat(email): Add protections to the email system

---

.github/dependabot.yml

The first-party actions from GitHub, `actions/*`, are very likely to have coordinated releases; they are prime candidates for an update group.

feat(deps): introduce group for Dependabot updates to actions

---

cl/opinion_page/templates/includes/buy_pacer_modal.html

CSP reports revealed that Bootstrap's modal was making an AJAX request for PACER content when presenting `#modal-buy-pacer`. This is because the framework unhelpfully loads the href of the target element, if present. The fix is to set another attribute, `data-remote` on either the source or target of the modal.
This affects all (~30) uses of `modal-buy-pacer`. And so, rather than correct this at the source, we apply `data-remote` to the target.
Fixes: #2882

fix(security): prevent Bootstrap modal from remote loading

---

cl/assets/static-global/js/base.js
cl/opinion_page/static/js/buy_pacer_modal.js

Through direct and indirect assignments (there are two uses of `cookie-name` used to toggle banners), the following cookies are set:
```
recap_install_plea
buy_on_pacer_modal
no_banner
```
Adjust all to declare cookies to be `samesite=lax`: each are needed in cross-site browsing contexts - e.g. linking directly to a page from outside.

chore(security): set samesite for JS cookie assignments

---

cl/opinion_page/templates/includes/de_filter.html
cl/search/templates/includes/result_type_chooser.html

An invisible change to correct warnings that Chrome gives about some label usages on the search and docket pages:
```
Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.
```

fix(html): correct form label associations

---

cl/search/documents.py
cl/settings/third_party/elasticsearch.py

Working on #2906 where I added an SSL connection for ES for the dev environment and updated Elasticsearch to the latest version (which we plan to use in the cluster). However, the Elasticsearch connection is failing on Github (I'm still trying to identify why), making Elasticsearch related tests to fail.
So that also `parenthetical_group` index creation failed. Consequently, the `Citation` Parenthetical Group tests also failed because the automatic indexing via Django ES DSL signals for `ParentheticalGroupDocument` was enabled, but the connection to the ES instance is not functioning.
This issue led me to realize that something similar might be happening in production as well, considering we don't have an ES server yet. I searched for ConnectionError on Sentry and found the …

Disable ParentheticalGroup indexing signals

---

cl/settings/project/security.py

Two more permissive changes for the policy. These address the outstanding reports that could potentially be caused by CourtListener itself. Those that remain are unreproducible and have not been explainable by any hypothesis apart from browser extensions.

fix(security): amendments to CSP for `media-src` and `base-url`

---

cl/api/views.py
cl/corpus_importer/management/commands/troller_bk.py
cl/corpus_importer/tasks.py
cl/corpus_importer/tests.py
cl/disclosures/tasks.py
cl/disclosures/tests.py
cl/lib/microservice_utils.py
cl/lib/search_utils.py
cl/lib/thumbnails.py
cl/recap/mergers.py
cl/recap/tasks.py
cl/recap/tests.py
cl/recap/views.py
cl/recap_rss/tasks.py
cl/scrapers/tasks.py
cl/scrapers/tests.py
cl/scrapers/utils.py
cl/search/models.py
cl/search/tests.py
cl/simple_pages/urls.py
cl/simple_pages/views.py
cl/users/views.py
poetry.lock
pyproject.toml

We're a bit limited in which handlers can actually use native asyncio until #2703 is merged since django 3.2 does not support async ORM operations. This is an alternative approach to #2701.

Convert some views to native async.

---

cl/alerts/views.py
cl/opinion_page/views.py
cl/search/views.py

This should make our views work again and when the ratelimiter is fixed, we should be able to easily revert the one commit that's here.
Fixes: https://github.com/freelawproject/courtlistener/issues/2930

Remove rate limiters that aren't async

---

cl/users/tests.py

Tests using the django test client should use the async variant which is compatible with both sync and async views while the regular client generally only works with sync views.

Migrate users tests client to asyncio

---

cl/recap/tasks.py
cl/recap/tests.py

When we were using Celery retries, the technique is to throw errors when you want something retried. That makes Sentry noisy in the new approach, so this tweaks things to just exit the function when things fail.

fix(tasks): Don't throw errors, just return

---

cl/api/urls.py
cl/lib/ratelimiter.py

Two small fixes here to make ratelimiters get the user IP correctly, and to remove an old URL that has never worked but recently began failing due to a crawler (might as well remove it).

Remove deprated (broken) URL and fix ratelimiters

---

cl/search/models.py

Unfortunately, somebody is uploading every single doc in this case, and each time they do, our poor server has to pull the massive party information from the DB. Our server stalls while working on this, and this backs up both the DB and Celery, leading to memory problems in celery and a sad, slow DB.
The fix? For now (I hope), a hack to block the case from pulling party information.

Block the J&J talcum powder case

---

cl/search/templates/includes/search_result.html

While the values interpolated into URLs for related searches have recieved HTML escaping, they were not also being encoded for the URL context that they were in.
For example:
```
<a href="/?type=r&amp;q=(&quot;United States v. Ulbricht&quot;) AND docket_id:7195048">
View 11 Additional Results for this Case
</a>
```
This isn't of much practical significance. I mean, there are lots of actions in rem against things identified by URIs, but, sadly, queries for these do not produce any results. Nonetheless, one of the best guards against slip-ups in encoding where it _is_ important is to perform it consistently - even where it is unimportant.
Also:
- consistently encode `:` as `%3A`
- drop `&amp;` where `&` alone will suffice

chore(search_results): encode related results URL parameters

---

cl/citations/annotate_citations.py
cl/citations/tests.py

Eyecite’s `annotate_citations` has an implicit requirement: the content type of `source_text` must be compatible with The `annotations` interpolated into it. In practice, `source_text` should be an HTML fragment.
Here, the output of `annotate_citations` is treated as HTML, but the input `source_text` is never encoded. After annotation, there is no place where encoding could be done without also encoding the annotations themselves; `opinion.source_text` should be encoded (and `<pre>` wrapped, for good measure) as HTML on input to Eyecite.
Fixes: #1491

fix(citations): fix encoding of annotated plaintext opinions

---

docker/courtlistener/docker-compose.yml

`cl-redis`'s use of `6379` conflicts with `bc2-redis` (BigCases) and frustrates parallel development. There's no need for many container ports to be exposed on the host. It is enough that they are accessible within the `cl_net_overlay` Docker network.

chore(docker): drop ports from ancillary containers

---

docker/courtlistener/docker-compose.yml

Unlike other exposed ports that were removed in #2999, this has non-negligible use in development.

chore(docker): pestore cl-postgresql port exposure

---

cl/api/templates/includes/toc_sidebar.html
cl/api/templates/rest-docs-vlatest.html
cl/assets/static-global/css/override.css

Reduce indentations in TOC menu from 40px to 20px to match other pages. Add missing ID attributes to enable using internal anchors when loading page.
contributes to issue #2029

docs(REST API): reformat toc menu

---

cl/api/templates/rest-docs-vlatest.html

As recommended in https://github.com/freelawproject/courtlistener/pull/2685 in this PR I updated docs to mention the `seed` used for random ordering must be an integer.

Added advice about using integers for random ordering.

---

scripts/make_bulk_data.sh

The last backups of July already differentiate between null and empty, but now the problem is that psql by default writes welcome messages or some useful information about what is being executed and if you take a look at the new backups, the first line contains the "SET" message, this is easily solved by removing the first line in order to have the header on the first line.
```
SET
id,pacer_court_id,pacer_has_rss_feed,pacer_rss_entry_types,fjc_court_id,date_modified,in_use,has_opinion_scraper,has_oral_argument_scraper,position,citation_string,short_name,full_name,url,start_date,end_date,jurisdiction,notes
"acca",,,"","","2015-01-09 00:24:40.715+00","t","t","f","113.3","A.C.C.A.","Army Court of Criminal Appeals","Army Court of Criminal Appeals","https://www.jagcnet.army.mil/ACCA",,,"FS","" …
```

Update bulk data script

---

cl/people_db/factories.py
cl/search/tests/tests.py
cl/search/tests/tests_es_recap.py

In this PR, I've added tests to cover the current RECAP Search functionalities and behavior. This will help us avoid regressions when moving RECAP Search to Elasticsearch.
A couple of notes:
- Highlighting on filter terms is not currently working for SOLR. This issue is going to be resolved in Elasticsearch.
- The ordering by `dateFiled` doesn't work properly in the RECAP Search API at the moment. It seems it's using `entry_date_filed` instead of `date_filed`. I added some tests for this but have commented them out. They should pass when we move to Elasticsearch.

Added RECAP Search tests

---

poetry.lock

The current `cryptography` package has been subject of a few vulnerability alert. The upgraded `cryptography` requires a newer version of `pyopenssl` and so these are changed simultaneously (see pyca/pyopenssl#1114).
```
% poetry udpate pyopenssl
% poetry update cryptography
```

build(deps): bump cryptography/pyopenssl versions

---

cl/audio/feeds.py
cl/audio/tests.py
cl/lib/elasticsearch_utils.py
cl/lib/timezone_helpers.py

Verifying the process to migrate OA from Solr to ES, I noticed that the Podcast for Audio was still working exclusively with Solr.
- So, in this PR, I implemented the Elasticsearch version, querying audio documents from ES.
- Audio Podcast tests moved to ES.
- The ES version is also behind a waffle, so we can make a smooth transition once indexing is completed.
I compared the Solr and ES XML versions to ensure that both of them have the same structure and content. The only difference I found was related to the `pubDate`:
`Solr:` Wed, 28 Apr 1999 07:00:00 +0000
`ES:` Wed, 28 Apr 1999 00:00:00 -0700
The two of them represent the same datetime; the Solr one uses an UTC offset of 0, and the ES uses an offset of -7.
The difference is due to Solr storing the datetimes in UTC 0, so it changes …

Move Audio Podcast to Elasticsearch

---

cl/scrapers/management/commands/clone_from_cl.py

`search.Opinion` is not a valid type; replace it with `search.OpinionCluster`.

chore(clone_from_cl): Correct spelling in clone_from_cl

---

docker/django/Dockerfile

Reviewing `Dockerfile.yml`, I thought to myself, who is user 33? The answer is that it is `www-data`:
```
% docker exec -it cl-celery id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```
This is the same user specified for `rss-scraper` and `retry-webhooks`, which both use the user name. There's no reason for `celery` to take a different approach.

chore(docker): use human-readable user name for `celery`

---

cl/search/documents.py
cl/search/templates/includes/search_result.html
cl/search/templates/search.html
docker/courtlistener/docker-compose.yml

This solves the OA indexing issue. Now if a MP3 doesn't exist it's not indexed, instead a warning is logged.
Also:
- Fixed show OA query time in UI.
- Removed ellipsis from OA results.
- Fixed ES dictionaries path in Docker-compose for testing.

Avoid indexing MP3 fields in Elasticsearch that don't exist in S3.

---

cl/alerts/management/commands/cl_send_scheduled_alerts.py

Since cron jobs for `cl_send_scheduled_alerts` are already set, we need to avoid executing this command while the `oa-es-alerts-active` switch is disabled, in order to prevent sending duplicate alerts.

Disable scheduled ES alerts if switch is disabled.

---

.github/workflows/tests.yml

Experimental support for gha (GitHub Actions) caching was introduced two years ago by moby/buildkit@b9d7315. While it continues to be marked as experimental, it should be stable enough for our purposes.

chores(workflows): revise docker/build-push-action caching.

---

docker/django/Dockerfile

It is a best practice for production processes to not run at `root` (also for `root` to be inaccessible via `sudo`). Docker's best practices emphasize this:
> If a service can run without privileges, use `USER`
> to change to a non-root user.
Typically, binding to port `80` requires special privileges and presents a problem, but both `web-dev` and `web-prod` bind on `:8000`; Uniformly use `www-data` user for all Docker images/containers.

chore(build): use www-data user for all services

---

docker/django/Dockerfile

The Docker image, `python:3.11-slim`, that CourtListener are built from, recently stopped working with the installation script that is downloaded and executed for the Poetry tool:
```
RUN curl -sSL https://install.python-poetry.org/ | python3 -
```
Instead of this script, use the installation with `pip` that is a alternative approach which doesn't have this problem and is more direct than the script.
Also in this branch:
- Removal of surplus `POETRY_HOME` argument
- Remove nonoperative `VENV_PATH` environment variable
Fixes: #3079

fix(build): use manual installation for python Poetry

---

cl/opinion_page/views.py

Followup to #3094 after post-deploy testing revealed a missing `/` in path

fix(opengraph): missing slash

---

cl/recap/tasks.py

It looks like we should be processing this as a celery task.

Move send_alert_and_webhook to background celery task

---

docker/django/Dockerfile

After #3110, which manually installed Poetry using `pip`, the binary was no longer in `$PATH` and needed to be addressed directly. This is fine so far as the Dockerfile is concerned, but it is inconvenient when an implementer wants to interact with `poetry` using `docker exec`.
Resolve the issue by creating a `poetry` symlink accessible via `$PATH`.

fix(build): link to poetry in /usr/local/bin/

---

docker/courtlistener/docker-compose.yml

This settings change tells Docker to run the Django app as root, which is needed after the `www-data` change to have the container play more nicely with IDEs (in particular, VSCode, which @ERosendo and I use, but I also ran into the same issue trying it with Fleet).

add user to dockercompose file

---

cl/audio/feeds.py
cl/audio/tests.py

There are some Oral Arguments that its related docket doesn't have a `date_argued` set. e.g: https://www.courtlistener.com/audio/85533/isobel-berry-culp-v-commissioner-of-internal-revenue/
So those OA are triggering the error described in #3153
Reviewing  RSS feed specification it seems that the right thing to do in these cases is to omit the `pubDate` since it's an optional key:
https://cyber.harvard.edu/rss/rss.html#ltpubdategtSubelementOfLtitemgt
So that's the solution in this PR, if there is no DateArgued, `pubDate` is omitted for that item.

3153 Fixed error in Podcast feed when date_argued is None.

---

cl/alerts/management/commands/cl_send_scheduled_alerts.py
cl/alerts/templates/alert_email_es.txt
cl/alerts/tests.py

I noticed that the date range query in the "View Full Results" link within Alert emails was not working properly.
The issue arose because OA Scheduled Alerts are set to trigger at `17:30 PT`, which corresponds to `0:30 UTC`. As a result, the date range for the link was set to the following day in UTC time.
So for example the correct date range for today should be:
`dateArgued after 09/13/2023` but it was `dateArgued after 09/14/2023`.
I fixed it changing  `django.utils.timezone.now()` by `datetime.datatime.now()`, since the Django method uses UTC and `datatime.now()` uses the local time.
Also when testing this fix I found a different error that was logged in [sentry](https://freelawproject.sentry.io/issues/4476263939/?project=5257254&query=is%3Aunresolved&referrer=issue-stream&stream_index …

Fixed alert email View Full Results date range query.

---

cl/lib/context_processors.py

Amazon Smile was discontinued in February 2023.

Delete reference to Amazon Smile

---

.github/workflows/codeql-analysis.yml
.github/workflows/semgrep.yml

The Semgrep and CodeQL workflows have similar purposes, but different triggers. A closure looks reveals that these differences are incidental and that each would benefit from borrowing from the other.
- In 475587, CodeQL was made to run on a schedule only. Only running on `main` and not blocking pull requests is reasonable, but schedule alone is a little odd: Semgrep, a similar task runs `push` and `pull_request`.
- In 52b8f5, Semgrep was made to always checkout `main`. The effect of this rule would be that `main` would be checked any time there was a `push` or `pull_request` (i.e. frequently). This is better expressed by a (sufficiently frequent) schedule and `push` or `pull_request` tied specifically to `main`.

chore(workflows): harmonize triggering of Semgrep and CodeQL

---

cl/search/filters.py

Potentially useful for identifying entries by sequences, lets also add a `isnull` filter option to `entry_number` as that may also be handy here.

Add docket entry pacer_sequence_number filter field and isnull filters

---

cl/search/tests/tests_es_oral_arguments.py

The test that was failing randomly involved the assertion `self.assertNotIn(result.id, ids_in_results)`, which checked that all the results on the current page were "new," ensuring that no results from previous pages were repeated.
This approach seemed to work most of the time. However, it appears that when using random ordering, a result was occasionally repeated on subsequent pages. I was unable to reproduce the error locally, so for now, I just removed that assertion.
Also simplified some variables in the test.

Fixed test_oa_results_pagination failing assertion. 

---

cl/scrapers/management/commands/clone_from_cl.py

I updated the clone command to fix some bugs i found due some fields not being excluded from the creation of the cloned objects and some dates not being formatted correctly.
I also added a new option to clone people positions, this is useful when you are trying to find judges(people object) using last name, court and event date with lookup_judges_by_last_name_list() function.
`manage.py clone_from_cl --type search.OpinionCluster --id 1814616 --clone-person-positions`
I also made the option to index objects in solr optional (this option will be replaced when the elasticsearch implementation is ready for dockets, clusters and opinions)
`manage.py clone_from_cl --type search.OpinionCluster --id 1814616 --add-to-solr`

Update clone command

---

cl/alerts/tasks.py
cl/lib/es_signal_processor.py
cl/people_db/models.py
cl/search/documents.py
cl/search/signals.py
cl/search/tasks.py
cl/search/tests/tests_es_person.py

This PR implements the [UpdateByQuery](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) request to update the fields we duplicate from the `PersonDocument` in position documents.
This PR introduces the following changes:
- Renames the `PEOPLE_DOCS_TYPE_ID` class to `ES_CHILD_ID`.
- Adds a [field tracker](https://django-model-utils.readthedocs.io/en/latest/utilities.html#field-tracker) to the `PoliticalAffiliation`, `School` and `ABARating` classes.
- Adds a new task called `update_child_documents_by_query` to handle  the bulk updates asynchronously.
- Tweaks the signal mapping for positions to use the bulk update method.
- Update the `update_reverse_related_documents` and `update_es_documents` methods to implement the …

Updated child documents by query in Judges.

---

cl/audio/tests.py
cl/lib/elasticsearch_utils.py

The error report was correct, there was a bug that prevented the use of `dateArgued desc` for sorting podcast items. Instead, the relevance score was being used.
The issue arose because I didn't include the sorting clause when using a simplified query in the Elasticsearch podcast query. And we didn't have tests to catch this error. So, I've fixed the issue and added an assertion to tests in order to ensure that `dateArgued desc` is always used for sorting.
So now, podcasts for Jurisdiction for All Courts and for specific courts, as well as search results for podcasts, are now ordered by `dateArgued desc`, displaying the newest results first.

Fix ES podcast items order

---

cl/lib/search_utils.py

PR addresses issue #3187 
When we switch military courts from Federal Special we need to account for that in the court picker.
This was an easier thing to do as we simply needed to make a small tweak.
Also I think we should eventually identify courts as Article I vs Article III

feat(search_utils): Update merge_form_with_courts

---

cl/recap/mergers.py
cl/search/templates/includes/operators_quick_list.html

Somehow we've gotten this error about 9k times today and none before. Somebody is trying to push data to us, so that's great, but boy are we failing at accepting it. 
This should take it over the line to be properly async.
---
Separately, a client told me they couldn't figure out how boosting worked. I tried and failed, and I think we removed the rest of this from the help page already, so I'm yanking the rest of it now.

Make docket sub-attachments async

---

cl/search/templates/indexes/opinion_text.txt

PR Fixes issue #3194 
Tweak opinion_text.txt file to include xml_harvard Without this and the future re-index harvard data
is not actually searchable in solr.

fix(opinion_text.txt): Fix harvard search bug

---

cl/search/management/commands/cl_index_judges_and_positions.py
cl/search/tasks.py
cl/search/tests/tests_es_person.py
cl/search/types.py

This PR adds the command for indexing Judges and Positions (it can be upgraded later to also index other types of parent-child documents).
`manage.py cl_index_judges_and_positions --queue celery`
Also the argument `pk_offset` can be used.
`manage.py cl_index_judges_and_positions --pk_offset 100 --queue celery`
In case the indexing is interrupted we can resume it from the last pk indexed.
So the condition for indexing existing judges is that they meet the `is_judge` criteria.
The `index_parent_and_child_docs` task (throttled) is going to index each judge with all their positions.
Within the task, the parent object is indexed first. If its indexing is successful, then all its positions are indexed in `bulk` using a single ES request.
So, we can evaluate how this works for indexing judges …

Introduced command for indexing Judges and their positions into ES

---

cl/api/views.py
cl/assets/static-global/css/override.css
cl/simple_pages/coverage_utils.py
cl/simple_pages/sitemap.py
cl/simple_pages/static/js/coverage-op.js
cl/simple_pages/templates/help/coverage.html
cl/simple_pages/templates/help/coverage_opinions.html
cl/simple_pages/templates/help/index.html

PR focuses on follow up tasks in issue #3222 
Leaving 
cc @mlissner

3222 coverage followup tasks

---

cl/search/templates/includes/search_result.html
cl/search/templates/includes/search_result_solr.html
cl/search/templates/search.html

This PR fixes the headings in the RECAP search in the Solr version. So the `ms` and the docket entries count are properly displayed.
The problem was those changes for ES needed to be behind the waffle.
I also checked the results in Solr.
The space after the citation court seems to be an old issue since for showing results in Solr we're using the template `search_result_solr.html`  which remained with no changes (for elastic results we're using: `search_result.html`). Anyway hiding the space is an easy fix, so I applied it in the Solr and ES versions.
About the `unknow` date filed, it seems normal, most of the dockets that say that don't have a `date_filed` and just a few do have it but those can be outdated in Solr.

Fixed RECAP Search template conflicts in Solr.

---

cl/search/feeds.py

This PR fixes [COURTLISTENER-50M](https://freelawproject.sentry.io/issues/4544106662/events/latest/) by using the `is_naive` helper method in the `SearchFeed` class before trying to use the `localize_naive_datetime_to_court_timezone` method.

fix(search): Handle non-naive dates in search feed

---

cl/search/documents.py
cl/search/tests/tests_es_recap.py

This fixes: #3246
The problem here was that we were using an `int` to store the entry number, which works well for storing small numbers, however, the problem arises when storing the `pacer_doc_id` in unnumbered entries which can be greater than the `int` range: `-2147483648 - 2147483647`
To solve the issue, a `long` field is required instead. I re-checked the mapping in Solr and in fact, it's using a `long` field too.
Also, the document_number uses a `long`, so I also changed it to `long`.
Also, upon re-checking the document mapping, I found that the `jurisdictionType` field in Solr uses the `text_en_splitting_cl` analyzer. So I've added it to the ES mapping as well, to help reduce the storage size for that field.
In order to apply these changes, we'd need to delete the RECAP index and …

Fixed RECAP ES document mapping to support storing pacer_doc_id as entry number.

---

cl/lib/es_signal_processor.py
cl/search/signals.py
cl/search/tasks.py
cl/search/templates/includes/search_result.html
cl/search/types.py

This PR fixes #3248 the problem here is that Bankruptcy instances that changed were triggering a bulk update of `RECAPDocuments` when the related docket has not been indexed yet. Since almost everything hasn't been indexed. So the solution is just to ignore child bulk updates if the parent document hasn't been indexed in ES.
These bankruptcy instances will be indexed with their most recent data into the Docket and RECAPDocuments when the docket changes and gets updated in ES via signals or when the indexing command reaches the Docket.
I also checked the signals in general in order to be sure signals were not duplicated as #3249 suggested, in fact some of them were duplicated.
This duplication occurred because reverse-related instances, such as `BankruptcyInformation, Education, ABARating, …

3248 Fix multiple issues related to indexing signals.

---

cl/search/tasks.py

Ok, reviewing #3259 the problem there was that we assumed that the indexing command was going to index only new documents, so the "update" case was not considered. 
The ES DSL `save` method, can return two options, `created` and `updated` so the problem was `updated` dockets that didn't match the if statement: `response != "created"`
@ERosendo downloaded a sample of the Docket IDs that triggered this error, and we confirmed that these dockets had already been indexed (by a save signal).
To resolve this issue, I removed the code that checked the response after the save operation. Instead, the code now checks whether the parent document is already indexed. If it is, the process skips indexing the parent document and proceeds to index the child documents in bulk. Otherwise, the parent …

3259 Removed condition to abort indexing of parent docs.

---

cl/settings/third_party/elasticsearch.py

This PR adds a variable to tweak the ES connection's read timeout and sets its default value to 30 seconds. 
This PR should help us lower the number of `ConnectionTimeout` exceptions we get (like https://github.com/freelawproject/courtlistener/issues/3262 and https://github.com/freelawproject/courtlistener/issues/3253) while indexing RECAP documents.

feat(settings): Add a variable to tweak the ES timeout

---

cl/opinion_page/templates/tn-court.html

PR fixes #3269 
When we switched to add maine, it appears we did not adjust the tn-court website 
with regard to how it displays recent opinions.  The old variable naming convention
slightly changed so we need to update it to restore that functionality

fix(tn-court): Update variable name in tn-court

---

cl/alerts/tasks.py
cl/search/management/commands/cl_index_parent_and_child_docs.py
cl/search/tasks.py
cl/settings/third_party/celery.py

This PR introduces a new setting to specify the name of the queue for ETL tasks, the setting uses the celery queue by default and it can be tweaked using an env var in prod. Additionally, it updates  the `Task` decorator of those methods that handle the indexing or updating of Elasticsearch documents to use the new setting.
This PR also includes updates to the `--queue` argument of the `cl_index_parent_and_child_docs` command. The `required` and `default` keywords were previously used together, which doesn't make sense because a `queue` must always be provided when using the command, and the default value is never used. These updates remove the 'required' keyword, allowing the use of the command without providing a value for `queue`, which will default to the new setting. We can use the …

3263 feat add queue for etl tasks

---

cl/search/templates/includes/search_result.html

This PR tweaks the search_result.html template and fixes the issue related to the highlighting in the court field.
The problem arose because the `nbsp` filter first escaped the HTML content of the string and then marked the output as safe. As a result, the HTML tags used for highlighting were displayed as text. This pull request changes the order of the filters to prevent the escaping of the HTML content.

fix(search): Tweak order of filters applied to the court_string

---

cl/lib/es_signal_processor.py
cl/lib/view_utils.py
cl/search/tests/tests_es_recap.py

This solves the issue of triggering save/update indexing tasks when the `view_count` for an object is incremented by the `increment_view_count` method during a user view.
This issue caused a large number of update tasks to be called each time a user viewed a docket page. 
Now, increases in `view_count` are ignored in the indexing signal, which will also address the issue for opinions that use the `increment_view_count` method.

Avoid calling ES save/update tasks when increasing the object view_count

---

cl/search/templates/search.html

This PR tweaks the title tag of the search.html template to accurately display the number of documents.
This PR fixes https://github.com/freelawproject/courtlistener/issues/3251

fix(search): Tweak the title tag to show the total number of docs

---

cl/lib/es_signal_processor.py
cl/search/signals.py
cl/search/tasks.py

This should help with #3143 specifically related to [COURTLISTENER-57S](https://freelawproject.sentry.io/issues/4557024065/?referrer=github_integration)
The conflict errors we're seeing are directly linked to updates made to `DocketDocument` after the associated `BankruptcyInformation` is saved. After reviewing Sentry logs, it became clear that multiple updates for the same docket and `BankruptcyInformation` are being triggered by the RSS Feed scraper. This happens because multiple docket entries for the same docket can exist within a single feed. When these docket entries are merged, each one triggers an update to `BankruptcyInformation` if it contains bankruptcy data. If `BankruptcyInformation` doesn't already exist, it is created; otherwise, it is simply updated.
The issue became …

3143 Fix ConflictError on ES document updates.

---

cl/search/management/commands/cl_index_parent_and_child_docs.py
cl/search/tests/tests_es_recap.py

This PR adds a log in Redis to record the last Parent Document ID that was indexed.
The log is set to update every 1000 documents processed. Therefore, we will only have one entry in Redis, which will include the following keys:
```
"last_document_id": document_id
"date_time": Log date and time
```
The `--auto-resume` flag works as follows:
`manage.py cl_index_parent_and_child_docs --search-type r --chunk-size 100 --auto-resume`
This will resume indexing from the last document ID that was logged in Redis.
If both `--auto-resume` and `--pk-offset` are used together, the `--pk-offset` option will be ignored.

cl_index_parent_and_child_docs command: Log last document ID indexed to Redis and auto-resume flag.

---

cl/alerts/tests.py
cl/audio/tests.py
cl/lib/es_signal_processor.py
cl/scrapers/tests.py
cl/search/tests/tests_es_oral_arguments.py
cl/search/tests/tests_es_parenthetical.py
cl/search/tests/tests_es_person.py
cl/search/tests/tests_es_recap.py

This PR fixes DoesNotExist errors like #3283.
This PR introduces the following changes:
- Adds the [on_commit](https://docs.djangoproject.com/en/4.2/topics/db/transactions/#django.db.transaction.on_commit) function to the different asynchronous tasks fired from the signal processor to ensure that the transaction is finished and successfully committed before the tasks tries to retrieve the new object from the database.
- Adds the context manager [captureOnCommitCallbacks](https://docs.djangoproject.com/en/4.2/topics/testing/tools/#django.test.TestCase.captureOnCommitCallbacks) to capture and execute callback functions in tests where objects are created during execution, such as tests for RT alerts and the percolator.
- Moves tests for ES indexing/update to a new …

3283 fix matching query does not exist

---

cl/lib/elasticsearch_utils.py

This pull request introduces the max_analyzed_offset setting to the highlight query and resolves the issue outlined in https://github.com/freelawproject/courtlistener/issues/3257#issuecomment-1777235639.

fix(elasticsearch): Add the max_analyzed_offset setting to the HL query

---

cl/lib/elasticsearch_utils.py
cl/search/tests/tests_es_recap.py

This PR fixes the issue with the filtering checkbox to display only results with PDFs as described in this [comment](https://github.com/freelawproject/courtlistener/issues/3257#issuecomment-1763430663).

fix(elasticsearch): Add filter to remove results with no children doc

---

cl/alerts/api_serializers.py
cl/api/templates/rest-change-log.html
cl/api/templates/rest-docs-vlatest.html
cl/search/api_serializers.py
cl/search/api_views.py

This partially fixes #3294 by adding the specific IDs the issue calls for, but we have more work to add all the other fields as `*_id` fields — but this is a start.
This also allows deep pagination on the Courts endpoint, since a user is rightly complaining about that.

A few API tweaks

---

cl/lib/es_signal_processor.py
cl/search/tasks.py
cl/search/types.py

As we discussed, the easiest way to resolve the ConflictErrors described in issue #3249 is to retry failed tasks when a `ConflictError` is raised.
The following changes have been implemented in this PR:
- Removed throttling from the ES task where we had initially added it. Since the task signature changes after removing the **`throttling_id`**, I have duplicated these tasks to avoid conflicts, we can remove them later.
- I have also eliminated the old duplicated tasks to prevent errors arising from tasks in the queue.
- In the newly renamed tasks, I added retry logic for **`ConflictError`**. However, during testing, I realized that just retrying the task was insufficient. This is because tasks may be retried almost simultaneously, particularly in the **`update_children_docs_by_query`** …

3249 Added retries on ES ConflictError

---

cl/lib/elasticsearch_utils.py
cl/search/tests/tests_es_recap.py

This PR fixes the full join query by adding children filters to the parent query when using the available_only field.
The filter added in #3301 is intended to return only dockets with available documents that match the search query, it works properly when used independently or in conjunction with parent filters( like the case name) but It's not specific enough and when it's combined with child filters (such as the description filter), it also returns dockets that have a document available but don't match the search criteria.

3257 Show documents properly in the "Only show PDFs" query

---

cl/search/tasks.py

It seems that timeouts suddenly increased after merging https://github.com/freelawproject/courtlistener/pull/3305 the reason seems to be that now that the `update_by_query` requests are no longer conflicting with each other, they tend to take more time to process. As a result, these requests are exhausting the connections or overwhelming the ES responsiveness.
So it seems a good option to use the UBQ [auto-slicing](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html#docs-update-by-query-slice) feature to solve the issue. This would divide bulk document updates into slices that are processed in parallel, reducing the time it takes for `update_by_query` requests to complete.

3309 Add slicing to ES Update by query requests

---

cl/lib/elasticsearch_utils.py
cl/search/templates/includes/search_result.html
cl/search/tests/tests_es_recap.py
cl/settings/project/search.py

As described in #3257 when filtering a single docket using the `docket_id` we need to show a `XYZ total filings. See full docket for details` button if the Case has more entries than the limit inner hits limit in a result (100). 
I've added this button linked to the docket detail page,  it looks like this:

3257 Added "See full docket for details" button on docket_id query

---

cl/search/tasks.py
cl/settings/third_party/elasticsearch.py

The ES bulk API doesn't provide a similar setting to `Slices` like in the Update by query API in order to perform the operation in parallel. 
We're still getting time-outs related to the bulk indexing API, so the solution implemented in this PR is to perform smaller bulk indexing requests processing the documents in batches.
I added the the setting `ELASTICSEARCH_BULK_BATCH_SIZE` to set the size of batches now it defaults to 200.
- I also set the number Update by query slices number equal to the number of shards in the index.
[Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html#docs-update-by-query-slice) says:
> Setting slices to auto chooses a reasonable number for most data streams and indices. If you’re slicing manually or otherwise …

3309 Performs ES bulk indexing in batches to avoid timeouts.

---

cl/alerts/views.py
cl/opinion_page/feeds.py
cl/opinion_page/tests.py
cl/opinion_page/urls.py
cl/opinion_page/utils.py
cl/opinion_page/views.py

This was more complicated than I had hoped because the syndication feeds don't easily allow decorating, so I had to pull the class out of urls.py and put it into a view, which I could then wrap. That caused some circular dependency troubles, but I was able to fix those by adding a utils.py file and doing a small refactor to use it.

Add ratelimiter to feed URLs

---

cl/search/management/commands/cl_index_parent_and_child_docs.py
cl/search/tasks.py
cl/search/tests/tests_es_person.py
cl/search/tests/tests_es_recap.py
cl/settings/third_party/elasticsearch.py

After dividing the bulk indexing of child documents into chunks to avoid timeouts in large cases, the indexing rate decreased. To address this, this PR uses **`parallel_bulk`** instead of **`bulk`** to send chunks to ES in parallel, based on the number of threads. The goal is to improve the indexing rate.
According to the documentation, **`parallel_bulk`** can be memory-intensive. If needed, the following settings can be adjusted to balance memory usage:
- ELASTICSEARCH_BULK_BATCH_SIZE: defaults to 200
- ELASTICSEARCH_PARALLEL_BULK_THREADS: defaults to 5
Additionally, I included a **`--testing-mode`** flag in the indexing command for use exclusively in tests based on **`TestCase`**. This is because the **`parallel_bulk`** approach is incompatible with **`TestCase`** tests due to threading …

Use parallel_bulk for indexing child documents in parallel.

---

cl/alerts/tasks.py
cl/search/tasks.py
cl/settings/third_party/elasticsearch.py

According to [COURTLISTENER-5AM](https://freelawproject.sentry.io/issues/4578580569/), we are still encountering some `ConflictError`s for the `update_children_docs_by_query` method.
I suspect that the issue may be related to the **`refresh_interval`**. The refresh interval could be affecting the **`Update by query`** requests, as these requests also perform a search to retrieve the documents that need to be updated. Consequently, they might be retrieving outdated versions of the documents, leading to **`ConflictErrors`**.
This issue is also discussed here:
- https://discuss.elastic.co/t/elasticsearch-delete-by-query-409-version-conflict/174150/2)
- https://stackoverflow.com/a/66944587
Now that we have extended the **`refresh_interval`** to 5 minutes, as described in issue #3316, this …

Retry update_children_docs_by_query with a minimum delay to avoid ES ConflictErrors

---

cl/lib/es_signal_processor.py
cl/search/tasks.py
cl/search/tests/tests_es_parenthetical.py

As described in issue #3309, we had checks in the signal processor to prevent sending tasks for related documents that don't exist in the index.
When timeouts occurred, these checks could affect data uploads, as they raised errors. We agreed it's better to remove these checks. Such issues are likely to be rare once all indexing is complete; currently, they can still occur since not all dockets are indexed yet.
These checks are also performed within the task itself, so we don't expect errors due to updating instances that aren't indexed, also timeouts will be retried on tasks.

3309 Removed ES document existence checks from the signal processor.

---

cl/search/tests/tests_es_recap.py

This PR adds the `captureOnCommitCallbacks` context manager to the .delete operation in some tests of the `RECAPSearchTest` class.
Prior to this PR, the `test_show_documents_when_combining_the_is_available_filter` test would occasionally fail, I hypothesize that some documents were not removed from the index before the test began.

test(search): Add missing context managers to submit delete transactions

---

poetry.lock
pyproject.toml

It would appear we can now update to psycopg3 as the newer versions of django-pghistory should support it.

Update psycopg2 to psycopg3 and update django-pghistory

---

cl/corpus_importer/management/commands/ready_mix_cases_project.py
cl/lib/elasticsearch_utils.py
cl/search/tests/tests_es_recap.py

This PR adds the required query for the project and it can be run as follows:
`manage.py ready_mix_cases_project --task  query-results --results-size 1000`
The `--results-size` is default to 1000, we can use a greater number in case we got a bigger number of results (we can confirm this from the count in the frontend).
Results will be exported to a json file in `ready_mix_cases/extracted_ready_mix_cases.json`
Each case with the following fields:
```
{
"caseName": "DARRELL DEXTER ready mix HAMPTON",
"chapter": "7",
"court_exact": "nvb",
"dateFiled": "2023-11-02",
"docketNumber": "23-14880",
"docket_absolute_url": "/docket/129/darrell-dexter-ready-mix-hampton/"
}
```
- While testing the query, I noticed that we were not returning results for dockets without documents when filters were …

Added ES query to ready_mix_cases_project command.

---

cl/search/signals.py
cl/settings/third_party/elasticsearch.py

This creates a new env var to disable ES indexing signals for RECAP documents, `ELASTICSEARCH_RECAP_SIGNALS_DISABLED` default `True` so it's not required to set it in K8s now (we'll need to se it to it to False to re enable signals).

Disable ES indexing signals for RECAPDocuments

---

.github/workflows/semgrep.yml

Looks like the [action](https://github.com/returntocorp/semgrep-action) was deprecated and needs to be updated.

Fix semgrep

---

cl/recap/views.py

It would appear that on disconnect(which may happen due to a load balancer timeout) `process_recap_upload` may get prematurely cancelled. To prevent this lets try and shield the upload task from cancellation so that it will finish processing the upload even if the uploader is disconnected.

Attempt to shield recap upload tasks from disconnect cancellation

---

poetry.lock
pyproject.toml

No non-doc changes since previous release other than [this fix](https://github.com/django/asgiref/commit/d920c3c44f59ef037be3a09a41a5640014cfb1e2).

Use asgiref commit with sync_to_async context fix

---

cl/recap/views.py

I think we can revert back to using `asyncio.create_task` now that we have #3357.

Revert "Remove asyncio.create_task for shield"

---

cl/lib/elasticsearch_utils.py

While reviewing #3043, I noticed something unusual in the search queries:
The `query_string` had repeated boosted fields in every request, leading to massive queries that could be affecting memory usage and ES performance.
```
"query_string":{
"fields":[
"case_name_full",
"suitNature",
"juryDemand",
"cause",
"assignedTo",
"referredTo",
"court",
"court_id",
"court_citation_string",
"chapter",
"trustee_str",
"short_description",
"plain_text",
"document_type",
"caseName^4.0",
"docketNumber^3.0",
"description^2.0",
"caseName^4.0",
"docketNumber^3.0",
"description^2.0",
"caseName^4.0",
"docketNumber^3.0",
"description^2.0"
],
"query":"\"08637\" case",
"quote_field_suffix":".exact",
"default_operator":"AND",
"tie_breaker":0.3
}
```
The issue lay in how the original fields (before boosting) were …

Fix repeated boosted fields in ES search queries

---

cl/scrapers/management/commands/cl_scrape_opinions.py
cl/scrapers/management/commands/cl_scrape_oral_arguments.py
cl/scrapers/utils.py

Fixes a Juriscaper issue [#764](https://github.com/freelawproject/courtlistener/issues/3381)
Allow custom header values while getting binaries in Minnesota Supreme/Appellate courts

fix(cl_scrape_opinions): Enable custom header/user-agents

---

cl/opinion_page/templates/opinion.html

Fix #3377 
Fix missing line breaks that sporadically affect our HTML with citations.  Add django filter for line breaks where new lines exist and it cleans up our HTML beautifully. 
Before
After

fix(opinions): Add filter linebreaksbr to html

---

.github/workflows/docker-build.yml

k8s reports that, "error: --rm should only be used for attached containers"

fix(docker): Remove --rm flag

---

scripts/make_bulk_data.sh

Without this, I was getting an error installing the postgresql client. With it, the install seems to work and the bulk data script is exporting data.
Fixes: #3376

Allow dependencies to install properly

---

poetry.lock

Might as well rule outdated transients as the cause of django 5 test failures.

Update all transient dependencies

---

cl/recap/mergers.py

Looks like we currently only handle existing duplicate docket_number's but are unable to create new ones, lets try and fix that.

Handle creation of duplicate docket entries with duplicate docket_number's

---

cl/lib/elasticsearch_utils.py
cl/search/tasks.py
cl/settings/third_party/elasticsearch.py
poetry.lock
pyproject.toml

Following up [#3352](https://github.com/freelawproject/courtlistener/issues/3352) about Transport errors.
I set up a testing ES cluster in AWS with the same settings we have in production to replicate the issue.
Here are my findings:
- I successfully replicated the error after indexing some of the dockets related to the error found at https://freelawproject.sentry.io/issues/4580682651/events/7648526678a447f7a85c347e99d6c41c/. This was achieved by triggering updates on the child documents for many dockets simultaneously (using 20 celery workers).
The **`TransportError`**, specifically **`Trying to create too many scroll contexts`**, was triggered when many UBQ requests were executed simultaneously. Each UBQ request was configured to create a number of scroll contexts equal to the number of …

Update ES client dependencies and disable UBQ slicing.

---

cl/search/tasks.py
cl/settings/third_party/elasticsearch.py

As outlined in https://github.com/freelawproject/courtlistener/issues/3442 automatic retries performed by the ES client during connection failures are not desired for Update By Query requests.
Therefore, it is preferable to disable these retries and manage them exclusively through Celery, where both the number and delay of retries can be controlled. 
This PR introduces a new type of client connection that disables retries for UBQ requests.

Disable HTTP connection retries on UBQ requests

---

cl/opinion_page/views.py
cl/search/models.py

This PR fixes the following issue related to the new authorities tab: 
- [COURTLISTENER-5S5](https://freelawproject.sentry.io/issues/4710002739/): Use the appropriate keywords when calling the view_document_authorities pattern
- [COURTLISTENER-5S6](https://freelawproject.sentry.io/issues/4710014892/): Adds the timezone variable to the context of the recap_authorities.html template. The recap authorities page requires the `timezone` variable to display the date the document was filed.

fix(recap): Fix issues related to the authorities tab

---

cl/recap/mergers.py
cl/recap/tests.py

Ok, we're still encountering some [ConflictErrors](https://freelawproject.sentry.io/issues/4591891908/). Upon reviewing the most recent cases, they seem to be associated with one or two specific fields: **`assigned_to_str`** or **`referred_to_str`**.
Here's the issue:
The RSS Feed data, as parsed by Juriscraper, includes **`assigned_to_str`** or **`referred_to_str`**, but these fields are typically empty.
If a Docket entry already has values in **`assigned_to_str`** or **`referred_to_str`**, and the RSS Scraper then merges another entry for the same docket, the existing values are cleaned. This occurs because the current merging code is: **`d.assigned_to_str = docket_data.get("assigned_to_str") or ""`**.
This cleaning is identified as a change by the field tracker, which then triggers an …

Prevent RSS feeds from clearing assigned_to_str and referred_to_str docket fields.

---

cl/lib/paginators.py
cl/search/tests/tests_es_recap.py
cl/search/views.py

This PR fixes #3334 
The issue resolved in this PR is the limitation imposed by ES default result limit (10,000) on large queries. Previously, the `ESPaginator` relied on this default value, resulting in a maximum of 500 generated pages.
To fix this, the `ESPaginator` now utilizes the accurate total results count returned by `build_es_main_query`. 
It's important to note, that while the paginator can display more than 500 pages, users are still restricted to browsing only up to 100 pages due to the depth pagination limit.

3334 Fix ES search pagination limit

---

poetry.lock
pyproject.toml

This Juriscraper version update contain the fix for https://github.com/freelawproject/courtlistener/issues/3449

Bump Juriscraper 2.5.71

---

cl/search/tasks.py

I checked in detail the ConnectionErrors and ConflictErrors we still getting from ES.
The issue with `ConnectionError` is as follows:
The global ES connection timeout set in production is 200 seconds, and we have set the IDLE timeout in the load balancer to 200 seconds. However, through testing, I've found that the ES client's timeout can exceed this set value. This is because the client appears to add additional timeout when a connection fails:
> Node <Urllib3HttpNode(https://load-balancer-id.us-west-2.elb.amazonaws.com:9200)> has failed for 8 times in a row, putting on 8 second timeout.
And it seems this is a global count for the endpoint so other requests can also increase this value.
Consequently, when the client's timeout exceeds 200 seconds, it surpasses the IDLE timeout set in the …

Added dynamic retry policy for update_children_docs_by_query tasks

---

cl/assets/static-global/css/override.css
cl/assets/templates/base.html
cl/search/tests/tests.py

This PR adds two CSS classes to properly align the icon next to the sign-out button in the navigation bar.
This is how the icon looks now: 
After this PR is merged, the icon should be correctly aligned in all resolutions. Here are some screenshots:

style(base): Add CSS classes to align the icon next to the sign out bttn

---

cl/api/tests.py
cl/corpus_importer/import_columbia/parse_opinions.py
cl/corpus_importer/import_columbia/populate_opinions.py
cl/corpus_importer/tasks.py
cl/donate/models.py
cl/donate/stripe_helpers.py
cl/lib/models.py
cl/lib/pacer.py
cl/search/admin.py
cl/search/api_utils.py
cl/search/documents.py
cl/search/tasks.py
cl/stats/utils.py
cl/users/tests.py

* Drop f from constant strings
* Remove `object` from class declarations. Hasn't been needed since Python 3.
* Get rid of some unneeded list comprehensions

refactor(cl): Refactor and Make Code More Pythonic

---

cl/settings/django.py
cl/settings/project/security.py
poetry.lock
pyproject.toml

This PR fixes #3126 by adding the [django-permissions-policy](https://github.com/adamchainz/django-permissions-policy) package and disabling the browsing-topics feature.

3126-block the browsing topics feature

---

cl/simple_pages/templates/help/advanced_search.html
cl/simple_pages/templates/includes/available_fields.json

I updated the `/help/search-operators/` documentation to add the new fields available in the RECAPDocument mappings.
Also:
- Updated the Phrase section to include an exact query description.
- Updated `Date Queries` for RECAP so once this is live, the syntax will be simpler, this will apply also for Opinions Search.

2779 Updated RECAP related Advanced Search documentation

---

cl/recap/admin.py

This PR fixes #3503 by registering the EmailProcessingQueue to the admin interface and adding a custom action to reprocess recap email records.

feat(recap): Register the EmailProcessingQueue model to the admin 

---

cl/recap/admin.py

This PR adds the `uploader` and `court` field to the list of `raw_id_fields`. This helps avoid displaying all related instances in the drop-down, thereby reducing overhead.

feat(recap): Tweaks details view of the EmailProcessingQueue admin

---

cl/recap/admin.py

This PR adds the `recap_documents` and `filepath` fields to the exclude list.

feat(recap): Exclude some field from the EmailProcessingQueue form

---

cl/opinion_page/views.py

Optimize the ORM query by employing the `prefetch_related` method to remove the `plain_text` field from the list of fields used to display the list of documents associated with a particular Docket entry in the `/docket` page.

feat(docket): Refines the query to retrieve RECAP documents

---

cl/lib/elasticsearch_utils.py
cl/lib/search_utils.py
cl/search/constants.py
cl/search/documents.py
cl/search/tests/tests_es_recap.py
cl/settings/third_party/elasticsearch.py

This PR implements the necessary changes to the ES RECAP index mapping to support the FVH highlighter.
I have added the `term_vector` lists to all fields that are highlighted in the frontend.
Docket Fields:
```
caseName
docketNumber
suitNature
cause
juryDemand
assignedTo
referredTo
court_citation_string
```
RECAP Fields:
```
description
short_description
document_type
plain_text
```
So we can evaluate the impact on the index size if we add term vectors to all the fields that require highlighting. This will help us decide whether to add term vectors to all HL fields or only to those where the FVH represents a significant improvement, especially in fields with large content like **`plain_text`** and **`description`**.
I've made adjustments to the tests to ensure they pass using FVH and also …

Added FVH HL support to RECAP Search

---

cl/simple_pages/coverage_utils.py

This PR addresses #3578 by ensuring query completion on line 25. 
The method now properly awaits query results before executing the conditional statement that skips cycles for courts without data. Additionally, to avoid variable naming conflicts, the variable within the for-loop on line 32 has been renamed to distinguish it from the variable storing each element of the Court queryset.

3578-fix the opinions coverage page

---

cl/simple_pages/coverage_utils.py

This PR fixes a bug introduced in #3579. 
While the previous PR successfully addressed the page loading issue, the variable naming refactor created a bug in the frontend. The new issue specifically affects the list of courts. Here's a screenshot of the issue. 
After cloning several dockets to debug this issue, I realized that we only need the `courthouse` variable to get the name of the state and we shouldn't include its value in the `courts` array. 
The opinions coverage page uses cache so we have to clear the `coverage_data_op` cache key immediately after deploying this PR.

fix(coverage): Adds the appropriate court information the the context

---

cl/scrapers/management/commands/cl_scrape_opinions.py

Addresses #3576 
Adds small tweak to cl_scrape_opinions that checks if 
the scraper has_opinion_scraper is true
Otherwise it skips the scraper.

feat(scrape_op): Add toggle on has_opinion_scraper

---

cl/scrapers/management/commands/cl_scrape_opinions.py
cl/scrapers/tasks.py
cl/scrapers/utils.py
poetry.lock
pyproject.toml

Theses changes are needed to support freelawproject/juriscraper#827
- If possible, get court object from child_court field passed by nytrial families of scrapers. Otherwise, default to parent court. This does not alter behavior for other sources. Solves freelawproject/juriscraper#847
- Pass opinion.html to site.extract_from_text, if opinion.plain_text does not exists. Solves #3549
- Add support to update Opinion object from extract_from_text metadata dict.

feat(scrapers): support nytrial scrapers

---

docker/django/docker-entrypoint.sh

I'm thinking this may cause issues if we have background asyncio tasks running.

Don't kill workers

---

cl/lib/search_utils.py

Working on the Elasticsearch version of **`get_related_clusters_with_cache`** in https://github.com/freelawproject/courtlistener/pull/3043, I realized that the results from the related clusters query are not cached.
The issue was that the results are stored in the Redis cache (which is the default cache), but they were being requested from the database cache.
This issue also exists in the Solr version, meaning that all the related clusters are currently queried every time. Addressing this can help reduce the load on Solr in the meantime while ES Opinions is being launched.
Additionally, I moved a condition that overwrites **`url_search_params`** outside the **`if related_clusters is None:`** block, ensuring that this variable is properly overwritten every time, even if there are results …

Fix cache in get_related_clusters_with_cache

---

cl/assets/react/_useTags.ts
cl/assets/static-global/js/base.js
cl/favorites/api_views.py
cl/favorites/filters.py
cl/favorites/static/js/tag-utils.js
cl/favorites/templates/tag.html
cl/favorites/tests.py

This PR fixes the following bugs related to the tagging feature:
- The "Untag this item" button is not working properly. When the user clicks the button the page is refreshed but the docket is not removed from the tag.
- The dropdown menu for tags on the docket page isn't accurately reflecting which tags are associated with a docket. Even when a case has previously been added to a specific tag, the checkboxes in the dropdown appear unchecked.
The PR introduces the following changes:
1. Adds a new JS filed named `tag-utils.js`. This file has the logic to add onclick events to "Untag this item" buttons ( This fixes issue 1)
2. Tweaks the DocketTagViewSet to properly enable filtering. The current implementation of the class  employs an attribute named `filter_class` for filtering, but this …

feat(favorites): Fix issues with the tag feature

---

cl/favorites/static/js/tag-utils.js
cl/favorites/templates/tag.html

This PR tweaks the code of the `onclick` event that we're adding to the untag buttons. 
The new event handler will avoid reloading the page when clicking the untag button, ensuring an uninterrupted flow and it will compute the list title to reflect the number of remaining dockets after the untag operation.
Here's a GIF showing how the button works:

feat(favorites): Avoids reloading the tag details page

---

cl/opinion_page/tests.py
cl/opinion_page/utils.py
cl/opinion_page/views.py

In this PR, the `es_get_citing_clusters_with_cache` method was introduced, serving as the ES version of `get_citing_clusters_with_cache query`.
The main difference from the Solr version is that the ES version performs a count query. Considering that there are Opinions cited by more than 10,000 other opinions.
Therefore, this additional query is necessary to retrieve the total number of results.

Moved citing clusters query to ES

---

cl/recap/tasks.py

get de_id from DocketEntry instead of RECAPDocument

---

cl/recap/tasks.py

Ok, this should fix other problematic cases related to #3610

3610 Fixed arguments passed to associate_related_instances

---

cl/opinion_page/views.py
cl/search/models.py

This PR addresses Issue #3608 by providing a synchronous option for computing Opinion cluster captions

fix(search): Adds sync version of the helper method to compute captions

---

cl/api/views.py

This PR fixes #3623 by using the `sync_to_async` adapter function to call the `build_alert_estimation_query` method.

fix(api): Use the sync_to_async adapter to fix the alert estimation query

---

cl/lib/es_signal_processor.py
cl/search/tasks.py
cl/search/tests/tests.py
cl/search/types.py

We found that issue #3602 was not completely related to documents not being indexed. After doing some test requests, we discovered that a request like **`/opinion_index/_doc/o_9918845`** returned a 'Not found' response, even though the document had already been indexed, as confirmed by a search query.
However, the following request successfully returned the document: **`/opinion_index/_doc/o_9918845?routing=9918845`**.
In ES, the **`routing`** field defaults to the document **`_id`**, as described in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html)
For indexing child documents, it is necessary to set the routing parameter to the parent document's **`_id`** so that parent and child documents are indexed in the same shard.
In …

3602 Include the routing parameter in ES "get" and "exists" requests for child documents

---

cl/search/tasks.py

This should fix #3626. The `BulkIndexError` is not very descriptive, but the format of the bulk documents hasn't changed and is correct. I believe what is happening now is that the check to confirm if the opinions to be updated exist is working properly. Therefore, the process reaches the Bulk update requests, but the bulk operation fails since some of the documents intended for update are not found in the shard. This is similar to what happened with the `exists` requests.
So, adding the [_routing](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-routing) parameter to each document that needs to be updated should solve the issue.

3626 Fix BulkIndexError by including the routing param on items to be updated

---

cl/scrapers/management/commands/cl_scrape_opinions.py
cl/scrapers/tasks.py
cl/scrapers/utils.py
cl/settings/third_party/sentry.py

Uses Sentry's fingerprinting of events to force a grouping. 
For scraping and parsing errors, the desired grouping is by the data's source scraper, which can be identified by the juriscraper module. If the module is not available, by the court id
Solves #3399

feat(sentry): Group Sentry issues by scraper

---

cl/search/es_indices.py

After merging this PR that switch the `recap` index to new `recap_vectors` ,ES signals for RECAP will start indexing and updating documents to the new index. 
Once this is merged we should also start the indexing command from the latest docket PK:
```
courtlistener=> select id from search_docket order by id desc limit 1;
id    
----------
68155306
```
Accordingly to the output you got when started the `re_index` task, should be something like:
`manage.py cl_index_parent_and_child_docs --queue celery --search-type r --pk-offset  68155306 --chunk-size 20 `
Tweaking the queue and chunk-size accordingly.
However the command above will only index new Dockets and their RECAPDocuments.
So, we'll need to tweak the indexing command to enable indexing of `RECAPDocuments` from a starting PK. This …

Switched ES RECAP index name

---

cl/assets/static-global/css/override.css
cl/lib/search_utils.py
cl/opinion_page/utils.py
cl/search/tests/tests_es_opinion.py
cl/search/views.py

This PR addresses the issues described in #3604
Some comments: 
> The bell icon is kind of a mess. This isn't part of Elastic, but we should spend a few minutes to fix it.
I was not able to reproduce this issue. I tested it in different browsers, and the bell icon is showing properly. I also asked Eduardo, and he confirmed that it's displaying properly. Do you still see this issue in your browser?
>  For some reason, it's doing "Citation" searches (see the header above, "6,960,345 Opinions cite", and the "0 References to this case").
Fixed. The issue was that the `add_depth_counts` method was not being properly called because it is now an asynchronous method.
> When you do [a citation query](https://www.courtlistener.com/?q=cites%3A(220342%20OR%209441923%20OR%209441924%20OR%209441925)) …

Fixed multiple Opinions search issues on the frontend

---

cl/assets/templates/base.html
cl/search/management/commands/cl_index_parent_and_child_docs.py
cl/search/tasks.py
cl/search/tests/tests_es_recap.py
cl/settings/third_party/elasticsearch.py

This PR enables the **`cl_index_parent_and_child_docs`** command to index either only parent or only child documents in ES.
It is now possible to index only Dockets without indexing their RECAPDocuments, or to index only RECAPDocuments without re-indexing their parent Docket (If it's already indexed). This is useful for targeted indexing, such as indexing new `RECAPDocuments` that belong to an old docket.
A new argument has been introduced: **`--document-type`**, with valid options "parent" or "child". If not provided, the command will re-index the parent and all its documents.
Example:
**`manage.py cl_index_parent_and_child_docs --queue celery --search-type r --pk-offset 383081261 --document-type "child" --chunk-size 100`**
In this example, the command will start indexing all …

Tweak cl_index_parent_and_child_docs command to index only parent or child documents

---

cl/recap/mergers.py

Pass pacer_doc_id via params to prevent duplicate kwargs

---

cl/lib/elasticsearch_utils.py
cl/search/tests/tests_es_recap.py

This PR fixes #3636. The issue impacted queries that involved filtering parties (**`party_name`** and **`atty_name`**).
Essentially, if you performed a search query that included parties and any other filter (parent or child) or search query, the results would include cases that matched the party filters `**OR**` the cases with filings that matched the other filters and query string. 
The correct behavior should be that the party filters constrain the results like the other filters and string query.
e.g:
https://www.courtlistener.com/?type=r&q=&type=r&order_by=score%20desc&party_name=Bank%20of%20america&court=ca1%20ca2%20ca3%20ca4%20ca5%20ca6%20ca7%20ca8%20ca9%20ca10%20ca11%20cadc%20cafc
https://www.courtlistener.com/?q=&type=r&order_by=dateFiled%20desc&filed_after=01%2F01%2F2020&atty_name …

Fix queries related to RECAP parties filters.

---

cl/lib/elasticsearch_utils.py
cl/search/api_utils.py
cl/search/forms.py
cl/search/tasks.py
cl/search/tests/tests_es_oral_arguments.py
cl/search/tests/tests_es_parenthetical.py
cl/search/tests/tests_es_person.py
cl/search/tests/tests_es_recap.py
cl/search/views.py

In order to optimize the performance of Search requests, the count queries and the main query in a search request are now executed in a single request.
In ES, it is necessary to perform an additional count query alongside the main query to retrieve the total number of results. This is because the main query only provides a count up to 10,000 for performance optimization.
In RECAP Search, an additional query is required to retrieve the count of docket entries. In general, we have for each Search request:
**Other documents:**
- Main query
- Documents count query
**RECAP Search:**
- Main query
- Cases count query
- Docket entries count query
To reduce the number of requests and improve Search performance, all two or three queries are now performed in a single request using the Multi-Search …

Utilize Multi-Search to perform simultaneous queries in a single request.

---

cl/donate/management/commands/charge_monthly_donors.py
cl/donate/utils.py

This PR fixes #3655 by restoring the email template used in the `charge_monthly_donors` command.

fix(donate): Brings back the email template for the "charge" command

---

cl/lib/elasticsearch_utils.py

Most of the errors in #3652 relate to queries with incorrect syntax.
I described in #3171 the cases that seem different.
The problem was that previously, when using the Search API, it returned these kinds of errors as a `RequestError`, which we caught and logged as a warning.
The Multi-search API now raises an `APIError` instead with the message `Failed to parse query ...` 
To stop raising these errors on bad query syntax and to display this screen to users instead:
Now it catch the `APIError` and only log a warning if the message error is `Failed to parse query ...`.
- Additionally I believe there could be other types of `APIError` not related to query parsing because some of the errors logged in Sentry appear to have valid queries. However, the error message in Sentry just shows: …

3652 Catch APIError on multi-search requests due to bad query syntax

---

cl/lib/elasticsearch_utils.py
cl/search/constants.py
cl/search/tests/tests_es_opinion.py
cl/search/tests/tests_es_recap.py

The error in #3658 was due to incorrect escaping of strings like `Steven !\li.;` since is already escaped during indexing. I've applied a fix in `replace_highlight` -> `f"<{tag}>{word}</{tag}>"` to remove escaping at merging time.
Now that we have `term_vectors` enabled for fields that require highlighting in RECAP and Opinions, it is possible to enable the setting [matched_fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html#highlighting-settings). This parameter combines matched HL terms from different versions of the same field (normal and exact) into a single field, eliminating the need for performing the merging process afterward.
I performed a benchmark to confirm that this new parameter does not increase search time, as the merging process is …

Introduced a matched_fields parameter for combining highlights in FVH fields

---

cl/scrapers/management/commands/cl_scrape_oral_arguments.py

Update parameter to site
Failing to update the identical get binary call for OA caused a bug

fix(oa): Fix cl_scrape_oral_arguments

---

cl/donate/factories.py
cl/donate/tests.py
cl/donate/utils.py

This commit updates the `user_bad_subscription` email template to provide more informative messaging and encourage users to become members. It also adds tests to prevent regressions.
Fixes #3677.

fix(donate): Tweaks email notification for failed monthly charges

---

cl/donate/api_permissions.py

This PR addresses a `keyError` exception that occurred in the `has_permission` method when the request payload is empty. The fix includes a check to ensure that the payload is not empty before accessing it.

fix(donate): Tweaks the AllowNeonWebhook class to handle empty payloads

---

cl/favorites/api_views.py

This PR fixes #3681 by updating the permission class in the `UserTag` Viewset. This new permission class would allow full access to authenticated users, but allow read-only access to unauthenticated users.

fix(tags): Tweaks permission class of the UserTag Viewset

---

poetry.lock
pyproject.toml

My [fix](https://github.com/django/asgiref/commit/0503c2c4df06dbe56f04689fe537325f28dbbe8b) for a [task cancellation bug](https://github.com/django/asgiref/issues/434) I was seeing in asgiref under some circumstances was recently merged so lets update to that commit(currently latest asgiref commit). We are already using a git commit pin due to encountering another [asgiref bug](https://github.com/freelawproject/courtlistener/pull/3357) that has yet to make it into an asgiref release. I suspect this bug is preventing #3596 from working as expected.

Update asgiref to latest commit to fix task cancellation bug

---

poetry.lock
pyproject.toml

Reverts freelawproject/courtlistener#3678
This is causing a number of errors in Sentry, and @ttys0dev seems to be busy. Reverting.

Revert "Update asgiref to latest commit to fix task cancellation bug"

---

cl/people_db/views.py

This PR fixes #3690 by using the select_related method to fetch related aliases in a single query.

fix(people): Adds the select_related method to fetch related aliases

---

cl/donate/api_views.py
cl/donate/tests.py

This PR updates the `create` method of the `MembershipWebhookViewSet` to ensure that the webhook payload is stored even when errors occur during subsequent processing. Additionally, tweaks the `_get_address_from_neon_response` helper method to extract zip codes properly and adds tests to prevent regressions.

fix(donate): Tweaks the Webhook ViewSet to store payload before processing it

---

cl/simple_pages/templates/includes/available_fields.json
cl/simple_pages/templates/includes/available_fields_tabs.html

I've added a note about filtering and searching for party and attorney to the search documentation:
Following your suggestion, I've included some examples to explain how to include empty filings in search results when using a party and/or attorney field.
Fixes: #3685

3685 Updated advanced search docs for explaining parties search and filtering

---

cl/alerts/tests.py

- The test started failing because it forces a date to the 30th day, and for February, this is an invalid date. 
- Fixed it by also forcing the month to always be January.

Fixed failing test_send_alert_multiple_alert_rates due to a bad date.

---

.github/workflows/tests.yml

With #3134, the celery and django containers began to use the same image, making the celery-specific job unproductive.

chore(build): drop redundant docker image build step

---

.github/workflows/docker-build.yml

Simultaneous deploys would be bad! Give the `deploy` job the concurrency group, `"production"`.

chore(deploy): restrict concurrency of deploy workflow

---

cl/settings/third_party/sentry.py

Sentry’s integration for `asyncio` promises that it will capture all unhandled exceptions in tasks and every `Task` is instrumented for performance analysis.
Fixes: #3129

feat(sentry): add `AsyncioIntegration` integration `sentry_sdk`

---

cl/corpus_importer/tests.py
cl/recap/tests.py

- Some test methods were inadvertently clearing the global Redis cache, including sessions, which led to occasional failures of requests requiring authentication when tests were run in parallel.
This adjustment should help with the random failures in:
**`cl.recap.tests.WebhooksRetries`**
**`cl.recap.tests.RecapEmailDocketAlerts`**
- Additionally, another test method was clearing the "STATS" database, which could be the cause of random failures in:
**`cl.users.tests.CustomBackendEmailTest`**
This was addressed by only clearing the specific keys related to each test.
- Clean up of `afirst()` calls in tests.

Fix failing tests by avoiding global deletion of sessions

---

cl/lib/email_backends.py
cl/tests/cases.py
cl/users/tests.py

This PR fixes #3686. 
I abstracted out how we create a Redis key for the email counter so that tests could mock it. This was necessary to allow tests to run in parallel. One of our tests couldn't get an accurate count for the `temp_counter` because other tests that send emails are simultaneously adding elements to this Redis key.
This PR allows it to have its namespace in Redis by tweaking the key the logger uses during the test.

3686 fix failing test related to Redis email counter

---

cl/alerts/templates/docket_alert_email.html
cl/alerts/templates/docket_alert_email.txt

This commit repositions the notes section in the `docket_alert_email` template files, placing it after the list of filings. This change enhances the scannability of our alert emails within mail clients. 
Fixes #3112

refactor(alerts): Reorganize sections in the docket alert email template

---

cl/search/tasks.py

Yeah, the events in #3739 are related to operations that shouldn't take too much time, like getting a document from the index. Therefore, it seems correct to just retry these `ConnectionTimeout` errors since they might be caused by a network issue.
I also added `ConnectionTimeout` on retries to other tasks that shouldn't take longer since they only update one document at a time.
There are some tasks like `update_children_docs_by_query` that have triggered `ConnectionTimeout` errors too,  like the ones described in https://github.com/freelawproject/courtlistener/issues/3541. Before adding retries to that task, I'll check the related documents in events. It's likely that we would need to increase the client timeout since some of those cases have a large number of fillings.
Additionally, the …

Retry ES indexing tasks on ConnectionTimeout

---

cl/recap/tasks.py

This PR updates the `process_recap_email` task to implement exponential backoff.
This backoff delay starts at 2 minutes and doubles between attempts, resulting in the following sequence: 2min, 4min, 8min, 16min, 32min, 1h, 1h, 1h, 1h, 1h. The maximum delay is 1 hour.
This new setting allows the system to automatically retry a failed task for up to 5 hours.

feat(recap): Update the retry strategy for the process_recap_email task

---

cl/users/tests.py
cl/users/views.py

This PR implements a check for the Neon account ID within the user profile before triggering the update process. If the ID is missing, the create process is initiated instead. This ensures data consistency and prevents potential errors.
This PR fixes #3755

fix(users): Adds a check for the Neon account ID before firing tasks

---

cl/search/apps.py

This PR addresses  #3306 by automatically creating the required Elasticsearch indices for development with the correct mappings.
The approach differs from the initial proposal of running the create indices command upon container initialization. I evaluated adding the create indices commands under `web-dev` in `docker-entrypoint.sh`, however, it doesn't seem convenient. To be successful, two conditions must be met: the ES cluster must be available, and the create index command should be avoided if the index already exists.Checking the Elasticsearch cluster's availability and checking for the existence of an index from here would be complex. Additonally, this method lacks flexibility in case an index name changes, requiring  adjustments to the commands.
A better option and the one …

3306 Create ES indices upon search app initialization 

---

cl/recap/tests.py
cl/search/tasks.py

I checked the related events in #3778, the related cases don't have many entries. Therefore, I believe what might have happened is that the shard handling the request failed (and the replica was not available), or the cluster was generally busy. Given that the timeout is now quite large, the request just continued beyond the default [search context duration](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html#_waiting_for_active_shards_2), which is 5 minutes. I could confirm that the latest sentry event request started at `16:16:47`, and the exception was triggered at `16:23:23`, indicating that the **`NotFoundError`** due to the missing context was triggered after it expired.
We could set **`wait_for_active_shards`** to 2, so the UBQ request waits …

3778 Include NotFoundError exception in the UBQ request's retry policy

---

cl/search/migrations/0026_drop_docket_unique_together_and_more.py

I have been updating some branches that are pending, merging them with the main branch, in some of these there are migrations that I apply to verify them. After this it is sometimes necessary to remove those migrations before changing branches to avoid any errors.
But I found a problem with the migration "0026_drop_docket_unique_together_and_more.py" from search app, it uses RunSQL operations but these are not reversible, so if you run this `python manage.py migrate search 0025` you will get this errors:
```
django.db.migrations.exceptions.IrreversibleError: Operation <RunSQL  sql='DROP INDEX CONCURRENTLY IF EXISTS "search_docket_docket_number_4af29e98dca38326_uniq";', state_operations=[<AlterField  model_name='docket', name='docket_number', field=<django.db.models.fields.TextField>>]> in …
```

Make RunSQL operation reversible in migration

---

cl/search/tasks.py

This PR fixes #3818:
`ConflictErrors` from the `index_related_cites_fields` task, when doing a `bulk` request, are not raised directly. It's required to parse the `BulkIndexError` `errors` property.
In this case, if the error type is `version_conflict_engine_exception`, it will raise a `ConflictError` so the task can be retried.

Raise a ConflictError on cites BulkIndexError conflicts for retrying the task

---

cl/corpus_importer/tasks.py

This PR updates the `is_docket_entry_sealed` method to gracefully handle situations where the doc_id argument is None.
Fixes #3836

feat(corpus importer): Update method to check sealed entries

---

cl/search/forms.py
cl/simple_pages/templates/help/advanced_search.html
cl/simple_pages/templates/includes/available_fields.html
cl/simple_pages/templates/includes/available_fields.json
cl/simple_pages/templates/includes/available_fields_tabs.html

According to #3843:
I've added a waffle flag to use the updated values for **`status`** once **`o-es-active`** is enabled for all users. Meanwhile, the Solr version displays the correct values and the appropriate field. In Solr, two related fields, **`status`** and **`status_exact`**, exist. I did a fielded search using **`status`**, but it failed on **`Non-Precedential`** due to the analyzer used in the field in Solr. Therefore, the field that should be used is **`status_exact`**, which is also utilized in the filter, then **`status_exact`** is the field that added to the Solr version documentation.
When updating the documentation for ES, we included the following new fields: **`attorney`**, **`panel_names`**, **`type`**, **`procedural_history`**, **`posture`**, **`syllabus`**, …

3843 Clean up Advanced Search help page

---

scripts/make_bulk_data.sh

This PR introduces a new command to verify that the `sudo` package is installed before proceeding with any other commands within the bulk generation script. This PR fixes #3839.
I tested the updated script in my dev environment and was able to generate this script: [load-bulk-data-2024-03-01.sh](https://s3.console.aws.amazon.com/s3/object/com-courtlistener-storage?region=us-west-2&bucketType=general&prefix=bulk-data/load-bulk-data-2024-03-01.sh) and a bunch of .bz2 files.

fix(bulk data): Add command to make sure the sudo pkg is installed

---

cl/search/templates/includes/no_results.html
cl/search/views.py

This PR tweaks the `no_results.html` template to avoid adding an empty `type` to the query string of the suggested URL and fixes #3834.

feat(search): Update template to avoid adding empty type

---

cl/disclosures/factories.py
cl/disclosures/filters.py
cl/disclosures/tests.py

This PR adds better filtering mechanisms for the remainder of the disclosure API endpoints.
Previously you could really only do stuff on 
Agreements, and Investments.  
Now we should be able to filter gifts and debts, positions and agreements and more.  
Some tests and factories were added to prove things are working nicely

Update disclousre apis

---

cl/audio/tests.py
cl/audio/urls.py
cl/lib/elasticsearch_utils.py
cl/search/feeds.py
cl/search/tests/tests_es_opinion.py
cl/search/tests/tests_es_recap.py
cl/search/urls.py
cl/tests/cases.py

This PR fixes #3743
- It catches ES errors, including syntax errors (`UnbalancedParenthesesQuery`, `UnbalancedQuotesQuery`, `BadProximityQuery`) logs a warning and display an empty feed or podcast.
- Added related tests for RECAP, Opinions Search and Audio Podcast.
- Refactored feed content assertions to remove duplicated code.

3743 Catch ES errors during feed rendering.

---

cl/citations/utils.py
cl/opinion_page/templates/citation_redirect_info_page.html
cl/opinion_page/tests.py
cl/opinion_page/views.py
cl/search/selectors.py

This pull request addresses several refactoring improvements and bug fixes within the citation views. Here's a summary of the key changes:
- Cleans up some unused code in the `citation_redirector` view. This PR removes an extra reverse call that is not being used anywhere.
- During the asynchronous migration of the `attempt_reporter_variation` view, we missed that one of the potential responses was using the `render` method, which is incompatible with asynchronous operations. This PR addresses this issue by replacing the `render` method with the `TemplateResponse` constructor, ensuring proper functionality within the asynchronous context.
- Similar to the previous point, during the migration of the `reporter_or_volume_handler` view, we missed that tthe code responsible for handling …

feat(citations): Refactor code related to citations

---

cl/lib/es_signal_processor.py
cl/lib/test_helpers.py
cl/search/models.py
cl/search/signals.py
cl/search/tasks.py
cl/search/tests/tests_es_opinion.py
cl/search/tests/tests_es_oral_arguments.py
cl/search/tests/tests_es_recap.py

According to #3875, this PR prevents indexing signals from indexing non-RECAP Dockets into ES.
**It considers the following:**
- New dockets, whose sources do not include RECAP, are not indexed into ES.
- Dockets that are updated and whose source does not include RECAP, are not indexed into ES.
- If a non-RECAP Docket's `source` is updated to include a RECAP source (e.g: receives an upload from RECAP), the docket is indexed into ES.
- It avoids calling unnecessary celery tasks for non-RECAP dockets since the condition is checked before calling a celery task.
- The `"source"` field is tracked but is not indexed into RECAP documents in ES.
- This condition does not apply to other indices, where non-RECAP dockets are still tracked to spread their changes to the main ES documents, like in …

3875 Avoid indexing non-RECAP Dockets into ES.

---

cl/search/management/commands/cl_index_parent_and_child_docs.py
cl/search/management/commands/cl_remove_non_recap_dockets_from_es.py
cl/search/tasks.py
cl/search/tests/tests.py
cl/search/tests/tests_es_recap.py

According to #3702 this PRs adds the cl_remove_non_recap_dockets_from_es command that queries non-RECAP dockets IDs from the DB and removes them from ES using the `DeleteByQuery` request.
Initially, my approach was to use bulk delete. However, after testing, I realized this could lead to `NotFoundError` because some of the non-RECAP dockets might not have been indexed. Therefore, it's better to use `DeleteByQuery`, so only indexed documents are removed.
The command can be executed as follows:
`manage.py cl_remove_non_recap_dockets_from_es  --chunk-size 50 --queue-size 20  --queue celery `
There is also a `--auto-resume` option that can be used in case the command crashes or it's stoped, allowing it to be restarted from where it left off.
- I also updated the …

3702 Introduced cl_remove_non_recap_dockets_from_es to remove non-recap dockets from ES.

---

cl/search/models.py

Since we don't know what is causing the error we can temporary solve it while we investigate
Catch the IntegrityError on Docket.save(), put the now() timestamp into the Docket instance date_modified field, and retry the insertion
patches: #3359

fix(search.Docket.save): temporary solution for auto_now bug

---

cl/search/tasks.py

According to #3892, it seems that the search context is being missed when removing non-recap dockets by query. This means the query is taking more than 5 minutes, which exceeds the default duration of a search context.
It would be worthwhile to monitor the cluster resources. It might be necessary to reduce the command `--chunk-size` to avoid overloading the cluster.
I've added NotFoundError to `remove_documents_by_query` so it can be retried in case the search context is missed.

3892 Retry remove_documents_by_query task on NotFoundError

---

cl/alerts/management/commands/clean_up_search_alerts.py
cl/alerts/tests.py

Introduces the command described in #3632 to clean up Opinion Search alerts to make them compatible with the changes performed on the Opinions ES index.
The fields that changed were:
`caseNameShort`: Removed
`type`: Values changed
`text`: Value changed
`status`: Values changed
`status_exact`: Removed
We confirmed that only two alerts (597 and 943) contain one of those fields within the query as a fielded search. Therefore, we can fix those alerts by hand.
The command thus focuses on the `stat_` filter, which is present in all Opinion Search alerts queries.
The replacements performed on the queries are as follows:
```
"stat_Precedential" - > "stat_Published"
"stat_Non-Precedential"  - > "stat_Unpublished"
"stat_Separate%20Opinion" - > "stat_Separate"
"stat_Relating-to%20orders" - > …
```

3632 Introduced clean_up_search_alerts command

---

cl/search/management/commands/cl_remove_content_from_es.py
cl/search/tasks.py
cl/search/tests/tests.py
cl/search/tests/tests_es_recap.py

This PR renamed the `cl_remove_non_recap_dockets_from_es` command to `cl_remove_content_from_es`, enabling it to handle the removal of Opinion documents based on their timestamp. This change aims to eliminate duplicate Opinions from #3897.
The command can be executed as follows:
`manage.py cl_remove_content_from_es --action opinions-removal --start-date 2024-03-15 --end-date 2024-03-18`
It will remove all `OpinionDocuments` indexed within the specified date range, utilizing the timestamp field that is populated during document indexing. I confirmed in tests that the timestamp is not altered during partial updates.
Then the command will remove `OpinionDocuments` that were re-indexed by the sweep indexer in recent days.
Afterward, we can re-index missing Opinions using the `sweep_indexer` …

3897 Remove Opinions based on their timestamp

---

cl/alerts/tests.py
cl/alerts/views.py
cl/api/tests.py
cl/api/views.py
cl/corpus_importer/tasks.py
cl/donate/tests.py
cl/favorites/tests.py
cl/lib/tests.py
cl/opinion_page/tests.py
cl/opinion_page/views.py
cl/recap/management/commands/monitor_pacer_websites.py
cl/recap/tasks.py
cl/recap/tests.py
cl/search/api_views.py
cl/search/tests/tests.py
cl/search/tests/tests_es_opinion.py
cl/search/tests/tests_es_recap.py
cl/simple_pages/tests.py
cl/simple_pages/views.py
cl/users/api_views.py
cl/users/tests.py
cl/visualizations/api_views.py
cl/visualizations/tests.py
cl/visualizations/views.py

This PR updates views, tests, and custom commands throughout the project to consistently use the  [HTTPStatus class](https://docs.python.org/3/library/http.html#http.HTTPStatus) from the standard [http python module](https://docs.python.org/3/library/http.html#module-http). Previously, these components relied on importing status codes from the `status` module included with [Django REST framework](https://www.django-rest-framework.org/api-guide/status-codes/).

Use the Http library to handle HTTP status 

---

cl/search/management/commands/cl_remove_content_from_es.py
cl/search/tasks.py

According to #3897, we need to throttle the removal of opinions to avoid impacting cluster stability.
The added throttling works by passing the **`requests_per_second`** parameter, which functions as follows: 
It considers the batch size, which defaults to 1000 documents per batch.
The parameter is set by `--requests-per-second`, which defaults to 8.
`1000 / 8 requests per second = 125 seconds.`
So, it will take around 125 seconds to remove 1000 documents.
Since we are targeting the removal of around 5,000,000 documents, which equals 5000 batches, it will take a total of 625,000 seconds to complete the removal, which is around 7 days.
I believe this throttling is more than safe, since we removed around 10M non-recap dockets in a few hours, which was a process throttled by celery tasks. …

3897 Added throttling to the delete-by-query request for removing opinions.

---

poetry.lock
pyproject.toml

We no longer need a custom git commit for this since the latest version now has my fixes.
Changelog: https://github.com/django/asgiref/blob/main/CHANGELOG.txt

Update asgiref to version 3.8.1

---

cl/search/management/commands/sweep_indexer.py

This PR simplifies the count query for `RECAPDocument` and `Opinion` in the sweep_indexer. Hopefully, with this change, the count query won't timeout anymore.
Fixes: #3919

fix(elasticsearch): Fixed sweep_indexer count queries.

---

cl/api/urls.py
cl/citations/api_serializers.py
cl/citations/api_views.py
cl/citations/exceptions.py
cl/citations/tests.py
cl/citations/types.py
cl/citations/utils.py
cl/opinion_page/views.py

This PR introduces a new API endpoint for citation lookup. It allows searching by string or using a `volume-reporter-page` format. Additionally, it closes #3337.
Here's a summary of the key changes:
- Introduces a new endpoint to look up citations. Users will be able to access it via a GET request to `/api/rest/v3/citation-lookup/`. To use this endpoint, The user must include the citation data in the request's querystring. Here are the supported fields:
- `text_citation`: Textual representation of the citation. 
- `reporter`: reporter name.
- `volume`: Volume number.
- `citation_page`: Specific page number within the volume.
- The pagination of this new endpoint is handled by the MediumAdjustablePagination class.
- The PR adds a new serializer to validate request parameters for citation …

feat(citations): Adds an API endpoint to look up citations

---

cl/citations/api_views.py

This PR fixes [COURTLISTENER-6ZE](https://freelawproject.sentry.io/issues/5108158611/) by adding a `serializer_class` attribute to the `CitationLookupViewSet` class

Fix(citations): Adds serializer_class to the CitationLookupViewSet

---

cl/lib/elasticsearch_utils.py
cl/search/tasks.py
cl/search/views.py

The check performed by `es_index_exists` is no longer required in production because we have already created all the required indices. In development, we have a signal that creates the required indices upon app initialization, and in tests, index creation is handled automatically as needed.
Therefore, this check can be removed to save one request to ES.
Fixes: #3913

3913 Removed es_index_exists check

---

cl/citations/api_views.py
cl/citations/utils.py
cl/opinion_page/forms.py
cl/opinion_page/templates/citation_redirect_info_page.html
cl/opinion_page/templates/volumes_for_reporter.html
cl/opinion_page/tests.py
cl/opinion_page/views.py

This PR fixes #2747. Here are the key changes of this PR:
- Updates the `CitationRedirectorForm` class to handle two distinct input scenarios identified from [COURTLISTENER-4SW](https://freelawproject.sentry.io/issues/4439604480/?project=5257254) events. The first scenario involves input strings containing forward slashes (/), like in this event: [event-fe6daae9196b4eb68d5e38e8d8d9d821](https://freelawproject.sentry.io/issues/4439604480/events/fe6daae9196b4eb68d5e38e8d8d9d821/?project=5257254), while the second involves input strings containing URLs like the following event: [event-e6fbf3df9f1946ea8cb5998278d0e510](https://freelawproject.sentry.io/issues/4439604480/events/e6fbf3df9f1946ea8cb5998278d0e510/?project=5257254).
- During development of a previous change, I identified an issue …

feat(citations): Handle Errors on the web citation tool

---

cl/citations/api_views.py
cl/citations/tests.py

This PR addresses one of the issues from https://github.com/freelawproject/courtlistener/issues/3924. It implements logic to skip citations lacking volume information. Additionally, it introduces a dedicated test to prevent future regressions.

feat(citations): Adds logic to filter out citations with no volume

---

cl/lib/pacer.py
cl/recap/mergers.py
cl/recap/tests.py
cl/scrapers/factories.py

This PR fixes: #3878
The solution implemented prevents the Docket's `nature_of_suit` from being modified by different source values, thereby avoiding unnecessary triggering of indexing signals. This is done by not updating the value if it is already set in the database.
The solution is applied to the `update_docket_metadata` method and to the `free opinions scraper`, which employs a different method for merging metadata into the database.
After this and https://github.com/freelawproject/juriscraper/pull/978 are merged, `ConflictErrors` events on Sentry should significantly decrease.

3878 Avoid updating the nature_of_suit if the docket already has nature_of_suit set

---

cl/citations/api_serializers.py
cl/citations/api_views.py
cl/citations/tests.py

This PR restricts access to the `CitationLookupViewset` to logged-in users by implementing the `IsAuthenticated` permission class. Additionally, it streamlines the `api_views.py` file by removing unnecessary imports and refines the `CitationAPIResponseSerializer` serializer to consistently include `error_message` keys in API responses.
I will implement throttling for this endpoint in a separate PR.

feat(citations): Updates the CitationLookup class

---

cl/scrapers/tests.py
cl/scrapers/utils.py

Helps fix #3937
- convert site.expected_content_types to lower()
- remove ";charset=utf-8" or similar specifications from returned content type
- add a test for "charset" content type

fix(scrapers.utils): improve expected content type check

---

cl/search/templates/includes/alert_modal.html
cl/search/templates/includes/no_results.html
cl/simple_pages/sitemap.py
cl/simple_pages/templates/faq.html
cl/simple_pages/templates/feeds.html
cl/simple_pages/templates/help/alert_help.html
cl/simple_pages/templates/help/coverage.html
cl/simple_pages/templates/help/coverage_opinions.html
cl/simple_pages/templates/help/coverage_recap.html
cl/simple_pages/templates/help/index.html
cl/simple_pages/urls.py
cl/simple_pages/views.py

This fixes #3962 by splitting the PACER coverage page into its own page that lives at `/help/coverage/recap/`.
It's a LOT better. Should have done this a long time ago.
I also tweaked other links to point to the new page where appropriate, and tweaked some other language where I thought it could be better.

Split off pacer coverage page

---

cl/search/management/commands/cl_compute_token_count.py

This commit updates the `get_recap_random_dataset` method to exclude documents with `page_count` equals to 0 from the random dataset.

fix(search): Updates query in the get_recap_random_dataset method

---

docker/django/Dockerfile

This PR addresses the issue reported in https://github.com/freelawproject/courtlistener/pull/3976#issuecomment-2059452959 by updating the Dockerfile to create a separate directory for the Hyperscan database.

build(dockerfile): Adds a directory for Hyperscan db

---

.gitignore

This PR updates the `.gitignore` file to exclude the hyperscan folder from version control.

fix(git): Ignore the hyperscan directory

---

cl/api/templates/citation-lookup-api.html
cl/search/templates/advanced.html
cl/search/templates/includes/alert_modal.html
cl/simple_pages/templates/faq.html
cl/simple_pages/templates/help/alert_help.html
cl/simple_pages/templates/help/coverage.html
cl/simple_pages/templates/help/coverage_fds.html
cl/simple_pages/templates/help/coverage_oa.html
cl/simple_pages/templates/help/coverage_opinions.html
cl/simple_pages/templates/help/coverage_recap.html
cl/simple_pages/templates/help/index.html
cl/simple_pages/tests.py
cl/simple_pages/urls.py
cl/simple_pages/views.py

This makes it more consistent with our other coverage pages and fixes: #3984. 
Also:
- Makes the footer beg more consistent.
- Makes the headings more SEO friendly.
- Some minor grammar/language tweaks

Split off covreage page for oral argument audio

---

cl/citations/api_views.py
cl/citations/tests.py

This PR integrates `validate_request_data` logic within the create method to use the CitationAPIRequestSerializer to ensure proper serialization of the request body for citation lookups. Additionally, a test is added to prevent regressions.
This PR fixes #3988.

fix(citations): Implements CitationAPIRequestSerializer in the CitationLookupView

---

cl/api/templates/bulk-data.html
cl/api/templates/financial-disclosure-docs-vlatest.html
cl/api/templates/includes/toc_sidebar.html
cl/api/templates/rest-docs-vlatest.html
cl/api/urls.py
cl/api/views.py
cl/simple_pages/sitemap.py
cl/simple_pages/templates/help/index.html
cl/simple_pages/tests.py

This PR adds a new page to the documentation for the financial disclosure APIs. As always, this is harder than it seems, but the result is worth it. 
This fixes #4004, and:
- Adds a test to ensure the page works, and adds a missing one for the citation lookup page too.
- Updates old links that went to the root API docs to point to this page if applicable.
- Adds this page and the citation lookup API to the sitemap.xml
- Adds this page to `/help/` and updates it a bit.
I haven't tried the tests locally, but if they pass here, I think we can merge, so I plan to set this for automerge.

Split the financial disclosure docs into their own page

---

cl/api/templates/alert-api-docs-vlatest.html
cl/api/templates/bulk-data.html
cl/api/templates/includes/toc_sidebar.html
cl/api/templates/rest-docs-vlatest.html
cl/api/templates/search-api-docs-vlatest.html
cl/api/templates/webhooks-docs-vlatest.html
cl/api/urls.py
cl/api/views.py
cl/simple_pages/sitemap.py
cl/simple_pages/templates/help/alert_help.html
cl/simple_pages/templates/help/index.html
cl/simple_pages/tests.py

This one wound up being pretty big, but our documentation needed it:
1. Cleans up and overhauls the alert help page for users.
2. Creates a new page for the Alert API and links to it (including sitemap, tests, help page, etc).
3. Creates a new page for the Search API and links to it etc.
Fixes: #4011

Split off Alert and Search API documentation

---

cl/people_db/api_serializers.py

This is a very small PR to add a couple more IDs to objects that lack them. I find it pretty annoying when these are missing, so hopefully this will help me and others in the future.

Add object IDs to the party/atty endpoints

---

cl/opinion_page/templates/citation_redirect_info_page.html
cl/opinion_page/tests.py
cl/search/selectors.py

This PR fixes #4013 by tweaking the `get_clusters_from_citation_str` method and updating the `citation_redirect_info_page.html` template. 
I identified the reason why the court name wasn't showing in the template. The prefetch_related approach stores cached data in a separate attribute on the parent model instance. In this case, the parent was the Docket model, not the Cluster. As a result, the court_data attribute wasn't available within the Cluster instances. To access the court data, we'd need to use: 
```python
cluster.docket.court_data
```
However, for a simple one-to-one relationship like the one between `Docket` and `Court`, this approach feels clunky. Since the court query is straightforward, using `select_related` would be more efficient.
This PR also updates the tests related to …

fix(citations): Display court name on multiple results page

---

cl/search/tasks.py
cl/search/tests/tests.py
cl/search/tests/tests_es_opinion.py
cl/search/tests/tests_es_recap.py

To optimize the sweep indexer, this PR removes the HEAD requests previously used to ensure that parent documents were already indexed before adding the child documents.
In cases where a few parents are missed due to failed signals, they will be indexed in the next sweep indexer cycle, and their related RDs will become searchable.

Removed parent document existency check when indexing child documents using index_parent_or_child_docs

---

cl/alerts/tests.py
cl/api/views.py
cl/lib/elasticsearch_utils.py
cl/tests/base.py

This PR solves the Selenium timeout error we've seen across different PRs while implementing ES alert estimation count for Opinion Alerts.
To debug the error, I tweaked the screenshot filenames stored by Selenium because the current implementation used the class name, so only one screen was being stored per class. Now, the filename also includes the test name, allowing one screenshot per test to be stored when the `teardown` method is called.
The issue I found was that the Create Alert Modal was not rendering the form.
Checking the code, I found that the form is rendered only after the `alert_frequency` estimation query returns a response. However, this query was still running on Solr in the test while the `BaseSeleniumTest` already relies on ES.
Therefore, I migrated the …

Implemented an ES alert estimation count for Opinion Alerts

---

cl/lib/elasticsearch_utils.py
cl/lib/tests.py
cl/lib/utils.py
cl/search/exception.py
cl/search/tests/tests.py

- As described in #4044, this PR ensures that the **`UnbalancedParenthesesQuery`**, **`UnbalancedQuotesQuery`**, and **`BadProximityQuery`** exceptions are properly caught in the V4 Search API, and the corresponding **`APIException`** error is raised.
The error **`detail`** is the same as for the original exception:
- **UnbalancedParenthesesQuery**: The query contains unbalanced parentheses.
- **UnbalancedQuotesQuery**: The query contains unbalanced quotes.
- **BadProximityQuery**: The query contains an unrecognized proximity token.
The error status is: `400` (BAD_REQUEST).
- Reviewing the related events on Sentry, I noticed that queries like this were raising **`BadProximityQuery`**:
`suitNature:"Securities"~1 AND caseName:"jpmorgan research equity long/short sel"~0.9`
However, in this …

4044 Properly catch custom ES syntax errors in the V4 Search API

---

cl/lib/document_serializer.py
cl/lib/test_helpers.py
cl/search/api_serializers.py
cl/search/api_views.py
cl/search/tests/tests_es_recap.py

According to #4032 I've applied the following changes in this PR:
- Removed `court_exact` from the response object in all search RECAP search types.
- Added a new `meta` key into all the RECAP search types that contain:
- r type:
-  docket level `meta`
-  more_docs
- timestamp (timestamp when the docket was indexed)
- date_created (docket date_created)
- recap_document level `meta`
- timestamp (timestamp when rd was indexed)
- date_created (rd date_created)
- d type `meta`:
- timestamp (timestamp when the docket was indexed)
- date_created (docket date_created)
- rd type `meta`:
- timestamp (timestamp when rd was indexed)
- date_created (rd date_created)
Here some examples:
```
{
"assignedTo":null,
"assigned_to_id":null,
"attorney":[
],
"attorney_id":[
],
"caseName":"Attia v. Oura Ring, …
```

4032 Tweaked V4 RECAP Search API objects

---

cl/lib/elasticsearch_utils.py
cl/search/tests/tests_es_person.py

I noticed that doing a match all query in the V4 People Search API and sorting by `dob desc` was not working:
https://www.courtlistener.com/api/rest/v4/search/?q=&type=p&order_by=dob%20desc%2Cname_reverse%20asc
I was able to reproduce the issue by cloning judges with the oldest dates of birth in the database.
The problem was that sorting judges by `dob desc` was failing because some judges were born before the previously used offset date of George Washington's birthday (February 22, 1732).
You can see some of these judges in this query:
https://www.courtlistener.com/?q=&type=p&order_by=dob%20asc%2Cname_reverse%20asc
To fix the issue I changed the offset to `1600-01-01` within `build_custom_function_score_for_date` to ensure we can cover all the Judges `dob`.

Fix V4 People Search dob desc sorting

---

cl/lib/storage.py
cl/settings/third_party/aws.py

This PR adds a new variable `AWS_PRIVATE_STORAGE_BUCKET_NAME` to the settings. This allows us to configure a separate storage bucket specifically for development purposes. This way, when developing new features or debugging existing ones, we can avoid accidentally uploading files to the production bucket, improving development safety and data security.

feat(settings): Adds variable to set the private storage bucket name

---

cl/lib/document_serializer.py
cl/lib/test_helpers.py
cl/search/api_serializers.py
cl/search/tests/tests_es_oral_arguments.py

To complete #2680, I reviewed the ES V3 OA Search API that we have developed but is not yet being used in production. 
To ensure that the responses are fully compatible with the field values currently in the Solr version.
Two tweaks were required:
`panel_ids`: In Solr, when this field is empty, it returns `None`. I changed the field in the ES version to return None when empty, instead of an empty list as in V4.
`timestamp`: Returns the timestamp in the same format as the Solr version, using a time offset relative to the server's local time (PT).
The object now looks like this:
```
{
"absolute_url": "/audio/4/snyder-santiago-and-patterson-v-allen/",
"caseName": "Snyder, Santiago and Patterson v. Allen",
"court": "Superior court of the dragons",
"court_citation_string": "",
"court_exact": …
```

2680 Compatibility tweaks to make ES V3 OA API fully compatible with Solr version

---

cl/simple_pages/templates/help/coverage.html
cl/simple_pages/tests.py

This PR addresses #4068 by using the [floatformat](https://docs.djangoproject.com/en/5.0/ref/templates/builtins/#floatformat) filter within the `coverage.html` template. This ensures the displayed number of minutes is rounded to an integer, enhancing readability. Additionally, I've added a new test to verify the template accurately presents the rounded minutes.

fix(simple_pages): Round the OA minute count in the coverage page

---

cl/recap/api_serializers.py
cl/recap/tests.py

This PR adds logic to verify the `court` associated with recap documents before attempting to fetch their PDFs. Additionally, I've included a test to check the validation works properly.
This PR fixes one of the issue from #4084

feat(recap): Refines validate method in the PacerFetchQueue serializer

---

cl/corpus_importer/management/commands/recap_into_opinions.py
cl/opinion_page/templates/opinion.html

Add PDF to front end for the new opinions in opinion.html set required to false for total documents to process Add error handling for citation matching - when some unicode text causes headaches.
Add logging around citation fails and
logging for all new recap documents
Finally, save local path not to download url
its more accurate and lets us directly link frontend pdf

feat(recap->op): Fixes for recap into opinions and tweaks

---

cl/api/templates/webhooks-docs-vlatest.html

This PR updates the docket alert example on the webhook documentation page. 
I noticed a slight difference in the endpoint the example is using to create docket alerts. The correct endpoint is `/api/rest/v3/docket-alerts/` instead of `/api/rest/v3/docket-alert/`. Additionally, this endpoint uses the field `docket` instead of `docket_id` to specify the docket you want to subscribe to.

fix(docs): Update docket alert example to improve webhook documentation

---

cl/audio/tasks.py

Set `audio.stt_status = Audio.STT_FAILED` on BadRequestError. The error has a message like
'The audio file could not be decoded or its format is not supported' So as to avoid naive retries of bad audio files

fix(audio.transcribe): mark failed when BadRequestError is raised

---

cl/scrapers/utils.py

Changed the default  value for `requests.get` argument verify from  False, to depend on the presence of a "cipher". Sending verify = False when the session used a custom ssl context caused an error.
Solves #4120

fix(scrapers.get_binary_content): verify now depends on Site.cipher

---

cl/audio/management/commands/transcribe.py
cl/audio/tasks.py

- Add "dont-retry-task" argument to command
- Handle retries in except clause, no longer using auto_retry_for
- add logger.info call for number of retries
- add logger.error call when audio with status STT_COMPLETE as enqueued for transcription
- now sending all exceptions to Sentry
In general, these changes allow to better control and monitor the requests, since we were seeing more requests than expected

fix(audio.transcribe): tweak retry behavior

---

cl/corpus_importer/management/commands/make_aws_manifest_files.py

This PR tweaks the `make_aws_manifest_files` command to selectively retrieve records for the manifest files. It uses the `stt_status` field as a filtering clause. This change makes sure that only records with completed transcriptions are included in the generated manifests.

feat(corpus_importer): Update filtering clause to retrieve audio with transcriptions

---

cl/audio/management/commands/transcribe.py
cl/audio/tasks.py
cl/scrapers/management/commands/clone_from_cl.py

- replace --retry-failures with --status-to-process: allows to retry different types of failures
- handle STT_HALLUCINATION by not sending the case name as prompt. This should work for a good part of the hallucinations
- small fix to clone_from_cl: there was a bug when copying audios with stt_transcript

fix(audio.transcribe): add argument to retry different stt_status

---

cl/audio/management/commands/transcribe.py
cl/audio/tasks.py
cl/audio/tests.py
cl/settings/project/microservices.py

This PR registers a new service to downsize audio files and updates the transcribe command to remove logic that previously prevented the processing of large files. 
The PR also introduces a new parameter named `max-audio-duration` to the transcription process. During testing, I noticed that the API could successfully transcribe **compressed** audio files under 2 hours (7200 seconds) in length. However, attempts to transcribe files exceeding this duration resulted in `InternalServerError` exceptions, even for files well below the 25MB file size limit imposed by the API. The `max-audio-duration` parameter provides a mechanism to filter out audio files based on their length.
I Identified **1,778 records** with status 4 that are under 2 hours long. By downsizing those files before sending …

feat(audio): Add logic to transcribe big files

---

cl/audio/tasks.py
cl/lib/microservice_utils.py

This PR fixes #4145 by passing the Audio object instead of the binary content to the microservice. Additionally, a match statement is implemented to ensure the CL version of the oral argument is used when downsizing records.

feat(microservice): Adds match statement to use CL version when downsizing

---

cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py

This small PR is related to #4143.
It seems that some of the problems are only happening on the server since I have not been able to replicate them locally, the problem is that the logged messages have not been enough to be able to infer what the error is since only something like:
```
2024-06-20 02:14:22.154	ERROR Failed to get free document references for wawd between 2024-06-15 and 2024-06-20 due to PACER 6.3 bug..
2024-06-20 02:14:10.649	INFO Attempting to get latest document references for wawd between 2024-06-15 and 2024-06-20
```
As you can see the message does not say much and there is no traceback available.
The change only passes the exc_info parameter to obtain the traceback but keeping the message.

Add exc_info param to pacer free document command

---

cl/lib/document_serializer.py
cl/search/tests/tests_es_opinion.py

This PR fixes #4156
The problem was that there are old opinions that were likely imported, so their `date_created` field doesn't contain microseconds. For instance:
`2010-04-28 16:01:19+00`
The `TimeStampField` `date_created` parsing format  `"%Y-%m-%dT%H:%M:%S.%f"`  failed to handle these `datetimes`.
To fix the problem I changed the parsing approach of dates to use `dateutil.parser` which can parse different `datetime` formats out of the box.

4156 Fixed TimeStampField serializer for dates without microseconds

---

cl/lib/juriscraper_utils.py
cl/scrapers/management/commands/cl_scrape_opinions.py
cl/scrapers/tasks.py

Solves #4193
Now passing the full module string through cl_scrape_opinions.scrape_court -> extract_doc_content -> update_document_from_text.
This will solve getting the wrong Site.extract_from_text method, when there is more than 1 scraper file for each court id. For example, as it happens with mass

fix(juriscraper_utils): pass full module path as optional argument

---

cl/assets/static-global/css/override.css
cl/assets/templates/base.html
cl/assets/templates/includes/dismissible_nav_banner.html

This pull request introduces two key improvements:
- **Rebranding Banner**: A new banner is added to the base template, informing users about the rebranding efforts.
- **Reusable Responsive Banner Component:** While implementing the banner, I noticed the current HTML code of the banner had some responsiveness issues. To address this and promote code reusability, I factored out the HTML into a new file and added CSS classes to make the banner fully responsive.
| Breakpoint  | Screenshot |
| ------------- | ------------- |
|  X-Small(<576px) | ![image](https://github.com/user-attachments/assets/17fa0649-fc71-42e8-ae18-c3a2b26fc61d)  | 
| Small (≥576px) | ![image](https://github.com/user-attachments/assets/8ad8d128-d467-4e3f-b482-37b35b88fa56) | 
|  Medium (≥768px)  | …

feat(templates): Adds rebranding announcement banner

---

cl/assets/static-global/css/override.css

This PR fixes #4215 by updating the CSS classes used to style the logo. 
Here's the breakpoint table with screenshots:
| Breakpoint  | Screenshot |
| ------------- | ------------- |
|  X-Small(<576px) | ![image](https://github.com/user-attachments/assets/ba10f807-a129-4eaa-b7cf-a98c9e1c31e6)  | 
| Small (≥576px) | ![image](https://github.com/user-attachments/assets/7eb59812-9dee-4759-8eb8-96265ce7de14) | 
| Medium (≥768px)  | ![image](https://github.com/user-attachments/assets/7bc8d6e4-f50b-48a0-89c8-d1ab042538b2) |   
| Large (≥992px) | ![image](https://github.com/user-attachments/assets/4e819df7-ebd7-4433-ad84-7bd59738bec1) | 
| Extra large (≥1200px) |  ![image](https://github.com/user-attachments/assets/aa20abef-9659-4c5c-bfb7-b12fc3aff7ae) | 

fix(template): Corrected horizontal alignment of banner and logo 

---

cl/assets/static-global/css/override.css

The padding under the logo was uneven.

fix(css): Make the navbar slightly taller

---

cl/corpus_importer/management/commands/make_aws_manifest_files.py

This PR introduces several improvements to the `make_aws_manifest_files` command, making it more flexible and efficient for generating AWS manifests.
Key Features:
- **Customizable Output Filenames**: We can specify custom names for generated manifests using the `--file-name` argument. if not provided, it defaults to the previous naming convention
- **Retrieve All Records**: Bypass filtering logic for the entire table by including the `--all-records` flag. This is useful when complete data extraction is needed.
- **Randomized Sampling**: Generate manifests based on a random sample of the table data. Use the `--random-sample-percentage` argument (between 0.0 and 100.0) to define the sample size.
Here are some examples:
------------------------------------------------------------------------ …

feat(db_manifest): Enhance command to create aws manifest files 

---

scripts/make_bulk_data.sh

Adding missing tables, setting import order to avoid foreign key constraint violations, and changing quote character for CSV data to '`' so it doesn't cause parsing errors with quotes in the XML data column.

Bulk data export script bugfixes

---

cl/corpus_importer/tasks.py
cl/corpus_importer/tests.py
cl/recap/mergers.py
cl/scrapers/tasks.py
cl/tests/fakes.py

This PR adds support for storing the HTML files from the Case Query Crawl as PacerHtmlFiles instances.
HTML files are stored for both dockets retrieved by the probe daemon and cases retrieved by the sweep signal.
Fixes: #4231

4231 Store HTMLs from Case Query Crawl

---

cl/api/tests.py
cl/people_db/filters.py

This PR fixes an issue where duplicate attorney records were included in the endpoint response due to the many-to-many relationship between `attorneys` and `dockets` via the `role` table.
To address this, the `distinct` argument has been added to the attributes of the `AttorneyFilter` class. This ensures that only unique attorney records are returned in the response, improving data accuracy and consistency.
This PR fixes #4264

fix(api): Removes duplicate attorneys from response by using distinct

---

cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py

The error was very simple, the order of the parameters of the ocr_available function were inverted in do_everything function.
What made it difficult for me to see this very obvious error is that when I tried to replicate the error by running the command in my local environment I was never able to see the exception shown in sentry, the command did not throw any exceptions.
I thought it had to do with the CELERY_TASK_ALWAYS_EAGER flag, but I couldn't replicate the error by changing it. 
To manually queue these failed documents that require ocr we need to run the following command, if it is merged before the task is run again then it should not be necessary:
` manage.py scrape_pacer_free_opinions --action ocr-available
`

Correct do_everything function used in pacer free documents command

---

cl/custom_filters/templatetags/extras.py
cl/search/templates/includes/search_result.html
cl/search/tests/tests_es_recap.py

This PR adds the docket entry date filed to the RECAP results. It is always displayed, regardless of the selected sorting.
Final screenshots:
Mobile:

4254 Added docket entry date filed within the RECAP search results

---

cl/lib/elasticsearch_utils.py
cl/lib/paginators.py

As mentioned in #4209, this fixes the estimation of cardinality queries. They were incorrect because `track_total_hits` was set to `True`, causing the response to retrieve both the exact count and the estimation. Now, it will only perform and return the estimation count.
Additionally, I set `track_total_hits=False` in the main query so that no count is retrieved. Previously, it would retrieve up to 10,000 hits. This is unnecessary since it's not used.

Fixed cardinality count queries

---

cl/search/admin.py

I noticed the admin panel was experiencing slow loading times and occasional failures when accessing docket data. I started debugging the issue and noticed it was primarily caused by excessive database queries generated by the newly added `parent_docket` ForeignKey field (introduced in #4263 ).
Django's admin interface typically uses **select-box interfaces** for `ForeignKey` fields, which can negatively impact performance due to the loading of all related instances. This PR enhances efficiency by adding the `parent_docket` field to the `raw_id_fields` list. This change replaces the **dropdown** with an **input** field, reducing the number of database queries required and resulting in a noticeable improvement in admin panel responsiveness.

fix(admin): Add parent_docket field as input for editing

---

cl/corpus_importer/tasks.py
cl/lib/pacer_session.py
cl/lib/tests.py
cl/recap/tasks.py
cl/recap/tests.py

This PR removes redundant session code introduced in #4192. This logic was specifically added to handle session data previously stored in the cache. With the recent changes to session data, this code is no longer necessary and can be safely removed.
This PR fixes #4298

feat(proxy): Removes logic to handle legacy cached session data

---

cl/lib/model_helpers.py
cl/lib/tests.py

This is modifying #4293 because of a minor regex issue related to commas in Federal Register citations. See this case for an example: https://www.courtlistener.com/docket/68527293/airlines-for-amer-v-dept-of-trans/.
In that case, the citation is 89 Fed. Reg. 34,620 but the function is linking to https://www.federalregister.gov/citation/89-FR-34 instead of https://www.federalregister.gov/citation/89-FR-34,620.

Linkify administrative citations (minor revision)

---

cl/lib/elasticsearch_utils.py
cl/search/templates/includes/search_result.html
cl/search/tests/tests_es_recap.py

According to #4324 this PR fixes the button text to match the correct legend based on the jurisdiction type.
**District:**
Document available
`Initial Complaint`
Buy document:
`Buy Initial Complaint`
**Bankruptcy:**
Document available
`Initial Petition `
Buy document:
`Buy Initial Petition`
**Appellate:**
Document available
`Notice of Appeal`
Buy document:
`Buy Notice of Appeal`
Let me know what do you think.

4324 Tweaked the initial complaint button text according to the jurisdiction type.

---

scripts/make_bulk_data.sh

Fixing quote character not being escaped and replacing server side COPY with client side version

Issue #4326

---

cl/assets/templates/base.html

This PR removes the rebranding announcement banner from the base template.
Fixes #4320

feat(templates): Removes rebranding announcement banner

---

cl/citations/match_citations.py
cl/citations/match_citations_queries.py
cl/search/templates/search.html
cl/search/tests/tests_es_opinion.py
cl/search/views.py

As outlined in #4252, this PR introduces a feature that checks if the query contains citations. It searches for the citations in the Opinions index, and any citations that cannot be found are removed from the query. The query is then performed without the missing citations, and the user is informed accordingly.
It works for one or many missing citations in the query.
**Example with one missing citation:**
**Example with two missing citations:**
**Example with one missing citation and one that could be found.**
One remaining question:
As you can see, the modified query is shown in the search bar. Or should we display the original query instead?

Drop citations from Opinions queries if we don't have them

---

cl/assets/static-global/css/override.css
cl/assets/static-global/js/export-csv.js
cl/lib/ratelimiter.py
cl/opinion_page/templates/docket_tabs.html
cl/opinion_page/templates/includes/de_list.html
cl/opinion_page/tests.py
cl/opinion_page/utils.py
cl/opinion_page/views.py

This PR addresses a bug that was leading to inaccurate data in the exported CSV file. To address this issue, we've refactored the `generate_docket_entries_csv_data` function to avoid using a common variable within the inner loop.
This PR implements a rate limiter to control the frequency of CSV exports per hour. Additionally, the `de_list` template has been modified to display a loading spinner while the export request is in progress. If the rate limit is reached, an error message will be shown to inform the user about the issue.
Here are some gifs showing the spinner and the error message: 
<details>
<summary>Regular Download</summary>
</details>
<details>
<summary>Ratelimit Error</summary>
</details>
-----
<details>
<summary>Regular Download</summary>
</details>
<details> …

fix(utils): Prevent incorrect CSV data appending due to shared variable

---

cl/scrapers/DupChecker.py

A bug was introduced in the previous [modification](https://github.com/freelawproject/courtlistener/pull/4303) of the DupChecker, where SingleDuplicateError was not raised when the item was duplicated if we were not in a full_crawl

fix(scrapers.DupChecker): ensure raising SingleDuplicateError

---

cl/corpus_importer/management/commands/bulk_iquery_project.py
cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py
cl/corpus_importer/utils.py

This PR introduce these changes:
- We need to add this cron job to run he daily scrape
```shell
manage.py scrape_pacer_free_opinions --action=do-everything --date-start `date -d "10 days ago" +"%Y-%m-%d"` --date-end `date +"%Y-%m-%d"`
``` 
- Implementation of a new way to rotate between courts to download the PDFs to not hit each court server with a lot of downloads. It will download one item for each court until it finishes all the pending documents to download, in the previous code we downloaded everything from each court. It will go through rows like this:
| court_id | pk  | row_number |
|----------|-----|------------|
| 1        | 10  | 1          |  
| 2        | 11  | 1          | 
| 3        | 13  | 1          |  
| 1        | 12  | 2          |  
| 2        | 14  | 2          | 
| …

Improve PDF file download for pacer free documents command

---

cl/lib/search_index_utils.py
cl/search/documents.py
cl/search/signals.py
cl/search/tasks.py
cl/search/tests/tests_es_recap.py

According to #3046, this PR focuses on extracting the parties from the Docket `case_name` if normalized parties are not available, and indexing them into the party field so they can be used for filtering.
Some considerations:
- The `case_name` is the only field considered for extracting parties (not `case_name_full` or `case_name_short`).
- The possible separators used to split the case_name into parties are the same ones used to boost the case_name during search: " v ", " v. ", " vs. ", " vs ".
- The split of the `case_name` is performed only once, meaning that names like "Google v. America v. Oracle," which have more than two parties, are not divided into 3 parties. Is this type of case name possible?
- This applies to the indexing of new dockets as well as to docket updates if the …

3046 Index party from case_name when normalized parties are not available

---

cl/recap/mergers.py
cl/recap/tests.py

Since `rd.description` may be from an attachment we should never blindly apply it to the main document.

Don't apply attachment description to main document

---

cl/search/tests/tests_es_recap.py
cl/search/views.py

I noticed that the `test_profile_urls` test is failing randomly.
This test requires a user session to pass. I believe what's happening is that previous `cache.clear()` for search micro-cache test was causing all cache entries to be deleted, including user sessions, which affects other tests.
To solve the issue, I added a prefix to the micro-cache keys and ensured that only related keys are cleared during the test.

Added prefix to the search micro-cache key to avoid affecting other tests

---

cl/search/tests/tests_es_opinion.py

It seems that this test is still failing, as Eduardo reported to me. I believe the issue is now the same as in the RECAP test. The `OpinionClusterFactory` also uses the `case_name_full` field, which is randomly generated and can sometimes match the query.
Another lesson learned here: we must always set all the text-generated fields in factories for search tests.

Fixed Opinion Search case_name exact test randomly failing due to factories

---

cl/lib/elasticsearch_utils.py
cl/search/templates/includes/search_result.html
cl/search/tests/tests_es_recap.py

As requested in #4324, I've applied the button text change.
Now, it shows `"Initial Document"` when available and `"Buy Initial Document"` when it is not. 
This applies for all filing types.
This also simplified the query since we no longer need to differentiate the text for court types.
Fixes: #4324

 4324 Renamed initial complaint button to initial document

---

cl/recap/mergers.py
cl/recap/tests.py

Sometimes attachments are missing a `pacer_doc_id` which can prevent matching the `main_rd` needed for looking up the `de` in which to store the attachments being processed. When this is the case we should try to locate the `main_rd` using any of the attachment `pacer_doc_id`'s.

Attempt to match attachment main_rd against all attachment doc id's

---

cl/assets/static-global/css/override.css
cl/assets/static-global/js/base.js
cl/assets/static-global/js/progress-bar.js
cl/search/templates/advanced.html
cl/search/templates/homepage.html
cl/search/templates/search.html

This PR fixes #4384 by implementing a visual progress indicator to provide feedback during search requests. While the original issue outlined a `HTMX`-based solution, this implementation uses existing code and a more straightforward JavaScript event-driven approach due to conflicts with HTMX's history navigation functionality.
Key Changes:
- Updates the `submitSearchForm` to create a progress bar element and disable submit buttons upon form submission. 
- Adds an event listener to detect page transitions (the browser starts loading a new page). Upon detection, the progress bar's style is updated to reflect the search request's completion status.
Here's a gif showing the progress bar in action:

feat(search): Adds progress marker to search results

---

cl/assets/static-global/js/progress-bar.js

This PR addresses inconsistent progress bar behavior caused by visibility change listener. The progress bar now remains visible even when switching tabs or minimizing the browser, providing a more consistent user experience.

fix(progress bar): Removes visibility change listener

---

cl/settings/django.py

This PR removes the `CONN_MAX_AGE` setting, which in production seems to be set to 60 seconds, making it incompatible with enabling the DB pool.
For developers, this isn't an issue since the value is set to 0 by default.

Removed CONN_MAX_AGE setting to enable DB pooling

---

cl/scrapers/utils.py

Related to #4256
Doing a Docket lookup when the docket number is empty will match false positives

fix(scrapers.utils.get_existing_docket): return None when docket_number is an empty string

---

cl/api/templates/case-law-api-docs-vlatest.html
cl/api/templates/citation-api-docs-vlatest.html
cl/api/templates/financial-disclosure-api-docs-vlatest.html
cl/api/templates/includes/toc_migration_guide_sidebar.html
cl/api/templates/includes/toc_sidebar.html
cl/api/templates/jurisdictions.html
cl/api/templates/migration-guide.html
cl/api/templates/pacer-api-docs-vlatest.html
cl/api/templates/rest-change-log.html
cl/api/templates/rest-docs-v1.html
cl/api/templates/rest-docs-v2.html
cl/api/templates/rest-docs-v3.html
cl/api/templates/rest-docs-vlatest.html
cl/api/templates/search-api-docs-vlatest.html
cl/api/urls.py
cl/api/views.py

Now that the API is live, I was able to see everything at once and I had a number of edits that came to me. Please see commit notes or diff for details.
I'd like to get a review of this, but I think it's a clean improvement as it is, so I'm merging now in case anybody is looking at the API over the weekend. 
But let's do a full review anyhow, and we can fix anything that should be better.

Api v4 edits

---

cl/custom_filters/templatetags/extras.py
cl/lib/test_helpers.py
cl/search/tests/tests_es_recap.py

This PR fixes #4487. The issue was that child documents from ES are strings, so they need to be converted to date objects before formatting. The previous approach was weak because it only extracted the day and appended `th` to it.
Now, the code relies on Django's built-in `date_filter`, which properly formats dates following English rules (1st, 2nd, 3rd, 4th, and so on). It also fixes the issue of adding a leading zero to days less than 10.

4487 Fixed entry_date_filed display on RECAP Search results

---

cl/users/tests.py
cl/users/views.py

This PR fixes #4466 by adding stricter validation to the email query parameter to mitigate text injection risks. If an invalid email format is detected, a `SuspiciousOperation` exception is raised and logged at the Error level.

fix(users): Prevent text Injection in Email Query Parameter

---

cl/recap/tests.py

This PR fixes #4490 
I confirmed that we're using IncrementingAWSMediaStorage for RECAPDocument uploads, and the change in naming does not affect production.
For existing file names using IncrementingAWSMediaStorage, the file names preserve the correct behavior:
```
gov.uscourts.hocad.205202.1.0.pdf
gov.uscourts.hocad.205202.1.0_1.pdf
```
So this issue only occurs in the tests. I applied the following fixes:
- Updated `test_docket_and_docket_entry_already_exist` name assertion to be compatible with Django file storage on tests regarding naming prefix changes.
- Added mocks to avoid delays in process_recap_pdf tests. Reduced RecapPdfTaskTest from 11s to 1s

4490 Fixed test_docket_and_docket_entry_already_exist assertion to prevent random failures

---

cl/api/templates/migration-guide.html
cl/search/views.py

Key changes:
- Adds  the `@never_cache` decorator to set cache control header to the `advanced` view( which is used to render the following pages: **recap**, **oral arguments**, **financial disclosure**, and **judge** search) so it's always loaded fresh from the server. 
- Fixes a few typos in the migration guide.

fix(search): Set cache control header to the advanced view

---

cl/api/templates/alert-api-docs-vlatest.html
cl/api/templates/case-law-api-docs-vlatest.html
cl/api/templates/citation-api-docs-vlatest.html
cl/api/templates/citation-lookup-api-vlatest.html
cl/api/templates/financial-disclosure-api-docs-vlatest.html
cl/api/templates/includes/v3-deprecated-warning.html
cl/api/templates/judge-api-docs-vlatest.html
cl/api/templates/oral-argument-api-docs-vlatest.html
cl/api/templates/pacer-api-docs-vlatest.html
cl/api/templates/recap-api-docs-vlatest.html
cl/api/templates/rest-docs-v3.html
cl/api/templates/search-api-docs-v3.html
cl/api/templates/visualizations-api-docs-vlatest.html

Fixes: #4501 
This PR adds the V3 deprecation warning to all V3 pages.
For all API help pages (except Search), we use the same template, and only the API routes within the content change dynamically according to the API version in the URL. Also this warning is displayed when the page URL matches `/help/api/rest/v3/`.
I also noticed that within the root V3 documentation, API routes were linking to the latest version (V4), so I adjusted these routes to link to V3 to ensure the warning is displayed on those pages.
Additionally, I fixed a typo in the `Oral Argument Recordings API` title, which was previously `Oral Argument Recoding API`.

4501 Added a V3 deprecation warning to all V3 API pages

---

cl/favorites/tests.py

- Fixed by using the same date formatter as in the email template to avoid discrepancies.

Fixed test_prayers_integration failing test regarding date format

---

cl/favorites/tests.py

This is a fix for the failing `test_prayers_integration` test, which starts failing from 5 PM PT, corresponding to the next day in UTC. The issue is caused by a difference in the timezone context when formatting the date in the test.

Fixed test_prayers_integration test due to a difference in the timezone context

---

cl/scrapers/management/commands/cl_back_scrape_opinions.py
cl/scrapers/management/commands/cl_back_scrape_oral_arguments.py

- Abstract into a function the backscraper `parser.add_argument` calls,
to prevent duplication
- Add dynamic backscraping support to oral argument scrapers
- Support days_interval optional argument, as expected in https://github.com/freelawproject/juriscraper/pull/1108

feat(cl_back_scrape_oral_arguments): add backscrape-start and backscrape-end optional args

---

cl/recap/management/commands/clean_up_docket_judges.py
cl/recap/tests.py

As described in #4541, this PR introduces the `clean_up_docket_judges` command to clean up `assigned_to` and `referred_to` fields when their corresponding `assigned_to_str` and `referred_to_str` values have changed, and we don't have the new judges in database.
This works by checking all the dockets in the database where `referred_to` and `assigned_to` are not `null`. Then, the docket `assigned_to_str` and `referred_to_str` values are used to perform a Judge lookup using `lookup_judge_by_full_name`.
If the current `assigned_to` and `referred_to` values are different from the ones returned by the lookup (which includes a `None` value in case the Judge is not found), the docket is updated.
Since this `save()` will trigger an Elasticsearch update, it's better to do it slowly. I set a default …

4541 Introduced clean_up_docket_judges command to clean up assigned_to and referred_to

---

cl/corpus_importer/tasks.py

Small change to skip the document if it doesn't have a case number.
See issue #4547
When it is ready we can resume the sweep.

Update pacer free document command to ignore documents without case number

---

cl/api/templates/search-api-docs-v3.html
cl/api/templates/search-api-docs-vlatest.html

The example commands in the search API documentation (v4 and v3) were missing a necessary closing single quote.

fix(docs): correct quoting in examples with `jq`

---

cl/search/filters.py

The Bluebook's court abbreviations are fairly close to an identifier. While there's a suggestion that they may not be stable – some administrative agencies have lobbied to avoid the periodization of their reporters[^1], they are still useful. When working directly from a citation, this is the best route to a CourtListener court `id`.
[^1]: Fred Jacob, Even the Federal Government Can’t Beat The Bluebook, 27 Green Bag 2d 117 (2024)

feat(api): add `citation_string` as a `CourtFilter` filter field

---

cl/scrapers/management/commands/cl_back_scrape_opinions.py
cl/scrapers/management/commands/cl_back_scrape_oral_arguments.py

feat(cl_back_scrape_opinions): add optional wait argument

---

cl/recap/mergers.py

Looks like this was broken in #4352.

Fix check for restricted attachments

---

docker/courtlistener/docker-compose.yml

`docker-compose.yml` was going about specifying paths relative to the base directory in a handful of ways. Some were just convoluted (see `cl-postgresql`) while others were incorrect (see `cl-es`). With this patch, the `courtlistener` directory is consistently referred to with `${CL_BASE_DIR:-../../}`.

chore(docker): improve usage of `CL_BASE_DIR`

---

.github/workflows/flp-dependencies-pr.yml

auto update flp dependencies action was broken by recent update to python 3.13, since `python-version` specification '3.x' was interpreted as 3.12.7

fix(github.actions): set python version to >= 3.13

---

cl/recap/mergers.py

I recall coming across some attachments with blank description that did not have restricted documents, I think we probably need to process these.

Process attachments without descriptions

---

cl/simple_pages/forms.py
cl/simple_pages/templates/contact_form.html
cl/simple_pages/tests.py
cl/simple_pages/views.py

Addresses #4585 
This update enhances the contact form by allowing users to select the "Issue Type" for their submission, and also optionally pre-select it via URL query parameters, improving UX.
Additionally, the contact form now sends submissions to `support@freelawproject.atlassian.net`, integrating with Jira for better issue tracking. The email body includes:
- User Email: Displayed as `User Email: <email address>` to facilitate easy parsing in Jira.
- Issue Type: Clearly stated to assist in automatic categorization within Jira.
- Subject and Message: Retained as before for detailed context.
This change enables automatic ticket creation to relieve some of the overhead of managing requests manually by email.

feat(contact_form): Enable selection of issue type and enable Jira integration

---

cl/search/management/commands/import_harvard_pdfs.py
cl/search/tests/test_import_harvard_pdfs.py

Fixes an issue where the PDF import script wasnt working.
Changes:
- Fixes path construction for CAP pdf download path
- Fixes handling of content file for the PDF
- Additional error handling added
- Unit tests updated to reflect modified logic
QA steps:
I pointed the save function to a local dir and verified that PDFs are saved correctly.  This needs verified that it works with S3

Fix path construction and pdf file handling

---

cl/custom_filters/templatetags/pacer.py

This will help us see its value in Sentry. See:
https://github.com/freelawproject/courtlistener/issues/4589

debug(pacer): Put page_count in a variable

---

.github/workflows/tests.yml

This isolation trims ~90s in billable GHA time and, by way of isolating the build, makes build errors easy to seperate from test errors.

refactor(workflows): isolate courtlistener build from test phase

---

cl/disclosures/tasks.py
cl/recap/tasks.py

This is following up on the discussion in #4589 and the earlier fix in #4592, which was not comprehensive and missed another instance in the codebase of `page_count` being temporarily stored as a `str` instead of an `int`. It fixes this by casting `page_count` before the rd is created.

fix(favorites): casting page_count from str to int to ensure pray-and-pay emails work

---

cl/search/management/commands/import_harvard_pdfs.py
cl/search/tests/test_import_harvard_pdfs.py

- Add argument to set number of workers (2 by default)
- Add argument to set reporter to start from
- Improve the readability of reporters names
- Tests updated
Set workers number
`manage.py import_harvard_pdfs --crosswalk-dir /opt/courtlistener/cl/assets/media/crosswalk  --max-workers 4`
Go thru all reporters but starting from specific repoter:
`manage.py import_harvard_pdfs --crosswalk-dir /opt/courtlistener/cl/assets/media/crosswalk --start-from-reporter "Hill"`

feat(harvard_pdfs): parallelize cap pdf download

---

cl/audio/templates/oral_argument.html

This PR completes #4625, by allowing users to link from an audio page to the corresponding docket, similar to how existing appellate dockets allow users to see the lower courts the cases originated from.  
I wasn't sure if the site typically includes `class="meta-data-value select-all"` in `<a>` tags as well as plaintext, but if it does, I can add the class to the link as well.

feat(audio): link to RECAP search from audio pages

---

cl/corpus_importer/management/commands/recap_into_opinions.py
cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py
cl/corpus_importer/tasks.py

Features:
- add corpus_importer.tasks.recap_document_into_opinions into the scrape_pacer_free_opinions chain: this will make the recap documents be ingested in real time into the case law database
- tweaked the task so it can be used by both the scraper_pacer_free_opinions and recap_into_opinions command
Refactors:
- renamed task `ingest_recap_document` to `recap_document_into_opinions`
- renamed task `extract_recap_document` to `extract_recap_document_for_opinions`
- deleted duplicated function `extract_recap_document` in recap_into_opinions command file; delete unused imports and code

feat(scrape_pacer_free_opinions): apply task recap_document_into_opinions

---

cl/search/management/commands/generate_cap_crosswalk.py
cl/search/tests/test_generate_cap_crosswalk.py

Adds support for the updated_after param that checks CAP data for a last_updated field.  This will allow us to generate crosswalk files consisting of cases that have been updated after a given date.  Dates should be in either format: YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS+00:00.
Changes:
- Adds updated_after param to the generate_cap_crosswalk command 
- Adds logic for filtering based on the given date
- Unit tests added

add support for last_updated field in crosswalk generation

---

cl/alerts/management/commands/cl_send_recap_alerts.py

This PR addresses issues described in https://github.com/freelawproject/courtlistener/issues/4646#issuecomment-2466985751.
Key changes: 
- Refines checks to prevent early termination of the recap_document_sweep reindex process.
- Enforces upper bound on time estimate calculations.
To ensure a clean slate for the next execution and prevent issues from previous failed attempts, we should run the following Python script in production to remove any residual keys from Redis:
```python
from cl.lib.redis_utils import get_redis_interface
r = get_redis_interface("CACHE")
r.delete("alert_sweep:main_re_index_completed")
r.delete("alert_sweep:rd_re_index_completed")
r.delete("alert_sweep:query_date")
r.delete("alert_sweep:task_id")
```

feat(alert): Refines send recap alerts command

---

.env.example

When I tried to clone data from CL using the `clone_from_cl` command I got an error, because the command was expecting `CL_API_TOKEN` but the `.env.example` had `CL_API_KEY`. This PR fixes it.

fix(env): Change CL_API_KEY to CL_API_TOKEN

---

cl/search/api_utils.py
cl/search/api_views.py

As described in #4714, this PR fixes the use of waffle flags in the V3 Search API. 
Flags are now checked once per request, ensuring that when we start using percentages to brown-out Solr, any request selected to use Elasticsearch will have both the search query and the serializer aligned to use Elasticsearch.

4714 Refactored the use of flags in the V3 Search API to support an effective brown-out strategy

---

cl/opinion_page/templates/includes/rd_metadata_headers.html

feat(document_page): Add link to document in docket sheet

---

cl/api/tasks.py
cl/api/templates/search-api-docs-vlatest.html
cl/lib/test_helpers.py
cl/search/api_serializers.py
cl/search/api_utils.py
cl/tests/cases.py

As requested in #4312, this PR introduces the `score` field into the V4 Search API results for all search types.
We already have the `meta` field in V4 Search results, so I believe it makes sense to include the `score` within this field.
Additionally, since we plan to implement other ranking algorithms in the future to display alternative scores, it seems more appropriate to use the hash approach for this purpose. Currently, it only includes `bm25`, which is the score returned by Elasticsearch.
```
"meta": {
"timestamp": "2024-06-22T10:26:35.320787Z",
"date_created": "2022-06-26T23:24:18.926040Z",
"score": {
"bm25": 2.1369965
}
}
```
The `score` is only displayed for main documents across all search types. Nested documents do not include the `score` field in their `meta` section.
- In the …

4312 Introduced score field in the V4 Search API results

---

cl/opinion_page/views.py

While reviewing the details on https://github.com/freelawproject/courtlistener/issues/4713, I noticed that the flag on the `court_home` page view was incorrect. It was using `oa-es-active`, but the correct flag name should be `o-es-active` to ensure consistency with the flag in the template. 
This will allow the results to be properly rendered once we switch to ES.

Fixes o-es-active flag on court_homepage

---

cl/lib/utils.py
cl/search/tests/tests.py

This PR fixes the issue described in #4737.
I also noticed a recurring failing test related to storing queries for Solr. The issue seems to be caused by a flag being overridden, causing the tests to fail when run in parallel.
Since we are now transitioning to ES, these tests are no longer relevant. I have removed them.

4737 Avoid wrapping numbers in quotes for boost queries.

---

cl/api/tests.py
cl/search/filters.py

Resolves #4711
This PR also adds more tests for court filters, and it makes the assert message more descriptive in `FilteringCountTestCase.assertCountInResults` so it now includes the request url that prompted the response, for example:
```
AssertionError: 0 != 1 : Expected 1, but got 0 in /api/rest/v4/courts/?start_date__year=2021
r.data was: OrderedDict({'count': 0, 'next': None, 'previous': None, 'results': []})
```

feat(api): Enable filtering courts by parent court id

---

cl/lib/elasticsearch_utils.py
cl/search/tests/tests.py
cl/search/tests/tests_es_opinion.py
cl/search/views.py

This PR addresses a couple of issues reported on Sentry after switching to ES.
[COURTLISTENER-8QK](https://freelawproject.sentry.io/issues/6093090620/)
This error occurred when a user (or bot) performed deep pagination on the frontend.
It triggered a 500 error due to an `UnboundLocalError`, as the `error` variable was not set when a `PermissionDenied` exception was raised during deep pagination.
[COURTLISTENER-8QM](https://freelawproject.sentry.io/issues/6093221088/)
This error was encountered in V3 Opinion Search alerts using ES. A 500 error was raised because the collapse count query returned `None` instead of an integer, causing the request to fail during the pagination stage. This prevented the API from raising the correct error message:
`"Internal Server Error. Please try again later …

Fixed small search issues after the ES switch

---

cl/lib/elasticsearch_utils.py
cl/opinion_page/utils.py
cl/search/constants.py
cl/search/tests/tests_es_opinion.py

After investigating the issue with the MLT query using the production cluster to test the queries, I found a couple of issues affecting this query:
- The MLT documentation doesn't mention it, but I found that `routing` is required in production to properly reference the existing document in the index.
```
"like":[
{
"_id":"o_1472349",
"routing":1472349
}
]
```
The routing corresponds to the `cluster_id` the opinion belongs to so an additional DB query is required to retrieve it when performing the MLT query.
- The fields used in the MLT query must be the `exact` version. Otherwise, they affect the query, and sometimes they don't match results at all. This is likely because the exact version doesn't remove duplicates or apply stemming, which can lead to improper analysis when comparing …

4305 Fixed ES More Like This query

---

cl/corpus_importer/management/commands/probe_iquery_pages_daemon.py
cl/corpus_importer/tests.py
cl/settings/project/corpus_importer.py

The `probe_iquery_pages_daemon` is cycling because it hasn’t found new content. For now, I’m renaming the daemon setting to `IQUERY_CASE_PROBE_DAEMON_ENABLED`, which defaults to `False`, so the daemon will be disabled.

Changed setting IQUERY_CASE_PROBE_DAEMON_ENABLED to disable probe_iquery_pages_daemon

---

cl/assets/templates/base.html
cl/assets/templates/includes/dismissible_nav_banner.html

This PR fixes #4750 by adding a banner for GivingTuesday.
Instead of creating a new variable, we can use the existing `FUNDRAISING_MODE` setting. By simply toggling this variable, we can easily display the banner.

feat(assets): Adds GivingTuesday banner

---

cl/opinion_page/templates/opinions.html

Fix addresses #4762 
We enabled the scans to be downloaded but not viewed for the new harvard data.
This PR simply checks for scrapes and PDF scans

fix(opinions.html): Enable Harvard SCAN tab

---

cl/opinion_page/views.py

Fixes #3637 
Fixes an overly broad sponsorship bug

fix(opinion_page.views): Update sponsorship timeframe

---

cl/opinion_page/templates/opinions.html
cl/opinion_page/views.py

PR addresses three small front end cleanups.
#4785 Tweak tabbed text for each tab
#4786 No follow and no index for PDF case law page
#4788 Case caption converted to H1 tag

Small Front End UI Tweaks

---

cl/lib/utils.py
cl/search/tests/tests.py

This PR updates the `cleanup_main_query` method to remove spaces between phrases and proximity operators. 
Fixes #2965

feat(lib): Removes spaces in proximity search

---

cl/assets/static-global/css/opinions.css
cl/opinion_page/templates/opinions.html

Remove pink/brown caption color
Go Sans Serif
@mlissner a nice gray - and sans serif for your approval

fix(opinions.css):Front end tweaks

---

cl/search/views.py

The issue with the Latest Opinions section on the Home page is caused by an incorrect sorting field. It currently uses `dateArgued`, whereas the correct field for sorting Opinions is `dateFiled`.
After this is deployed it'll be required to clean the related cache:
```
from django.core.cache import cache
cache.delete("homepage-data-o-es")
```

Fixed Home Latest Opinions sorting key

---

cl/opinion_page/templates/includes/authorities_list.html
cl/scrapers/management/commands/clone_from_cl.py

Resolves #4134
It took me a while to get the authorities to show up in the docket page, so I added a note in the `clone_from_cl` docstring hinting devs to use `find_citations_and_parantheticals_for_recap_documents` in the django shell to achieve this (thanks @ERosendo for the tip!)

feat(authorities): link docket authorities to search results

---

cl/lib/tests.py
cl/lib/utils.py
cl/search/tests/tests.py

This PR addresses issue #2790 by improving the handling of quotes in text queries.
Key changes: 
- Replaces smart quotes (`“` and `”`) with standard double quotes (`"`) in text queries
- Updates the `check_unbalanced_quotes` method to consider smart quotes when checking for unbalanced quotes in queries.

fix(search): Replaces smart quotes with double quotes in text queries

---

cl/recap/factories.py
cl/recap/mergers.py
cl/recap/tests.py

I think we need a fallback here in case we have entries with bad `pacer_doc_id`'s.

Fix finding document entries with a bad pacer_doc_id

---

cl/search/exception.py
cl/search/templates/includes/no_results.html
cl/search/tests/tests.py
cl/simple_pages/templates/help/advanced_search.html

Fixes: #4907
**Included & operator to AND documentation.**
**Added But not documentation**
Tweaked the Wildcards documentation to reflect the new behavior of `*` and `!` and updated fuzzy search documentation according to ES behaviour:
**Added documentation about disallowed expensive wildcard patterns:**
**Linked disallowed expensive wildcard error message to documentation:**
Fixed the `/s` and `/p` syntax error message to correctly refer to a proximity query example instead of a fuzzy query, as it did previously.

4907 Tweaked advanced search documentation to include new search operators

---

cl/citations/annotate_citations.py
cl/citations/tests.py

Aria description needs to be safely handled
Escape case names and added tests

feat(annotate_ciations): Add test for unsafe characters

---

cl/recap/tasks.py
cl/recap/tests.py

This PR fixes the issue described in #4836 where the attachment merge process fails when a recap email indicates attachments but the main document is sealed and the attachment page is inaccessible.
This bug was introduced in https://github.com/freelawproject/courtlistener/pull/4665 during the refactor of the `get_att_data_from_pq` method that parses attachment pages. The issue occurs because pages containing invalid data weren't properly marking their corresponding PQs as invalid.

4836 Fix attachment merge process for sealed documents with inaccessible attachment page

---

.github/workflows/docker-build.yml
docker/django/Dockerfile

This PR fixes the deployment workflow by removing the step that generates Tailwind CSS assets within a temporary pod. Instead, Tailwind CSS asset generation is now integrated into the Docker build process.

chore(Dockerfile): Include Tailwind asset compilation in Docker build

---

cl/disclosures/tests.py
docker/courtlistener/docker-compose.yml

This PR updates the `tearDown` method of the `DisclosureReactLoadTest` class to capture a screenshot at the end of each test run. This will help in visual regression testing and debugging.
This addresses one of the issues found in #4958

tests(disclosures): Tweaks the DisclosureReactLoadTest class

---

.pre-commit-config.yaml
cl/corpus_importer/tasks.py

isort started failing in the GitHub action due to a version mismatch between the GitHub action environment and our pre-commit version.

Bump isort pre-commit to 6.0.0

---

cl/alerts/management/commands/cl_send_alerts.py
cl/alerts/tasks.py
cl/alerts/tests/tests.py
cl/alerts/tests/tests_recap_alerts.py
cl/alerts/utils.py

As outlined in #904, this PR improves the search alert email subject to have the following structure:
`X Alert(s) have hits: "My alert name", "My other alert name"`
Where "X" is the number of alerts in the email and it includes the alert names, comma separated.
The subject length is truncated up to 935 characters with an ellipsis included, which is the maximum subject length displayed in Gmail. This length is also below [RFC2822](http://www.faqs.org/rfcs/rfc2822.html), which states that header lines must be under 998 characters.

904 Improved search alerts email subject

---

cl/lib/test_helpers.py
cl/search/api_serializers.py
cl/search/documents.py
cl/search/management/commands/cl_index_parent_and_child_docs.py
cl/search/models.py
cl/search/signals.py
cl/search/tests/tests_es_opinion.py

This PR adds the new `ordering_key` field to the Opinions index.
This field has also been added to the ES tracked fields, so Opinion instances that have this field populated will be updated in ES.
- This new field is shown in the Opinions Search API.
Additionally, the command `cl_index_parent_and_child_docs` has been modified to index only Opinions where `ordering_key` is not null.
It can be run using:
`docker exec -it cl-django python /opt/courtlistener/manage.py cl_index_parent_and_child_docs --queue celery --search-type o --document-type child --non-null-field ordering_key --chunk-size 20`
I don't remember which Celery deployment we last ran this command on. Because the indexing rate will depend on the number of workers in the queue and the queue's current busyness if it is shared with …

4976 Added ordering_key to the Opinions index

---

cl/lib/test_helpers.py
cl/search/api_serializers.py
cl/search/documents.py
cl/search/management/commands/cl_index_parent_and_child_docs.py
cl/search/models.py
cl/search/signals.py
cl/search/tests/tests_es_opinion.py

To prevent Elastic auto-maping from creating the new field as `long`  we need to wait until the indexing mapping change is done in https://github.com/freelawproject/infrastructure/issues/269

Revert Added ordering_key to the Opinions index

---

cl/corpus_importer/management/commands/make_aws_manifest_files.py

The `LIKE` filter in the `make_aws_manifest_file` command was using an extra set of quotes, resulting in incorrect filtering.  This PR removes the redundant quotes, resolving the issue and ensuring accurate filtering.
I noticed this issue while reviewing the record count shared in the following comment: https://github.com/freelawproject/infrastructure/issues/253#issuecomment-2625995827.  When I tested the new query on the dev database, the manifest jumped from 5 million to over 9 million records. That's different from what the comment in the infrastructure repo showed, so I checked the query again and noticed the extra set of quotes.

fix(corpus_importer): Remove extra quotes in like filter

---

cl/recap/tasks.py
cl/recap/tests.py

This PR fixes #4828 by adding logic to replicate attachment pages retrieved from a PACER Fetch API request to sub-dockets that require replication, matched by `pacer_doc_id`.
- The logic here differs slightly from the replication process used in RECAP uploads. In this implementation, it is sufficient to fetch the attachment page from PACER only once. After retrieving the attachment page, `ProcessingQueue` instances are created for each case requiring the attachment page to be replicated. In a secondary chained task (`replicate_fq_att_page_to_subdocket_rds`), these additional `ProcessingQueue` instances are processed. This ensures that PACER is only queried a single time, and the additional `ProcessingQueue` instances can be used for debugging purposes.
- For efficiency, the additional …

4828 Replicate attachment pages from fetch api to subdockets

---

cl/corpus_importer/tasks.py
cl/corpus_importer/utils.py
cl/recap/mergers.py
cl/recap/tasks.py
cl/recap/tests.py

As outlined in #4966, this PR applies two changes:
- During a PDF upload for a document belonging to an appellate court that does not use regular numbers, the `document_number` was being incorrectly updated with the PDF upload’s `document_number`, leading to incorrect matching for subsequent attachment page uploads. To fix this, the `document_number` is no longer updated during a PDF upload for appellate courts that do not use numbers.
- The second change addresses RDs where their document numbers were already scrambled by PDF uploads during attachment page merging. If an RD cannot be matched using the `document_number`, during the fallback lookup if the RD belongs to an appellate court that does not use numbers, the `document_number` is removed from the lookup. Finally, the …

4966 Avoid updating the RD document number upon PDF uploads in courts that don’t use document numbers

---

cl/recap/tasks.py
cl/recap/tests.py

This PR adds support for replicating PDFs from a Fetch API request.
The approach is similar to the one applied in #4979, where the document is purchased a single time, and then a PQ is created and processed for each RECAPDocument where the document needs to be replicated.
Fixes: #4827

4827 Replicate PDFs from Fetch API to subdockets

---

cl/citations/recap_citations.py

I didn't see that the do_resolve_citations function was also used in this function for recap, i had to remove citations with multiple matches

fix(citations): remove MULTIPLE_MATCHES_RESOURCE in recap_citations.py

---

cl/citations/tasks.py
cl/citations/tests.py

Solves #5098
- Check that fields that are expected to be non-null actually have a value
- Add tests with known fail cases

fix(store_unmatched_citations): improve validation

---

cl/lib/middleware.py

This PR refines `IncrementalNewTemplateMiddleware` to properly handle cached views, implementing the solution proposed in  https://github.com/freelawproject/courtlistener/issues/5034#issuecomment-2666311826
while investigating why cached instances of the `TemplateResponse` class lack the `template_name` attribute, I found an implementation for the [__getstate__](https://github.com/django/django/blob/86493307f97b9795a74227b6af2d59a267160847/django/template/response.py#L53-L67) method. This method, used for serialization and caching, is designed to store only rendered instances and their rendered data, _not_ the data used for response construction. This explains why cached instances are always rendered and lack the `template_name`.
Fixes #5034

fix(lib): Handles cached views in IncrementalNewTemplateMiddleware

---

cl/citations/match_citations_queries.py
cl/citations/tests.py
cl/citations/utils.py

Small typo assigned end year to start year
causes errors matching citations because
reporter years wont match reducing
elastic searches to zero
Fixes #5130

fix(citations): get_years_from_reporter

---

cl/settings/third_party/rest_framework.py
cl/simple_pages/templates/faq.html
cl/simple_pages/views.py

In #5135, I identified that the FAQ page can no longer populate its cache because the DB just can't do counts fast enough. 
This PR is a hot fix to simply remove that logic until we can do it with Elastic.

Remove specific stats on FAQ page

---

cl/scrapers/management/commands/cl_scrape_opinions.py

Related to #5138 and https://github.com/freelawproject/juriscraper/issues/1323
scrape_court now handles  juriscraper.lib.InvalidDocumentError

fix(cl_scrape_opinions): handle juriscraper.lib.InvalidDocumentError

---

cl/opinion_page/templates/opinions.html

This small PR update the tabs of opinions page. It removes the abbreviations and stack the tab items for mobile.
Full version:
Mobile version:

fix(opinions): update tabs of opinions page

---

cl/api/templates/case-law-api-docs-vlatest.html

The documentation has been updated to indicate that the citations field is part of the Cluster API, not the Opinion API. This change ensures users can correctly find citation data within the Cluster object.

fix(help): update opinion and cluster endpoint documentation

---

cl/recap/mergers.py
cl/recap/tests/tests.py

As outlined in #5058, this PR adds a safeguard to the `find_docket_object` method to prevent lookups with blank docket_number_core values, which can occur in cases such as:
- The parser fails and returns a blank docket_number.
- The `docket_number` is not recognized, and no `docket_number_core` is returned.
In these cases, the `docket_number` core lookups are omitted. 
Previously, these lookups included:
```
if pacer_case_id:
pacer_case_id + docket_number_core
"pacer_case_id": None + docket_number_core
"pacer_case_id": pacer_case_id
```
Now, if docket_number_core is blank, the first two queries involving `docket_number_core` are omitted, and only the query `"pacer_case_id": pacer_case_id` is preserved.
This should help avoid incorrect matches, especially if there are dockets in the …

5058 Avoid doing lookups with blank docket_number_core

---

cl/corpus_importer/management/commands/probe_iquery_pages_daemon.py
cl/corpus_importer/management/commands/ready_mix_cases_project.py
cl/corpus_importer/signals.py
cl/corpus_importer/utils.py

As detailed in https://github.com/freelawproject/infrastructure/issues/208#issuecomment-2698976819 this PR introduces a new method, `get_iquery_pacer_courts_to_scrape`, which centralizes the court lookup used by all components of the iquery scrape.
It includes all `district_or_bankruptcy_pacer_courts` that are currently in use.

Introduced get_iquery_pacer_courts_to_scrape to standardize courts for iquery scraping

---

cl/favorites/tests.py
cl/favorites/utils.py

This PR refines the `get_user_prayers` helper method to avoid including duplicate documents in the query. Unit tests have been added to prevent future regressions.
Fixes #5211

fix(favorites): Refines get_user_prayers to eliminate duplicates

---

cl/search/management/commands/cl_index_parent_and_child_docs.py
cl/search/management/commands/cl_re_index_rds_sealed.py
cl/search/management/commands/fix_rd_broken_links.py
cl/search/management/commands/sweep_indexer.py
cl/search/tasks.py
cl/search/tests/tests_es_opinion.py
cl/search/tests/tests_es_recap.py

In this PR, I've applied the following changes:
- Tweaked the `fix_rd_broken_links` command to schedule the re-indexing of chunks of `RECAPDocuments` that need to be fixed instead of chunks of `Dockets`. This ensures that every Celery task processes the same number of documents requiring re-indexing. The previous approach was based on `docket_ids`, but since the number of RDs in a docket can vary significantly, some tasks could take much longer to process than others. In this way, it'll be easier to adjust the `chunk_size` and `interval` parameters to distribute the load over time.
- Renamed the `testing_mode` parameter in `index_documents_in_bulk_from_queryset` to `use_streaming_bulk`. Previously, `streaming_bulk` was used only for testing, but since it will now be used in production, …

Updated fixer links command to use streaming_bulk

---

cl/search/management/commands/fix_rd_broken_links.py

Regarding the timeout encountered when running this command last time: https://github.com/freelawproject/infrastructure/issues/293#issuecomment-2702421454
The problem arises from the large number of `docket_ids` passed to the `RECAPDocument` query.
Since this command has now been modified to re-index `RECAPDocuments` in fixed chunks per task, we need to retrieve the `RECAPDocuments` that require fixing.
Initially, I thought that performing a subquery with the `docket_ids` retrieved in the previous step to fetch the `RECAPDocuments` that need to be fixed would not be too heavy, since we have indexes on `DocketEntry` and `Docket` for the pks required in this join query:
`RECAPDocument.objects.filter(docket_entry__docket_id__in=Subquery(docket_ids_to_fix))`
However, it timed out.
So I tested …

Refactor fix_rd_broken_links to prevent the DB query from timing out

---

cl/stats/urls.py
cl/stats/views.py

This PR fixes #5259 by moving the Elasticsearch health check logic from `/health-check` to a dedicated `/elasticsearch-status` endpoint.

feat(stats): Updates health check endpoint

---

cl/recap/tasks.py
cl/recap/tests/tests.py

This PR fixes: #5084 
The issue here is that `fetch_pacer_doc_by_rd` is a `transaction.atomic` task, so all DB operations within the task are transactional. Since the `replicate_fq_pdf_to_subdocket_rds` task is called within the main task, it is possible for the task to be executed before the PQs created to handle the subdocket replication content are committed to the database, making them unreachable for the `replicate_fq_pdf_to_subdocket_rds` task in case this task is processed before the transaction is committed.
To address this issue, the `replicate_fq_pdf_to_subdocket_rds` task is now wrapped within `transaction.on_commit` to ensure it is executed only after the transaction has been committed.
I also noticed that a similar issue could occur with recap email content replication, even …

5084 Wait for transaction to be committed before triggering subdocket replication

---

docker/django/docker-entrypoint.sh

In prod, we're constantly seeing our python pods using more and more memory. They've got 9 workers each, and yet they are using 5.5GB of memory and then resetting. This seems kind of crazy, so I'm going to try this setting to make them automatically restart.
I did a quick look around the internet, and it seems like 1000 requests before a reset is fairly normal. The jitter will help so all workers don't reset at the same time.
I'm hopeful this will make the pods stay up more reliably because right now they run out of memory and reset fairly regularly, making the site less reliable.

Add max-requests and max-requests-jitter to gunicorn

---

README.md
cl/favorites/templates/top_prayers.html
cl/favorites/utils.py

On average, PACER docs cost about 91¢, so it was bugging me that the
estimate in the header was so far from reality. I realized we can keep
it accurate by saying it's "about" some value, and then using the
average price of PACER docs instead of the minimum price.

Update the P&P header to be more accurate

---

cl/assets/static-global/css/opinions.css
cl/opinion_page/templates/includes/opinion_tabs_content.html
cl/opinion_page/utils.py

- Standardize the fields displayed in authorities, cited by and similar cases tab: Date filed, status, court and citations
- Fix typo in build_related_clusters_query causing to not display citations in similar cases
- Increase font size for header and value in each result row in tabs
- Citations are only shown if they exist
Cited by:
Similar Cases:
Authorities:

Standardize fields shown in the cases listed in Cited By, Authorities, and Similar Cases 

---

cl/assets/static-global/css/override.css
cl/opinion_page/templates/includes/pray_and_pay_htmx/pray_button.html
cl/opinion_page/templates/recap_document.html

This PR fixes #5299 by implementing a two-row layout for the mobile version of `recap_document.html`.
Additionally, this PR fixes an issue with the pray button's size for logged-out users. Here's a screenshot showing the problem:

fix(opinion_page): Switch to two-row layout on mobile document page

---

cl/alerts/api_serializers.py
cl/alerts/tests/tests.py

This PR fixes #5083 by updating the validate method from the SearchAlertSerializer to allow patch requests.

fix(alerts): Tweaks the SearchAlertSerializer's validate method

---

cl/opinion_page/utils.py

Implement early return for es_related_case_count function when the cluster doesn't have opinions.
In the code of the funtion, we use a function to build an ES "more like this" query which requires a list of sub opinions pks.
There are clusters without opinions, for example:
http://www.courtlistener.com/opinion/3561702/go/
http://www.courtlistener.com/opinion/3560425/go/
http://www.courtlistener.com/opinion/3895596/go/
http://www.courtlistener.com/opinion/3310252/go/
This doesn't affect the other function used to estimate cited by count because it doesnt use a "more like this" query

Fix error when returning estimate count for similar cases tab

---

cl/corpus_importer/management/commands/probe_iquery_pages_daemon.py
cl/corpus_importer/tasks.py
cl/corpus_importer/tests.py

This PR fixes the iquery scraper tasks to be schedule brake seen in [COURTLISTENER-9N8](https://freelawproject.sentry.io/issues/6481726584/) 
`Tried to schedule more than 433 iquery pages to scrape for court insd; aborting to avoid Redis memory exhaustion.
`
After reviewing the logs, I found the problem. When the jitter reaches its maximum possible value of 16, the brake limit can be surpassed by one, triggering the brake.
For instance:
jitter = 16
`Iteration: 17`
previous_pacer_case_id = 352 + jitter = 368
previous offset: 368 <= 400
pacer_case_id_to_lookup: 352 + 32 + jitter = 400
`Iteration: 18`
previous_pacer_case_id = 368 + jitter = 400
previous offset: 400 <= 400
pacer_case_id_to_lookup: 368 + 32 + jitter = 432
When computing the number of tasks to schedule using the subtraction: …

Fixed iquery scraper probe stop condition

---

cl/assets/tailwind/fonts.css
cl/assets/tailwind/tailwind.config.js
cl/assets/templates/new_base.html
cl/simple_pages/templates/v2_help/index.html

Closes #5282 
All pages in the new design adhere to one of two layouts: constrained or full-width. All constrained content pages have the same max-width and paddings, so we introduce a new content wrapper block in the new base template to keep things DRY.
For pages with constrained width, content must be placed inside the `content` block same as before, but for pages without this max width, content must be placed inside the `content_wrapper` block. The old `content` block will be ignored in these cases as the `content_wrapper` will override the entire block.
As a POC, this PR includes an updated version of the help index page, using proper layout, but without header or footer.
```html
{% extends "new_base.html" %}
{% block content_wrapper %}
<div class="w-full">
</div>
{% endblock %}
``` …

feat(templates): new base template layout

---

cl/simple_pages/templates/v2_help/alert_help.html

Fixes an [uncaught error](https://freelawproject.sentry.io/issues/6527382496/events/328cef8de95f4fef86cab69b2480777f/) due to the empty paths in the new template added in #5342

fix(alert_help.html): use logo as placeholder to avoid empty path in img src

---

cl/lib/db_tools.py
cl/search/tasks.py

In https://github.com/freelawproject/courtlistener/issues/4623 we found that we also have `Docket` and `RECAPDocument` instances that do exist in the database but raise an `ObjectDoesNotExist` error in `get_instance_from_db`, even after the task is executed using `on_commit`.
To help debug this issue, we can log some data from the connection/transaction in case the `ObjectDoesNotExist` is raised to better understand what’s happening.
Since we're receiving a couple of events of this type each day, we should have more details about what’s going on soon.

Log get_instance_from_db DB connection/transaction details for debugging

---

cl/settings/project/microservices.py

This PR adds `INCEPTION_TIMEOUT` env var to easily tweak the inception timeout if it's required. 
Right now it defaults to 60 seconds.

Introduced INCEPTION_TIMEOUT env var

---

cl/favorites/tasks.py

This PR fixes #5377 by using the `map_cl_to_pacer_id` method to retrieve the appropriate `court_id` prior to invoking the juriscraper method.

fix(favorites): Map internal court_id to pacer court id

---

cl/favorites/admin.py

This PR adds the `PrayerAvailability` model to the admin panel, allowing us to track documents sealed by the `check_prayers` signal.
This PR fixes #5395

feat(favorites): Adds PrayerAvailability to the admin panel

---

cl/alerts/management/commands/cl_send_recap_alerts.py
cl/alerts/tests/tests_recap_alerts.py
cl/lib/elasticsearch_utils.py

This PR fixes #4698, which was being triggered when querying RECAP alerts involving party fields using the sweep approach.
The problem was that `ESRECAPSweepDocument` is an index that only contains RECAPDocument-level fields and is a plain index (it has no join field, which is required to query RECAPDocuments based on parent docket fields such as parties). This index is used to filter out alerts that only involve RECAPDocument fields from those that may also involve Docket fields. Since the main index includes Docket fields within RECAPDocuments, this step is necessary to determine when to include RECAPDocuments nested within the Alert results and to distinguish whether an alert is triggered by a RECAPDocument, a Docket, or both.
The solution was simpler than I initially thought, …

4698 Fixed issue with RECAP search alerts involving party fields

---

cl/favorites/tests.py
cl/favorites/utils.py
cl/lib/test_helpers.py
cl/simple_pages/templates/help/prayer_help.html

This PR is straightforward. It resolves #5383 by allowing Free Law Project members to make three times the daily requests as part of the pray-and-pay project as regular users, who are currently allotted five requests. Under the quota in this PR, FLP members should now be able to make 15 requests in a 24-hour period.
This form and any other webpage that lists benefits for FLP members will need to be updated after this PR is merged.
https://donate.free.law/forms/membership

feat(favorites): increase pray-and-pay quota for FLP members

---

cl/simple_pages/templates/help/coverage_recap.html

In this PR I've updated the `/help/coverage/recap/` to mention the iquery probe fruits:
___
**Free PACER content scraper**
Basic case metadata is freely available on PACER for all District and Bankruptcy cases. This includes details such as the case name, docket number, date filed, date of last filing, and date terminated.
For bankruptcy cases, additional information is available, including the assigned judge, bankruptcy chapter, date the plan was confirmed, and date the debtor was discharged.
We scrape these pages every five minutes for each court, ensuring that we collect basic metadata for all new District and Bankruptcy cases shortly after they are filed. This data can be used to trigger RECAP Search Alerts.
___
One question here: We plan to reduce the scrape cycle for courts to 5 …

5254 Updated RECAP Coverage help page to mention fruits of iquery scraper

---

cl/alerts/templates/docket_alert_email.html
cl/favorites/templates/prayer_email_unavailable.html
cl/opinion_page/templates/includes/de_list.html

Refines the text displayed on the button for accessing unavailable recap records on PACER.
This PR changes the button label from "Sealed on PACER" to "Unavailable on PACER" to provide a clearer and more user-friendly indication that the content cannot be accessed.

feat(templates): Update wording for sealed recap records button

---

cl/search/management/commands/generate_opinion_embeddings.py
cl/search/tests/test_generate_opinion_embeddings.py

Here are some tweaks to `generate_opinion_embeddings` command:
- Use --database when executing the initial queries for the command.
- Added additional logs.
- Set chunk_size to 1000 in the iterator. I believe `with_best_text` prevents the iterator from applying the default limit of 2000, so hopefully this helps.
- Renamed `--batch-size` to `--token-count`

Tweaks to the embedding generation command

---

cl/favorites/tasks.py
cl/favorites/tests.py
cl/tests/fakes.py

This PR enhances the `check_prayer_pacer` task to more robustly handle responses when checking prayer availability. Specifically, it now explicitly checks if the response is a PDF document.
Previously, the task might have incorrectly flagged a prayer as unavailable if a PDF was returned directly (without the usual download confirmation page), as this PDF content is not a valid page for parsing. This update ensures that a PDF response is no longer treated as an indication of unavailability.
Here's the [code](https://github.com/freelawproject/juriscraper/blob/2c7a9014a96707623635002461f52fba23c0de22/juriscraper/pacer/download_confirmation_page.py#L49-L53) from Juriscraper that marks pdf responses as invalid: 
```python
if is_pdf(self.response):
self.is_valid = False
return
```

feat(favorites): Improve prayer availability check for PDF responses

---

cl/search/tasks.py
cl/search/tests/test_generate_opinion_embeddings.py

This PR resolves the Redis memory issue encountered during the generation and saving of embeddings.
Previously, embeddings were being passed directly to the save task. Since `CELERY_RESULT_EXPIRES` was set to `60` minutes, these embeddings were accumulating in memory even after the task chain completed.
To prevent this, embeddings are now stored in the Redis cache, and only the cache key is passed to the save task. The cached embeddings are deleted after the saving process, and they have a 30-minute expiration time as a fallback in case the save task fails.
Additionally, extra logs were added to capture errors from Inception when the response is not a list of embeddings, as seen in [COURTLISTENER-9RM](https://freelawproject.sentry.io/issues/6546932324/). This will help us identify which …

Avoid passing embeddings to save_embeddings, pass a reference instead

---

cl/settings/__init__.py
cl/settings/project/users.py
cl/users/forms.py

We use a blocklist package on Python to block hundreds of domains from creating accounts, but the maintainer of that package won't update their list as aggressively as we need them to. 
This PR allows us to keep a list of domains to block in addition to theirs rather than try to get them to add things to theirs (they've been closing my PRs).
This should prevent new accounts with these domain names without blocking existing ones. I could also add this to the email update form and the login form, but I'm hoping that isn't necessary.

feat(users): Add domain block list

---

cl/favorites/signals.py
cl/favorites/tests.py

This PR fixes #5386. From that issue:
> This is related to cl/favorites/signals.py and cl/favorites/tasks.py.
> Currently, we have created a de facto cache of only checking whether a currently unavailable document has since become available. These checks are limited to once a week.
> However, we've done nothing for the opposite case: we continuously check whether a requested document known to be available remains available. This seems like a waste of resources. I think we should only do one check for a document known to be available. Available documents rarely become unavailable. The most common case is when a court strikes a filing for violating the rules, but I don't think we need to focus on that situation. You may think that this is a minor issue because available documents will be …

fix(favorites): limit PACER crawls for available documents

---

cl/donate/models.py
cl/donate/tests.py

This PR fixes the `is_active` check to correctly handle memberships on their termination date.  By comparing only the date portion of the termination date and current time, we ensure that memberships are valid until the end of the day on which they terminate.
Fixes #5425

fix(donate): Tweak logic to check active status on termination date

---

cl/favorites/utils.py
cl/simple_pages/templates/help/prayer_help.html

This PR resolves #5436. While the existing code is not a bug per se, I don't think it is functioning as intended. It seems like it will confuse users to sort by both date and time if only the date is publicly visible to them.

fix(favorites): only sort by date of last_checked in get_top_prayers (not time as well)

---

cl/citations/tasks.py

Fixes #5505
Fixes a bug introduced in #5481 where the default queue for the task index_related_cites_fields was set to "celery" instead of "settings.CELERY_ETL_TASK_QUEUE" when the task is not called by the find_citations command

fix(citations.tasks): correct default queue for index_related_cites_fields

---

cl/alerts/templates/alert_email_es.html
cl/alerts/templates/alert_email_es.txt
cl/alerts/tests/tests_recap_alerts.py

This is a simple tweak to the RECAP alerts email template, as described in #4746, so that the case name link includes the `order_by=desc` parameter. This ensures the entries on the docket page are displayed in reverse chronological order.

4746 Display docket entries in reverse chronological order for the case name link within a RECAP Search Alert

---

cl/settings/django.py
cl/settings/project/security.py

I spotted this system check warning when running tests:
```
WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.
```
This comes from django-debug-toolbar, indicating that the app is installed but the middleware isn’t.
This PR refactors the settings files to remove the `debug_toolbar` app during tests, which avoids it triggering the warning. It should also speed up tests a bit since the debug toolbar tracking won’t be installed, although I haven't benchmarked that.

fix(tests): Avoid enabling django-debug-toolbar during tests

---

.github/workflows/docker-build.yml
.github/workflows/tests.yml
docker/django/docker-entrypoint.sh

Tidy up invocations of either `python manage.py` or `python /opt/courtlistener/manage.py` to just `./manage.py`. This change is possible because `manage.py` is executable with a correct shebang, and Docker has a `WORKDIR` set to `/opt/courtlistener`.

refactor: Run manage.py directly

---

cl/alerts/templates/docket_alert_email.html
cl/alerts/templates/docket_alert_email.txt
cl/recap/tests/test_recap_email.py

This PR fixes #5522
In Docket Alert emails, a link to the Main Document or Attachment page (depending on the document type) has been added.
Additionally, for minute entries without a document number, a link to the minute entry has been included, e.g:
`https://www.courtlistener.com/docket/68842149/frederick-v-apple/#minute-entry-393264842`
**Numbered document:**
**Minute Entry:**
The `None` link points to the minute entry in the docket page.
**Numbered entry, the link `View Document in CourtListener` has been added:**
```
**************************
CourtListener Docket Alert
**************************
1 New Entry in WSOU Investments LLC v. Google LLC (6:20-cv-00580)
Thirteenth circuit for the Zoo
~~~
View Docket: https://www.courtlistener.com/docket/100/wsou-investments-llc-v-google-llc/?or …
```

5379 Add document page link in Docket Alerts

---

cl/favorites/signals.py
cl/favorites/tasks.py
cl/favorites/tests.py
cl/favorites/utils.py
cl/search/signals.py

Minor modification to `send_prayer_emails` in `cl/favorites/utils.py`.
In `cl/favorites/tasks.py`, we already make sure to mark documents as not sealed if we discover they are available for purchase, but that function is only called when someone requests a document as part of the pray-and-pay project. Now, if someone goes directly to PACER to purchase a document and the RECAP extension uploads it to the repository, we confirm that it is not sealed and deletes any corresponding rows from the `PrayerAvailability` model.
I wasn't sure if this belonged here or in `handle_recap_doc_change` in `cl/search/signals.py`.
Edit: one question I have is whether it's possible for a particular RECAPDocument to be marked as `is_available = True` and `is_sealed = True`. Those two statuses seem …

fix(favorites): make sure granted prayers aren't marked as sealed

---

cl/donate/admin.py

This PR enhances the `NeonWebhookEventAdmin` class by displaying the creation date of webhook event records in the Django admin panel.
This change enhances the admin interface by providing more context for debugging and understanding the lifecycle of webhook events.

feat(donate): Adds creation date for NeonWebhookEvent in admin panel

---

cl/api/webhooks.py
cl/settings/project/security.py

Added the `WEBHOOK_EGRESS_PROXY_HOSTS` environment variable to define the list of IPs used to handle webhook requests.
Before merging this, we must set the `WEBHOOK_EGRESS_PROXY_HOSTS` environment variable to the current value of EGRESS_PROXY_HOSTS.

Introduced WEBHOOK_EGRESS_PROXY_HOSTS env var

---

cl/corpus_importer/management/commands/harvard_opinions.py
cl/corpus_importer/management/commands/import_tn.py
cl/corpus_importer/tasks.py
cl/lib/elasticsearch_utils.py
cl/lib/pacer.py
cl/opinion_page/forms.py
cl/recap/mergers.py
cl/recap/tasks.py
cl/recap_rss/tasks.py
cl/scrapers/tasks.py
cl/search/factories.py
cl/search/management/commands/generate_cap_crosswalk.py
cl/search/management/commands/import_harvard_pdfs.py
cl/search/tasks.py
cl/users/email_handlers.py
cl/users/tests.py
pyproject.toml

Follow-up to mistake highlighted in https://github.com/freelawproject/courtlistener/pull/5543#discussion_r2082451452 . Enable Ruff's [`flake8-logging-format` derived rules](https://docs.astral.sh/ruff/rules/#flake8-logging-format-g), of which G004 / logging-f-string relates to the previous discussion, preventing pre-formatted log messages.
There were ~150 violations, all fixed here.

chore: Enable Ruff log format rules

---

cl/settings/project/corpus_importer.py

Following up https://github.com/freelawproject/infrastructure/issues/208#issuecomment-2845671123 
I reviewed latests events from https://freelawproject.sentry.io/issues/6569345047/ to identify which courts need to be added to `IQUERY_EMPTY_PROBES_LIMIT_HOURS`. This ensures that the error `Court {court_id} has accumulated many probe attempts over approximately {} hours. It appears the probe may be stuck; manual intervention may be required` is customized for these courts and not triggered too frequently.
To do that, I reviewed the gaps in the latest cases published for these courts:
**gub**
April 24th, 2025
April 22nd, 2025
March 10th, 2025
March 6th, 2025
February 21st, 2025
In this case, the largest gap is between March 10th, 2025 and April 22nd, 2025 (43 days), so setting a limit of 45 …

Added additional courts to IQUERY_EMPTY_PROBES_LIMIT_HOURS

---

cl/simple_pages/templates/help/alert_help.html
cl/simple_pages/templates/v2_help/alert_help.html
cl/simple_pages/views.py
cl/users/templates/profile/alerts.html

Fixes: #1234, this PR includes two updates:
- On the `/profile/alerts/` page, the header has been updated to:
`Search Alerts for Case Law, RECAP, and Oral Arguments`
- The help page has been updated with the latest information regarding RECAP alerts:
- I've also added a section documenting some current limitations of RECAP search alerts, specifically those related to Percolator limits and the sweep index workaround, as well as issues with queries that combine party fields and filing-level fields.
I believe we'll need to update some screenshots and documentation once [#5126](https://github.com/freelawproject/courtlistener/issues/5126) is complete. I'll take care of updating it.
Besides that, is there anything else you think should be mentioned here?
I've also updated the help page v2 for …

1234 Improved Search Alerts help page for RECAP Alerts

---

cl/citations/tests.py

PR creates small tweak to test to match updated eyecite reference matching standard. 
A pincite must be followed by an ending punctuation to avoid capturing the start of the next citation.  Previously we did not enforce this with reference citation pincite matches.  
```
(?=
[,.;)\]\\]|  # ending punctuation
\ ?[(\[]|    # space and start of parens
$            # end of text
)
```

Update eyecite reference test

---

cl/corpus_importer/tests.py

This PR addresses an issue in the `test_can_retrieve_old_prayers_to_check` test. The test was giving inconsistent results because it depended on the current date. To make sure the test runs the same way every time and gives reliable results, this PR updates the code to use a fixed mock date instead of the real-time date.
This issue is affecting PR #5583 and #5571.

test(pray-and-pay): Fixes flaky test using a mock date

---

cl/assets/static-global/js/alpine/composables/clipboard.js
cl/assets/templates/cotton/code.html
cl/assets/templates/cotton/copy_to_clipboard.html
cl/assets/templates/cotton/data_table.html
cl/custom_filters/templatetags/text_filters.py
cl/simple_pages/templates/components.html

Closes #4739 
This PR introduces:
- two new components: data table and copy-to-clipboard.
- a new Alpine composable to provide JS to copy to clipboard.
- a new template tag filter to escape quotation marks, so we can safely pass text as HTML attributes without breaking syntax.
The `code` component was extended to include the new `copy-to-clipboard` in the top right corner. This has a flag to disable the button if needed.
<details>
<summary>Data table</summary>
</details>
<details>
<summary>Copy to clipboard</summary>
</details>
<details>
<summary>Updated code block</summary>
</details>

feat(components): introduce data table and copy-to-clipboard components

---

cl/opinion_page/sitemap.py

This PR optimizes the generation of large-sitemap index page. It replaces the [`get_latest_lastmod`](https://github.com/django/django/blob/0b2ed4f7c8396c8d9aa8428a40e6b25c31312889/django/contrib/sitemaps/__init__.py#L106-L115) method in the `DocketSitemap` class with a direct database query. This new logic retrieves the `last_modified` timestamp of the most recent record matching the items query, avoiding a full table scan.
This change should significantly reduce the load time of the  large-sitemap index page

feat(sitemap): Improve performance for large-sitemap index page

---

cl/users/signals.py

Follow up of https://github.com/freelawproject/courtlistener/pull/5592/
I noticed that the bounce events stored so far in S3 are not being saved in a directory based on the email address.
The issue is that it's common for the email address to appear as: `User Name <user@domain.com>` instead of just `user@domain.com`.
As a result, the captured email becomes an invalid directory name. To fix this, we need to normalize the email address before using it in the path.

Fixed path for storing bounce/complaint events

---

cl/search/api_views.py

Part of #5580
In a OpinionViewset, use a Prefetch object to get only the id of `opinion.opinions_cited` objects, instead of all opinion fields; since viewset only shows the opinions_cited as a list of hyperlinks 
May help reduce DB `IO:DataFileRead` as seen on RDS Performance Insights

fix(search.api_views.OpinionViewSet): Prefetch id only for opinions_cited

---

cl/alerts/forms.py
cl/api/templates/rest-docs-vlatest.html

This tweaks the alert modal to say "New" when selecting between new cases or filings:
This clarifies that the alert *will* trigger on documents even when you select only on cases. Otherwise, it's a bit confusing. You might think that selecting "notify on cases only" wouldn't find hits in the text of a document, but it will!

Add "new" to the RECAP Alert modal

---

cl/opinion_page/tests.py
cl/search/fields.py
cl/search/forms.py

This PR fixes https://freelawproject.sentry.io/issues/6631189163/ which has occurred only once. But it's a regression introduced in https://github.com/freelawproject/courtlistener/pull/5599 
While string-based relative dates are validated upstream, the modified fields are also used on the docket page to filter entries by date filed. In this context, a validation error is expected if an invalid date is provided as input, so that the form error can be displayed to the user.
To solve this issue, I decoupled the common logic and created a separate field to handle search fields and docket entry filter fields independently.

fix(search): Fixed entry date filed filter validation on the docket page

---

cl/assets/tailwind/input.css
cl/simple_pages/templates/cotton/terms_history.html
cl/simple_pages/templates/includes/terms_history.html
cl/simple_pages/templates/terms/18.html
cl/simple_pages/templates/terms/19.html
cl/simple_pages/templates/terms/latest.html
cl/simple_pages/templates/v2_help/alert_help.html
cl/simple_pages/templates/v2_help/coverage.html
cl/simple_pages/templates/v2_help/coverage_fds.html
cl/simple_pages/templates/v2_help/coverage_oa.html
cl/simple_pages/templates/v2_help/coverage_recap.html
cl/simple_pages/templates/v2_help/index.html
cl/simple_pages/templates/v2_help/markdown_help.html
cl/simple_pages/templates/v2_help/recap_email_help.html
cl/simple_pages/templates/v2_help/tags_help.html
cl/simple_pages/templates/v2_terms/latest.html
cl/simple_pages/views.py

Closes #5355 
This PR introduces:
- A new Terms History component heavily based off the `includes/terms_history.html` include.
- The redesigned version of the latest Terms and Policies.
- A fix for the notice about archived terms (old templates):
- v18 had the notice in a different place than the rest, so it was moved for consistency.
- v19 didn't have the notice so it was added.
Unlike the existing include, the new component tweaks the contents depending on whether it's in an archived version or the latest:
- In an archived version, the copy reads "Other versions of these policies..." and includes the link to the latest version.
- In the latest version, the copy reads "Earlier versions of these policies..." and it does not include the link to the latest version.
To identify the version, …

feat(simple_pages): add redesigned version of Terms and Policies page

---

cl/api/templates/alert-api-docs-vlatest.html
cl/api/templates/search-api-docs-vlatest.html
cl/search/templates/includes/calendar-and-relative-date-fields.html
cl/search/templates/includes/no_results.html
cl/simple_pages/templates/help/index.html
cl/simple_pages/templates/help/relative_dates_help.html
cl/simple_pages/templates/v2_help/index.html
cl/simple_pages/urls.py
cl/simple_pages/views.py

This PR solves: #5502 
It added a new help page for Relative dates:
It's linked from the RECAP Search home: 
In the RECAP search sidebar
In the relative dates error message:
In the Alerts API help page:
In the current index help:
In the new design index help:
Should I link it anywhere else?
This PR should wait to be merged until https://github.com/freelawproject/courtlistener/pull/5599 is merged.

5502 Added relative dates documentation

---

cl/recap/tests/test_recap_email.py
cl/recap/tests/tests.py

While reviewing https://github.com/freelawproject/courtlistener/pull/5628 I noticed a couple of transient test failures due to missing mocks.
This should resolve the issue.

Fixed flaky tests caused by missing mocks

---

docker/django/Dockerfile

The default was changed to 3 in apt 2.3.2 (2021): https://salsa.debian.org/apt-team/apt/-/blob/main/debian/changelog\#L1708-1711

chore(docker): Remove apt-get Retries option

---

cl/alerts/management/commands/cl_index_search_alerts.py
cl/alerts/tasks.py
cl/alerts/tests/tests.py
cl/search/documents.py

This PR applies a few tweaks to the `cl_index_search_alerts` command to support indexing of existing RECAP Alerts (types `r` and `d`). This allows us to re-index them into the new `recap_percolator_index` with the appropriate shard and replica settings.
To re-index all RECAP alerts, use the following command:
`docker exec -it cl-django python /opt/courtlistener/manage.py cl_index_search_alerts --pk-offset 0 --alert-type r --index-name recap_percolator_index`
Before running this command, we should create the `recap_percolator_index` in [ES](https://github.com/freelawproject/infrastructure/issues/362).

4635 Added support to index RECAP alerts to cl_index_search_alerts

---

cl/settings/third_party/rest_framework.py

User is hitting `/api/rest/v4/opinions/` constantly causing full table counts and high CPU usage, as seen  in RDS Performance Insights

fix(api): throttle user

---

cl/assets/static-global/css/override.css
cl/search/templates/includes/alert_modal.html

This PR refactors the HTML elements at the bottom of the alert modal, specifically for RECAP alerts. The goal is to prevent text from wrapping awkwardly onto a second line, particularly when the query matches a large number of hits.
Here's a screenshot of the alert modal with the refactor:

fix(search): Refines HTML layout in alert modal to fix text wrapping

---

cl/corpus_importer/management/commands/make_aws_manifest_files.py

This PR adds helper methods to create and run batch jobs immediately after a manifest file is created. This streamlines the workflow by triggering job execution as part of the manifest creation process.
Key changes: 
- Enhanced `upload_manifest` method: The S3 upload function now returns a tuple containing:
- The S3 ARN of the newly uploaded manifest file. 
- A dictionary with the uploaded file's S3 ETag and other relevant properties.
- Introduces `get_account_id` to reliably fetch the AWS account ID of the current execution role using AWS STS.
- Adds a new helper named `get_lambda_arns` to retrieve a dictionary mapping AWS Lambda function names to their ARNs.
- Introduces a new orchestration function named `create_and_execute_batch_job` to create and execute S3 Batch Operations jobs. …

feat(corpus_importer): Adds logic to create and execute batch jobs

---

cl/alerts/api_serializers.py
cl/alerts/models.py
cl/alerts/tests/tests.py
cl/api/templates/alert-api-docs-vlatest.html
cl/search/models.py

This PR adds support for saving case-only RECAP alerts via the Alerts API.
It makes the `alert_type` field optional for non-RECAP alerts and required for RECAP alerts.
The logic works by inspecting the alert type in the provided query string. If the type is `r` or `d`, it checks whether `alert_type` is also provided and whether it contains a valid value (`r` or `d`).
If `alert_type` is missing for a RECAP query, the following error is raised:
```
"alert_type": [
"Please provide an alert type for your RECAP search query. For notifications on cases only, use the d type. For notifications on both cases and filings, use the r type."
]
```
Or if the `alert_type` value does not match the type in the search query, for example, if a user provides `oa` for a RECAP query, the following error is …

5624 Added support for saving case-only alerts via the Search Alerts API

---

cl/favorites/tests.py
cl/favorites/utils.py

This PR updates the `compute_prayer_total_cost` to round the aggregated `price__sum` to one decimal place, enhancing readability and consistency in cost presentation.
Implements the suggestion from https://github.com/freelawproject/courtlistener/issues/5646
This tweak will affect the total cost of granted and pending prayers.

feat(prayers): Rounds prayers total cost to one decimal place

---

cl/simple_pages/tests.py
cl/stats/urls.py
cl/stats/views.py

Fixes #5691. 
Also adds tests for a few other monitoring URLs that had no coverage (others remain uncovered, but they're harder).

5691 heatbeat endpoint 2025 06 06

---

cl/api/tests.py
cl/api/utils.py
cl/search/api_views.py

Introduces `NoFilterCacheListMixin` to improve performance of list endpoints by caching responses when there's **no pagination** and either **a count** is specifically requested **or** **no filters** are applied to the queryset. This prevents repeated database queries for frequently accessed unfiltered data, reducing load and speeding up response times.
The mixin first determines if caching is applicable, checking for the absence of pagination and the presence of either a count request or no active filters. If eligible, it attempts to retrieve the response from db_cache; a hit returns the cached data immediately. Otherwise, the generated response is added to the cache via a `post-render` callback.
This new mixin class will cache requests that meet the following criteria:
- Requests with …

feat(api): Adds `NoFilterCacheListMixin` for caching unfiltered list of results

---

docker/django/docker-entrypoint.sh

As our traffic has gone up and as we've added workers to gunicorn, we're having the problem that restarting gunicorn all the time isn't great! Let's increase the default 10× and make it configurable in k8s via a variable.

fix(gunicorn): Increase max-requests

---

docker/django/docker-entrypoint.sh

Timeout: Setting this to zero causes requests to never time out. I think this could be the cause of our memory leak.
Max requests: 5000 is an unusually high default. We're using 2500 in prod.
Jitter: This should be some percentage of max requests, I guess, but 100 seems better than 50 from watching logs.

fix(gunicorn): Adjust parameters

---

cl/assets/tailwind/input.css
cl/assets/templates/cotton/header.html

Fixes #5717 
This was actually an easy fix! Alpine provides a directive exactly for this: [x-cloak](https://alpinejs.dev/directives/cloak).
This happens because the dropdowns are hidden by Alpine, so they are shown until Alpine has initialized. In slower connections, the effect can get much worse! Now we hide them by default, and Alpine removes the attributes once it's initialized.
To record both demos, I added "Regular 4G" throttle for the effect to be noticeable:
[Screencast from 06-11-2025 02:49:27 PM.webm](https://github.com/user-attachments/assets/de4e53b6-0daf-4d61-b199-c5dac6525971)
[Screencast from 06-11-2025 02:42:03 PM.webm](https://github.com/user-attachments/assets/b357ea3b-3ab7-4dea-9ded-1973f63778b8)

fix(new_header): avoid dropdown flash on load

---

cl/alerts/tasks.py

This PR adds a warning log when `send_or_schedule_search_alerts` exhausts its retries due to a `RECAPDocument.DoesNotExist` error, preventing the event from being sent to Sentry.

Avoid raising a RECAPDocument.DoesNotExist error after retries during alert trigger

---

cl/alerts/forms.py
cl/alerts/tests/tests.py
cl/assets/static-global/js/search-alerts.js
cl/search/templates/includes/alert_modal.html
cl/search/views.py

This PR solves #5750 
It uses the upgrade link for members: `https://donate.free.law/constituent/memberships/upgrade/{user_neon_id}`
when they reach their membership limits.
This applies for both the warning message and the form validation errors.
For non-members, it uses the regular membership link: `https://donate.free.law/forms/membership`

5750 Use Neon upgrade membership link for members

---

cl/api/templates/rest-docs-vlatest.html

Our docs were wrong. I think they were from an earlier time, but just not corrected.

Correctly document how to exclude fields from API responses

---

cl/api/tests.py
cl/api/utils.py

Introduces logic to explicitly prevent API responses from being cached when the request includes `fields` or `omit` query parameters.
Previously, responses containing dynamic field selection via `fields` or `omit` parameters could be cached. This led to inconsistent data being served from the cache, as different fields or omit configurations would retrieve the same cached response, potentially omitting or including data unexpectedly.
Fixes #5754

feat(api): Prevents caching responses with dynamic field selection

---

cl/simple_pages/templates/help/recap_email_help.html
cl/simple_pages/templates/v2_help/recap_email_help.html

This just clarifies why @recap.email doesn't "use up" a user's one-time links.
See #5778.

fix(simple_pages): clarifies @recap.email gets different "magic links"

---

cl/api/tests.py
cl/api/utils.py

This PR addresses a user-reported issue where `NoFilterCacheListMixin` was caching responses for `count=on` requests, even when filters were applied. This behavior led to incorrect counts being returned to users.

fix(api): Prevent caching count requests with filters.

---

cl/recap/tasks.py
cl/recap/tests/tests.py
cl/tests/utils.py

This commit adds logic to sort docket entries by document number for consistent ordering, matching the display order on the docket report.
Fixes https://github.com/freelawproject/courtlistener/issues/5731

feat(acms): Sort docket entries while processing uploads

---

cl/citations/tasks.py

While I say retry - it really is moving on to the next opinion to process.  And each time we fail we wait 60 seconds.  
Change it to 2 seconds and just move along with our day.  No need to hang for 60 seconds.

feat(citation.tasks): Speed up retry

---

cl/search/management/commands/cl_index_embeddings.py

The `cl_index_embeddings` command was failing with a connection error, possibly due to a read timeout. When Celery is handling a task, it waits before scheduling a new one. So if the connection remains open too long without requesting new bytes, it gets dropped.
Using a longer `read_timeout` parameter should help.
Also introduced TextIOWrapper for better handling of the text buffer.

Tweak cl_index_embeddings command to avoid boto timeouts

---

scripts/make_bulk_data.sh

Script last succeeded on April 30, 2025.
@mlissner observed this error on `apt install -y sudo`.
```
manual-run-cnk6m Installing utilities                                                                                               
manual-run-cnk6m                                                                                                                    
manual-run-cnk6m WARNING: apt does not have a stable CLI interface. Use with caution in scripts.                                    
manual-run-cnk6m                                                                                                                    
manual-run-cnk6m Reading package lists...                                                                                           
manual-run-cnk6m Building …
```

fix(bulk data): apt-get update before attempting apt-get install

---

cl/search/management/commands/cl_index_embeddings.py
cl/search/tasks.py

From the last run of the `cl_index_embeddings` command, I noticed that tasks were being scheduled too quickly, which can overwhelm Elasticsearch and Celery.
Celery throttling doesn’t seem to help in this case, since the batch queue has many workers available so tasks are executed almost instantly.
Therefore, it’s better to add a custom delay between each scheduled task to control the processing speed.
The default delay is one second between tasks.
`./manage.py cl_index_embeddings --delay 1 --indexing-queue batch2 --retrieval-queue batch3 --batch-size 5 --inventory-file embedding-csv/bf22253e-8d7f-49fb-9aa5-677e081d8384.csv --inventory-rows 2374114 --auto-resume`
I also included updating the `timestamp` during this process, as it can be useful for keeping track of the embeddings indexing.

Added --delay parameter to cl_index_embeddings command

---

cl/custom_filters/templatetags/extras.py
cl/users/templates/profile/alerts.html
cl/users/tests.py
cl/users/views.py

This changes the default ordering on the profile docket alerts page to be by most recent hit, incidentally removing the default ordering of alert creation time.
I had to make some changes to the template to enable a down arrow on a column even if there was no "order_by" parameter.  I think it's as small and elegant as I could make it.
Didn't see any tests to modify or add to.
If you don't accept this PR, I think you should cherry pick the fix for the sorting bug or I can submit a new PR.
This resolves https://github.com/freelawproject/courtlistener/issues/5714 and fixes https://github.com/freelawproject/courtlistener/issues/5713.

feat(alerts): Sort dockets on the Docket Alert page by last hit

---

cl/tests/runner.py

Using `--buffer` and `--parallel` can cause all test failure log messages, failed test stack traces, and all test results to be erased.  See Django bug [#36491](https://code.djangoproject.com/ticket/36491) for more details.  Until that is fixed and we've upgraded to it, we should use safe defaults.  I'm writing up a Discussion giving an example of how painful this makes test failures and I'll link it when finished.

fix(tests): Disable result buffering due to bug

---

cl/opinion_page/templates/includes/rd_metadata_headers.html
cl/opinion_page/views.py

Adds a new parameter to `view_docket` that allows direct linking to the docket page that contains the given docket entry.  This could be used by individuals, but it is primarily for the document page, which tries to link back to the docket entry in the docket and fails if the entry is not on the first page.  I named it `de`, but if you think it might be used elsewhere, we could call it `entry` or `docket_entry`. 
Updated the document template to use the new parameter.
Testing:
Manual testing so for against a docket with a [lot of entries](https://www.courtlistener.com/docket/59771301/in-re-google-rtb-consumer-privacy-litigation/).  If my approach is acceptable, I'll add some automated tests.
Resolves #5919.

Docket entry link

---

cl/assets/static-global/js/recap_dismissible_tooltip.js
cl/search/templates/search.html

Fixes #5949
The bug was introduced with the new [RECAP alerts tooltip](https://github.com/freelawproject/courtlistener/pull/5882/), because when a `<button>` element is inside a `<form>` and doesn't have a type, it has an implicit `type="submit"`. Thus, when hitting Enter in the input, the button caught the event and prevented the default behavior, so nothing happened. We now set an explicit `type="button"`, so the previous behavior is restored: we can now trigger the search by pressing Enter, and the close button doesn't submit the form at all.

fix(search_templates): prevent RECAP alerts tooltip close button from submitting the form

---

cl/users/tests.py

I can't figure out why this test would fail [like](https://github.com/freelawproject/courtlistener/actions/runs/16156761254/job/45600782427?pr=5930#step:17:3758) [this](https://github.com/freelawproject/courtlistener/actions/runs/16156761254/job/45600782427?pr=5930#step:17:4620).  By the time it gets to that subtest, it's already sorted by `date_last_hit` and `docket.case_name`, both ascending and descending.  So the objects being compared are the same and sorting correctly for those attributes.  At first I thought that I screwed up and the alerts were all getting the same court, leaving the order potentially to chance.  That would explain it usually passing.  But `DocketAlertWithParentsFactory` creates new Courts for each alert.  Then I thought maybe the Court ids were the same since …

test(users): adds info to test error message

---

cl/opinion_page/templates/opinions.html
cl/search/admin.py
cl/search/models.py

Fixes a minor bug that keeps some merged opinions from displaying correctly.
Now that opinion versions exist, we filter out
sub-opinions that are merged not main
(i.e., those not main_version set)
in the correct order

fix(search.models): Correct ordered_opinions

---

cl/corpus_importer/utils.py
cl/recap/mergers.py
cl/recap/tasks.py
cl/recap/tests/tests.py
cl/recap/utils.py
cl/tests/fakes.py

Key changes: 
- Introduces a new helper function that centralizes logic to determine whether a given `court_id` requires ACMS-specific handling
- Updates `purchase_appellate_docket_by_docket_number` to detect ACMS cases and switch to `ACMSDocketReport` when appropriate. Falls back to `AppellateDocketReport` for standard PACER courts.
- Tweaks `merge_pacer_docket_into_cl_docket` to save raw ACMS data as `.json` instead of `.html` (**ACMS** does not return a traditional **HTML** response)
- Adds `FakeAcmsCaseSearch`, `FakeAcmsDocketReport`, and related fakes for isolated ACMS test behavior.
Depends on #5938 and https://github.com/freelawproject/juriscraper/pull/1494
Fixes #5154

feat(recap): Enhances appellate docket purchase to support ACMS cases

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/docker-build.yml

Fixes: #5868
This PR adds deployment options to pull requests so that if the PRs have particular labels, certain parts of the deployment will be skipped. This should make deployments faster and more streamlined.
I developed these tweaks in a personal repo. You can see an example run here: 
https://github.com/mlissner/actions-test/actions/runs/16248353854
One thing that could be nicer, in theory, is that I'm checking using `contains()` instead of equality. Doing the latter seems to be really hard and not worth it, so I went with this compromise. It should be fine, so long a we don't make a label called `skip` or something like that.
This PR also adds a PR template to encourage the use of these labels. You're witnessing the first use of the template now.
1. The following labels control the …

Add deployment options

---

cl/recap/tasks.py
cl/settings/third_party/celery.py

This PR updates the `do_pacer_fetch` function to route PACER fetch tasks to a dedicated Celery queue, with the queue name now configurable via the new `CELERY_PACER_FETCH_QUEUE` setting. Additionally, it refactors the helper function to use Python’s `match-case` statement for clearer branching logic. 
Fixes #6008 
<details>
<summary>Instructions</summary>
---
The following labels control the deployment of this PR if they’re applied. Please choose which should be applied, then apply them to this PR:
| Label                 | Description                             | Use case                                                                                                                         |
| --------------------- | --------------------------------------- | …

refactor(pacer): rewrite do_pacer_fetch using match-case syntax

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/docker-build.yml

Fixes: #6009 
Context: freelawproject/infrastructure#410
This does three things in two commits. In the first commit:
1. It refactors our deployment script so that it's more modular, has better parallelism, and uses loops rather than repeated code.
2. It adds another deployment that can be skipped with the `skip-daemon-deploy` label, which I've created.
In the second commit: 
3. It updates the deployment script to deploy our new celery deployments created in https://github.com/freelawproject/kubernetes/pull/34. This is in the second commit.
This PR should not skip any steps so that we know it works properly.
It should not be deployed until freelawproject/infrastructure#410 is deployed.

Update deployment to do new celery deployments

---

.github/workflows/docker-build.yml

This is a fast-follow to https://github.com/freelawproject/courtlistener/pull/6010. I had a typo in there.

fix(ci): Use correct deployment names

---

cl/tests/providers.py

> I can't figure out why this test would fail [like](https://github.com/freelawproject/courtlistener/actions/runs/16156761254/job/45600782427?pr=5930#step:17:3758) [this](https://github.com/freelawproject/courtlistener/actions/runs/16156761254/job/45600782427?pr=5930#step:17:4620).
Good news, everybody!  Thanks to that [PR](https://github.com/freelawproject/courtlistener/pull/5933) that added more detailed debugging information leading to this very readable [failure](https://github.com/freelawproject/courtlistener/actions/runs/16360675735/job/46227845669#step:17:4630) on one of my other [PRs](https://github.com/freelawproject/courtlistener/pull/5867), I know exactly why this test is failing: 6.2% of the time, roughly 1 in 16, at least two of the three courts are getting the exact same …

fix(cl): fixed unrandom Court names

---

cl/corpus_importer/management/commands/upload_to_ia.py
cl/recap/management/commands/nightly_pacer_updates.py
cl/recap_rss/tasks.py
cl/settings/third_party/celery.py

Fixes: #6017
This decorates the feed tasks so that they always go to the `feeds` queue, which is established with a setting.

Use correct queue for feeds

---

cl/corpus_importer/management/commands/make_aws_manifest_files.py

Closes: [#417](https://github.com/freelawproject/infrastructure/issues/417)
This PR updates the filtering logic used to select RECAP records by removing the condition that excludes OCRed documents (`ocr_status != 1`).
This change aligns the filter with the logic used for estimating token counts across the full dataset and allows for a more comprehensive export if clients want to filter on `ocr_status` themselves.
<details>
<summary>Instructions</summary>
---
The following labels control the deployment of this PR if they’re applied. Please choose which should be applied, then apply them to this PR:
| Label                  | Description                             | Use case …

feat(aws_manifest): Removes ocr_status filter from recap queries

---

cl/users/forms.py
cl/users/tests.py

Fixes:  #5807
By default, the `ASCIIUsernameValidator` is not enabled in Django. This PR enables the `ASCIIUsernameValidator` in the user registration form `UserCreationFormExtended`, so the username only accepts ASCII characters, preventing the creation of homoglyph usernames.
Tests were added to prevent regressions related to this issue.
<details>
<summary>Instructions</summary>
---
The following labels control the deployment of this PR if they’re applied. Please choose which should be applied, then apply them to this PR:
| Label                  | Description                             | Use case                                                                                                                         |
|------------------------|-----------------------------------------|-- …

5807 Introduced ASCIIUsernameValidator to protect against homoglyph attacks

---

cl/api/templates/webhooks-docs-vlatest.html

Fixes: #5947
This PR fixes the Back to API Docs link on the latest Webhook docs page so it properly points to the V4 of the API.
It also updates other URLs in the curl examples that were previously linking to V3.

5947 Fixed API version links on the latest Webhook docs page

---

cl/alerts/management/commands/cl_send_recap_alerts.py

Fixes: #5948
This error log is related to the `get_task_status` method, which is used to track the progress of the daily re-indexing process in the sweep index. In this case, I believe the issue was caused by the ES cluster being busy and unable to respond to the request. However, this is not an essential query, as it’s only used to estimate how long to wait before checking the task progress again or to confirm that the re-indexing process has finished.
If the query fails, the implemented logic in `get_task_status` is to return an empty dictionary, so the estimated wait time remains the same as in the previous iteration. In this case, the wait was 2 minutes. On the next check, the process had already completed, and the sending process finished without any issues.
You can confirm this in …

5948 Log 'Error getting sweep alert index task status' as a warning

---

cl/api/tests.py
cl/corpus_importer/tests.py

Fixed some tests were deleting the `Court` objects that are installed by a migration and upon which other tests rely.
This makes progress on #5980, but doesn't resolve it.  But it does knock it down to 69 errors!  Nice!
```
----------------------------------------------------------------------
Ran 1530 tests in 316.306s
FAILED (failures=69, errors=2, skipped=53)
```
The `DRFCourtApiFilterTests` used factories to create Court objects, but it manually set the IDs to ones used by the migration fixture, so it started by deleting all Court objects.  This does not get rolled back by TestCase, so subsequent tests that rely on them will fail (I need to figure out if that is a Django bug and file it; I don't believe I came across an open one, but it seems like a big problem).  This seems to …

Fixes for tests that were clobbering migration data

---

cl/citations/unmatched_citations_utils.py

We can attempt the same unmatched citation
in the edge cases.  We could add queries to the db or just ignore the conflict here.
This fixes #6060 
Adds ignore_conflict flag to bulk create.

fix(unmatched_citations): Ignore conflict in unmatched citations

---

cl/assets/templates/base.html
cl/assets/templates/includes/dismissible_nav_banner.html
cl/simple_pages/templates/help/advanced_search.html

Closes #5823 
Closes #5822 
This PR introduces the changes required to launch the Oral Arguments Transcript feature 🎉 
- Extend the include for dismissible nav banners to enable color customization via a `variant` attribute that tweaks the classes applied to both the banner and the button. Accepted values are:
- `warning` (yellow)
- `info` (blue)
- `success` (green)
- `danger` (red, DEFAULT)
- Replace the RECAP Alerts banner with the new one announcing the OA Transcripts launch.
- Tweak the first paragraph of the Advanced Search help page to mention transcripts
⚠️ The waffle flag for the RECAP Alerts banner (`recap-alerts-home-banner`) should be removed _after_ this PR is merged.
<details>
<summary>OA Transcripts banner</summary>
</details>
<details>
<summary>Other …

feat(pages): introduce oa transcripts launch banner

---

cl/lib/elasticsearch_utils.py
cl/lib/test_helpers.py
cl/search/api_serializers.py
cl/search/api_utils.py
cl/search/api_views.py
cl/search/tests/tests_semantic_search_opinion.py

This PR improves the semantic search result handling by:
- Adding `inner_hits` to the nested KNN query to expose matched embedding chunks.
- Introducing a helper function to extract the max_score from `inner_hits` for semantic scoring.
- Extending the `MetaDataSerializer` to include a new "semantic" score alongside the existing BM25 score in API responses. This feature is controlled by the `enable_semantic_search` waffle flag introduced in #5899.
- Merging the top semantic chunk into each child document’s `_source["text"]` field for easier access and downstream consumption.
1. This PR doesn’t require any special deployment steps. However, in our recent meeting to enable the feature, we noticed that the `KNN_SIMILARITY` setting is restricting the number of returned …

feat(search): Enhances semantic search with inner_hits, scoring, and chunk merging

---

.github/PULL_REQUEST_TEMPLATE.md

Add a wiki link that explains in detail which pods are affected by each of the skip-deploy labels

fix(PULL_REQUEST_TEMPLATE.md): add wiki link for skip-deploy labels

---

cl/favorites/api_serializers.py
cl/opinion_page/templates/opinions.html
cl/opinion_page/views.py

Relates to https://github.com/freelawproject/courtlistener/issues/5943 but doesn't fully resolve it.
This PR introduces support for tracking view events of **Cluster** objects. It includes the following updates:
- Extends the label validation regex in `EventCountSerializer` to support `o.<id>:view` format, allowing view tracking for opinion clusters.
- Adds the `@track_view_counter` decorator to the `view_opinion` function to record person view events.
- Updates the `view_opinion.html` template to include an event counter placeholder in the "Cluster" button, displaying a loading spinner while the view count is fetched.

feat(opinion): Enables view tracking for opinion views

---

cl/opinion_page/templates/includes/rd_metadata_headers.html

#5771 added a cool new dropdown to the attachment page, but:
- It uses style attrs, which we usually avoid (though they don't matter *so* much anymore).
- The size of the text was really big
- The words could use a bit of cleanup to align with norms
This PR fixes these three little things by using a CSS class we already had, removing the style tags, and tweaking the language a bit.
<details open>
<summary><h4>Before</h4></summary>
</details>
<details open>
<summary><h4>After</h4></summary>
</details>

Remove style attrs and tweak words

---

cl/audio/views.py

Fixes #6113
This assumes the last `AudioTranscriptionMetadata` is the best one.
I checked both objects related to the audio that triggered the error in the dev DB, and the first one (id 1638) looked like this:
Whereas the last one (id 88337) looks like this:
So I guess last is best?
This fix prevents the error and displays the page properly, however **I could not get that audio to play at all** using the dev DB in my local machine, which I can do for other audios no problem. It seems [the file does not exist](https://dev-com-courtlistener-storage.s3.amazonaws.com/mp3/2024/03/07/vfs_leasing_co._v._markel_insurance_company_cl.mp3).

fix(oa_transcripts): prevent MultipleObjectsReturned error when fetching metadata

---

cl/opinion_page/templates/includes/rd_metadata_headers.html
cl/opinion_page/views.py

This PR fixes #6129 
Key changes: 
- This PR updates the `view_recap_authorities`  view that's attempting to access the response's `context` attribute, but it is raising an  `AttributeError` exception . This has been updated to use [context_data](https://docs.djangoproject.com/en/5.2/ref/template-response/#django.template.response.SimpleTemplateResponse.context_data), the correct way to access the template context according to the Django documentation.
- During the refactor in [#6125](https://github.com/.../pull/6125), a closing </div> tag was placed outside of a conditionally rendered block. This caused layout issues on the document details page when the block was not rendered. The fix ensures that the closing tag is only included when the block is present. Screenshots are included to …

fix(recap): Replaces undefined `context` attribute with `context_data`

---

cl/lib/elasticsearch_utils.py
cl/search/tests/tests_semantic_search_opinion.py

This fixes #6112 
This PR refactors the build_semantic_query method to simplify the keyword part of hybrid search queries. Previously, the keyword part of the query could target multiple fields. This PR narrows it to explicitly and only target the `text` field.

refactor(search): Narrows keyword matching in semantic queries to 'text' field

---

cl/search/selectors.py
cl/simple_pages/templates/faq.html
cl/simple_pages/views.py

This PR fixes #5135 
This PR introduces a helper function and makes several updates to the FAQ page, including a fix for formatting oral argument durations.
Key changes: 
- Adds a PostgreSQL based helper that estimates the number of `search_recapdocument` entries where `is_available = True`, using `pg_stats` and `pg_class`. This avoids full-table scans and improves performance for large datasets.
- Adds the estimated count to the FAQ view context and updates the template to display the total number in the FAQ section.
- Formats oral argument durations to display minutes with two decimal places for improved readability

feat(search): Estimate available document count using statistics

---

cl/lib/search_utils.py
cl/search/tests/tests_es_opinion.py

Fixes: #6154
This PR fixes the opinions count in the Home Page stats. The problem occurred when we moved from caching a Page object to caching ES hits in https://github.com/freelawproject/courtlistener/pull/5931
The previous Page object also stored the main total results, but the new approach only stores the ES hits for the Home Page latest results query.
To solve the issue, we now also cache the `main_total` count in the cache object. Backward compatibility code has been added to prevent errors during deployment, since the current cached object has a different format.
Once this is deployed, we can either wait six hours for the current cache to expire or clear it manually to see the fix earlier by using:
```
from django.core.cache import cache
cache.delete('homepage-data-o-es')
```
- …

6154 Added the total results count to the Opinions home page cached object

---

cl/opinion_page/templates/includes/de_list.html
cl/opinion_page/tests.py
cl/opinion_page/views.py

This PR fixes #6160. 
This PR enhances the CSV export functionality by requiring user authentication before allowing downloads.
Key changes: 
- Improves logic to handle dockets that has no entries, preventing errors during CSV creation
- Restricts downloading of docket entries CSV files to authenticated users for improved security.
- Updates the `de_list.html` template to display a “please log in” modal when an anonymous user clicks the Export CSV button.
Below is a GIF showing the Export CSV button in action, including the login prompt for anonymous users:

feat(docket): Requires User Authentication for CSV Exports

---

cl/donate/api_views.py
cl/donate/tests.py
cl/users/utils.py

This PR fixes #5935 
This PR updates the `MembershipWebhookViewSet` to include extra validation when creating EDU Memberships through incoming webhook events. The logic ensures that only users with confirmed .edu email addresses are eligible to receive this membership type.
Key changes: 
- EDU memberships are now conditionally created based on:
- The user’s email being confirmed (`email_confirmed = True`)
- The email domain ending in `.edu`
- Rejection emails are sent when users attempt to apply for EDU membership but don’t meet the requirements (e.g., unconfirmed or non-.edu emails).
Here's a screenshot of the rejection email sent to users who don't meet the requirements:
Currently, the rejection email is only sent to the user. Should we also notify Jenifer (or another team member) so …

feat(memberships): Adds validations for .edu accounts

---

cl/citations/management/commands/count_citations.py
cl/citations/tests.py

Solves #5706
OpinionCluster.citation_count can now be updated in batches of consecutive ids. This should prevent locking the whole table during the update
Add arguments to control behavior of batches
- start-cluster-id
- end-cluster-id
- step-size; default 10_000
Update tests
-------
Labelling this as `skip-*` because
- we intend to run it on the maintenace pods which we update manually
- doesn't affect any code used by the automated processes
--------------
The query now looks like below, with `start = 0` and `end = 10_000`
```sql
UPDATE "search_opinioncluster" 
SET "citation_count" = COALESCE(
(SELECT COUNT(U0."id") AS "total_count" 
FROM "search_opinionscited" U0 
INNER JOIN "search_opinion" U1 ON (U0."cited_opinion_id" = U1."id")
WHERE (U1."cluster_id" = ("search_opinioncluster"."id") …
```

fix(count_citations): citation_count update is now done in batches

---

cl/search/templates/v2_homepage.html

New homepage stats displays total estimate of opinions in our system but the copy says "number of precedential opinions". We remove the word "precedential" to better describe the datum.
</details>

fix(new_homepage): tweak copy to accurately describe the stat displayed

---

cl/citations/management/commands/count_citations.py

- Bug introduced in #6174 was preventing the command from being used
- remove nargs keyword from `--start-cluster-id` and `--end-cluster-id`

fix(count_citations): remove nargs from ids fields

---

cl/citations/management/commands/count_citations.py

Fixes a bug introduced in #6174
Was using raw input values `start_cluster_id` and `end_cluster_id`; instead of loop values `start_index`, `end_index`

fix(count_citations): use proper indexes in loop

---

cl/settings/third_party/rest_framework.py

This blocks a user that's non-responsive and using a lot of API.

feat(api): block user

---

cl/opinion_page/views.py

This PR adds bot detection to the update_opinion_tabs view. When the request comes from a known bot, we now skip the database lookups and return the opinion tabs template with an empty cluster.
- Crawlers like Bingbot were hitting the opinions page heavily.
- Each request triggered multiple DB queries, creating unnecessary load.
- By short-circuiting bot traffic, we reduce resource usage without affecting normal user experience.

fix(opinions): skip cluster lookup for bots in opinion tabs view

---

cl/opinion_page/templates/includes/opinion_tabs_content.html

This PR adds the `rel="nofollow"` attribute to the "Filter Similar Cases" link on the opinion page. 
This change ensures that crawlers know not to follow this link, without affecting its functionality for users.

fix(opinions): Adds `rel="nofollow"` to Filter Similar Cases link

---

cl/search/admin.py

I tried using the Opinion admin panel and it took forever to load, so this PR optimizes the Opinion admin panel by joining the clusters with `select_related`.
When testing with the dev DB, this reduced the number of DB queries from 103 to 3, and the time went from 20s to only 2. Still long, but a 10-fold improvement is not bad 🤷🏽 

feat(admin): optimize OpinionAdmin

---

cl/scrapers/management/commands/delete_duplicates.py
cl/scrapers/tests.py

Related to #4376
Allow grouping same hash duplicates from sources other than COURT_WEBSITE; which should help us target most of the remaining same hash duplicates
Tested command argument parsing with the following, and it works as expected
```
docker exec -it cl-django python /opt/courtlistener/manage.py delete_duplicates same_hash --cluster-sources Z
DEBUG 2025-08-19 12:36:02,551 (/opt/venv/lib/python3.13/site-packages/django/db/backends/utils.py debug_sql): "(0.097) SELECT COUNT(*) FROM (SELECT "search_opinion"."sha1" AS "col1" FROM "search_opinion" INNER JOIN "search_opinioncluster" ON ("search_opinion"."cluster_id" = "search_opinioncluster"."id") WHERE ("search_opinioncluster"."source" = 'Z' AND NOT ("search_opinion"."sha1" = '')) GROUP BY 1 HAVING COUNT("search_opinion"."sha1") >= 2) …
```

feat(delete_duplicates): add cluster-sources optional arg

---

cl/corpus_importer/management/commands/recap_into_opinions.py
cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py
cl/corpus_importer/tasks.py

Helps solve #6179
- introduce a second hash check in `recap_document_into_opinions`, just before object creation
- add a explicit hash check in the `recap_into_opinions` command, to prevent enqueuing the same hash multiple times in a same call
- introduce a random countdown to the chain in `scrape_pacer_free_opinions` (the ongoing process that calls `recap_document_into_opinions` ). This should help the hash checks work. A explicit hash deduplication (as for the `recap_into_opinions` command) cannot be done since the getting the pdf and the hash is part of chain, and no sha1 is available at the start of it

fix(recap_into_opinions): improve duplicated hash checks

---

cl/scrapers/management/commands/update_from_text.py
cl/scrapers/tasks.py
cl/scrapers/test_assets/test_opinion_scraper.py
cl/scrapers/tests.py

Solves #6137
- Modify `update_document_from_text` task to update or create OriginatingCourtInformation
- update `update_from_text` to handle OCI objects
- update `extract_doc_content` task to handle OCI objects
- update tests and test_opinion_scraper object

feat(update_from_text): now handles OriginatingCourtInformation

---

cl/search/utils.py

Number of minutes of Oral Arguments displayed in the Homepage was wrong.
After #6200 the number shown in the new homepage was no longer the number of minutes but the number of seconds. This happened because the expression read `seconds or 0 // 60` which yielded either `seconds` or `0 // 60`.
We now perform the calculation in the query itself, using `Coalesce` to prevent errors if no Audio rows exist.
<details open>
<summary><h4>Empty DB</h4></summary>
</details>
<details open>
<summary><h4>Dev DB</h4></summary>
</details>
<details open>
<summary><h4>Dev DB before this PR</h4></summary>
</details>
</details>

fix(new_homepage): handle empty queryset in DB when aggregating mins of OA

---

scripts/make_bulk_data.sh

This PR fixes #6256 
This PR updates our PostgreSQL setup to remove usage of the deprecated `apt-key` command, which is no longer available in Debian 13.
**Changes:**
- Removes use of `apt-key add` for importing the PostgreSQL key
- Adds keyring support under `/etc/apt/keyrings/postgresql.gpg` using `gpg --dearmor`
- Updates repo definition to use `signed-by` option

fix(bulk-data): Replaces `apt-key` with keyrings for PostgreSQL

---

cl/api/templates/bulk-data.html
cl/api/templates/v2_bulk-data.html

People often ask us if the bulk data files contain everything or only the newest stuff, so we're making it clearer that each file contains everything at the time of generation.
</details>

feat(help_pages): tweak bulk data docs to highlight that files are snapshots

---

cl/search/models.py
cl/simple_pages/coverage_utils.py

Solves https://github.com/freelawproject/courtlistener/issues/6239
Previously, when a court had data or descendants, and had no courthouse,
it would cause an error and the coverage page wouldn't load
with this PR:
- log a logger.error that will go to Sentry for someone to manually review it
- skip the court, so it doesn't break the page load
- add a signal to the Court model, that only works on prod and warns about a
new court needing a new courthouse

fix(coverage_utils): handle court with no courthouse

---

cl/lib/pacer_session.py

This PR fixes #5567
This PR updates `ProxyPacerSession` to override the `send()` method,  ensuring that all requests (including those triggered by redirects) are processed through `_change_protocol`. This replaces HTTPS with HTTP and relies on the `X-WhSentry-TLS` header to instruct Webhook Sentry to establish TLS with the target server.
I used case [25-12872](https://www.courtlistener.com/docket/71200951/yolanda-delgado-v-the-evangelical-lutheran-good-samaritan-society/) in my local environment to test login, docket purchase, attachment purchase, and PDF purchase.

fix(proxy): Override send() to enforce HTTP protocol for all requests

---

cl/simple_pages/templates/help/alert_help.html
cl/simple_pages/templates/v2_help/alert_help.html

Our webhooks are really cool and they're mentioned in the documentation here and there, but Eri pointed out that it'd be better if it were more prominent, so this accomplishes that.
We can skip deployment of this and let is land in another PR later. Seems OK to me! 
I should do some, but I don't have CL up and running and I just made these through the Github website. Hopefully you'll forgive me!

Add webhook link to top of alert docs

---

cl/citations/tasks.py
cl/citations/tests.py
cl/search/models.py

Fixes: #6350
This PR updates the authorities and aauthorities methods in OpinionCluster to ensure that a cluster is not returned as its own authority.
In addition, OpinionsCited objects are now only created when the citing and cited opinions belong to different clusters. This prevents unnecessary or invalid self-citations from being stored.

Exclude self cluster from authorities results
