freelawproject/courtlistener

cl/simple_pages/templates/terms/7.html

This PR, which addresses #432, adds a DMCA policy. This is needed because users will now be able to add their own content. I’ve added a new “Copyright policy” section to the terms page.

DMCA Policy

---

cl/search/management/commands/cl_dumpdata.py

Cleaned up the management command and added citations support. This should make it easier to extend to providing custom filter logic or model selection in an updated version.

Update to cl_dumpdata: added citations support, refactored

---

cl/opinion_page/templates/view_opinion.html

Update SCDB URL call

---

cl/api/templates/rest-docs-vlatest.html

From 01bbe7fc073893bee598405e53ee2e3ca60bad55 (for appellate).

rest-docs: history&appellate upload types

---

cl/opinion_page/tests.py
cl/opinion_page/urls.py
cl/opinion_page/views.py

Per #771.
Basically untested/WIP, needs review.
Needs tests (where should they go?)

Support /recap/ dockets.

---

cl/people_db/templates/view_person.html
cl/people_db/views.py

Add microdata to person pages

---

README.md

to make the developer guide more noticeable.

Add link to DEVELOPER.md in README

---

.circleci/Dockerfile
.circleci/activate.sh
.circleci/config.yml
.circleci/configure-courtlistener.sh
.circleci/configure-redis.sh

* cl/custom_filters/tests.py
* cl/stats/tests.py

circleci: run more tests during build

---

DEVELOPING.md

with instruction on how to update CircleCI test container.

docs: update DEVELOPING.md

---

cl/people_db/import_judges/judge_utils.py
cl/people_db/import_judges/populate_fjc_judges.py
cl/people_db/management/commands/cl_import_judges.py
cl/people_db/models.py

Updated to use FJC variable names and automatically include FJC as a source when uploading FJC CSVs.  Also a small tweak to date formatting (yyyy-mm-dd) so that they're read correctly when imported.

Import FJC updates.

---

cl/people_db/management/commands/cl_import_judges.py

Added "offset" and "limit" args to help review imports of FJC data.

feat($location):  add offset and limit args

---

cl/settings/10-public.py

Add if statement for Dev AWS settings

fix(public settings): Fix AWS DEV Settings

---

cl/cleanup/management/commands/fix_tax_court.py
cl/cleanup/tests.py

Fixed and improved testing for cleanup management command fix_tax_court

Improve testing and logging on Tax Court parsing.

---

cl/citations/find_citations.py
cl/citations/tests.py
cl/cleanup/management/commands/fix_tax_court.py
cl/cleanup/tests.py
cl/corpus_importer/court_regexes.py

Pull request fixes docket parsing (em-dash) bug, and citation parsing (return not continue) bug. 
It also includes updates to Testing for more patterns to catch future issues.

Cite docket parsing tc

---

cl/api/templates/includes/deprecated_sidebar_section.html
cl/api/templates/rest-docs-vlatest.html
cl/search/api_serializers.py

PR removes internal file path locations from the rest API

feat(api-serializer) Exclude local filepaths from rest API

---

cl/search/models.py

Add db_index to help expedite the import of the Harvard data

feat(search): Add db_index to filepath_json_harvard field

---

cl/search/migrations/0091_update_filepath_json_harvard.py
cl/search/migrations/0091_update_filepath_json_harvard.sql

Updated migration files for search to enable zero downtime while adding db_index=True to opinion cluster table

fix(migrations): Fix search db migration for conncurrent db_index(ing)

---

cl/corpus_importer/management/commands/harvard_opinions.py
cl/corpus_importer/tests.py

Simple fix to add partial date support for date_decisions when partial date is YYYY.

1142 partial harvard dates

---

cl/lib/search_utils.py
cl/opinion_page/views.py

1197 cache authorities for bots

---

cl/corpus_importer/management/commands/harvard_opinions.py
cl/search/models.py

Adds workaround to large docket numbers.  Adds docket numbers to Corrections field if too large for database model (unique together)

Fix large docket numbers

---

cl/api/urls.py
cl/api/views.py
cl/lib/search_utils.py
cl/search/templates/includes/alert_modal.html
cl/search/templates/search.html
cl/search/views.py

So far this only includes the server-side parts. JS parts up next.

230 alert frequency estimation

---

cl/corpus_importer/management/commands/harvard_opinions.py

Handle errors inside transactions during save

fix(harvard opinions): Handle errors inside transactions during save

---

cl/api/tests.py
cl/corpus_importer/tests.py
cl/people_db/api_serializers.py
cl/people_db/api_views.py
cl/search/fixtures/test_objects_query_counts.json

Add criminal charge data to the APIs 
Updates serializer for PartyType to include CriminalCount and CriminalComplaint

feat(api_serializers): #1212 Add criminal charge data to the APIs

---

cl/citations/tasks.py

This PR fixes/addresses issue #1224. However, it only implements changes 1-3 in that issue, not 4. These small tweaks should hopefully improve the performance of this code.

Issue 1224 improve citation increment logic

---

docker/courtlistener/docker-compose.yml

All mount points on the host machine should be configurable with environment variables.

Added environment variables for volumes

---

cl/recap/api_serializers.py
cl/recap/fixtures/canb_court.json
cl/recap/mergers.py
cl/recap/tasks.py
cl/recap/test_assets/claims_registry_empty.html
cl/recap/test_assets/claims_registry_njb.html
cl/recap/tests.py

1241 claims history recap endpoint

---

cl/alerts/templates/docket_alert_new.html
cl/alerts/urls.py
cl/alerts/views.py
cl/assets/templates/base.html
cl/opinion_page/static/js/docket_alerts.js
cl/opinion_page/templates/docket_tabs.html
cl/opinion_page/templates/includes/docket_alerts_button.html
cl/opinion_page/templates/includes/favorites_modal.html
cl/opinion_page/templates/includes/logged_out_modal.html
cl/opinion_page/templates/includes/rd_admin_tools.html
cl/opinion_page/templates/recap_document.html
cl/opinion_page/tests.py
cl/opinion_page/views.py

1253 docket alert endpoint

---

cl/assets/templates/base.html
cl/users/templates/register/logged_out.html

Adds User ID to Matomo tracking
See:
- https://matomo.org/docs/user-id/
- https://developer.matomo.org/guides/tracking-javascript-guide#user-id

Added setUserId to Matomo tracking

---

cl/recap/management/commands/pacer_iquery_scraper.py

Adds the option `--include-old-terminated`, can be called from cron when deployed

feat(iquery) add option to scrape old terminated cases

---

cl/recap/management/commands/pacer_iquery_scraper.py

Added the two remaining tasks from https://github.com/freelawproject/courtlistener/issues/1264#issuecomment-632220588

Added iquery tweaks 

---

cl/alerts/management/commands/handle_old_docket_alerts.py
cl/alerts/templates/emails/old_alert_email.html
cl/alerts/templates/emails/old_alert_email.txt
cl/alerts/templates/emails/old_email_subject.txt
cl/alerts/tests.py

1284 notify about alerts on old terminated cases

---

.github/workflows/tests.yml
DEVELOPING.md
cl/alerts/management/commands/handle_old_docket_alerts.py
cl/favorites/tests.py
cl/lib/date_time.py
cl/lib/tests.py
cl/people_db/views.py
cl/search/templates/homepage.html
cl/settings/10-public.py
cl/tests/test_visualizations.py
cl/visualizations/models.py
cl/visualizations/tests.py

1306 logging config

---

cl/corpus_importer/management/commands/import_tn.py

style(import_tn): Black code reformat after upgrade

---

cl/lib/search_utils.py
cl/opinion_page/templates/view_opinion.html
cl/opinion_page/views.py

This should help with #1406, but before deploying it we need to also
clear the cache of these items.

fix(caching): Stop getting and caching huge solr results

---

docker/nginx/docker-compose.yml

Fixes #1470
Add cl-ia-recap-uploader to nginx docker-compose
Add cl-scrape-rss to nginx docker-compose

feat(nginx/docker-compose): Add containers to handle supervisor scripts

---

cl/corpus_importer/management/commands/import_tn.py

Update argument type for import_tn to file.  
Argument was failing- perhaps removed in the py3 conversion.

Fix import tn

---

cl/assets/static-global/css/override.css
cl/assets/templates/base.html
cl/settings/10-public.py
cl/users/templates/profile/nav.html
cl/users/templates/profile/password_form.html
cl/users/templates/register/login.html
cl/users/templates/register/register.html
cl/users/tests.py
cl/users/utils.py

954 password validation

---

cl/users/views.py

fix(security): Nuke all sessions during account deletion

---

cl/visualizations/views.py

fix(viz): Allow visualizations to be embedded again

---

DEVELOPING.md

I got lost while following these instructions, and eventually set up a dev server by following the ['docker build and test' workflow](https://github.com/freelawproject/courtlistener/actions/runs/399656112/workflow), at @mlissner's advice. This rewrite incorporates that workflow.
Some things to note and/or change: The rewrite omits any discussion of the default values in 05-private.py, since they're already set. The rewrite also doesn't mention that it's possible to keep courtlistener-solr-server somewhere else by modifying courtlistener's docker-compose.yml.
Also, while I can confirm that this setup process worked for me, I don't know whether it causes other problems down the line. Someone more familiar with the software stack should probably double-check this.

streamline setup instructions in DEVELOPING.MD

---

cl/disclosures/admin.py
cl/disclosures/management/commands/import_financial_disclosures.py

PR provides fixes for financial disclosure extraction and importing project
Update admin for disclosures to show if description is blank
Split extraction to judicial watch and non judicial watch documents.

791 add disclosures app

---

cl/disclosures/management/commands/import_financial_disclosures.py
cl/scrapers/transformer_extractor_utils.py
cl/settings/10-public.py

This PR 
1) Fixes timeout issue in disclosure importer script.
2) Adds timeouts to BTE_URLS

Fix disclosure importer

---

cl/disclosures/management/commands/import_financial_disclosures.py
cl/disclosures/tasks.py
cl/disclosures/tests.py

PR makes the importation of financial disclosures a celery task.
Update model imports to avoid circular imports
Move importation code to tasks
Update tests for new imports.
Add queue and min-size parameters to command

Celerize financial disclosure importer

---

cl/disclosures/utils.py

PR Fixes - Fix on importer.
Check for False-y vs None

fix(disclosure.utils): Fix for false-y

---

.github/workflows/tests.yml
docker/courtlistener/docker-compose.yml

Build before tests

---

cl/alerts/views.py
cl/donate/views.py
cl/favorites/views.py
cl/lib/http.py
cl/opinion_page/views.py
cl/visualizations/views.py

1603 upgrade to django 3.1

---

cl/disclosures/tests.py
cl/simple_pages/templates/terms/10.html
cl/simple_pages/templates/terms/11.html
cl/simple_pages/templates/terms/12.html
cl/simple_pages/templates/terms/13.html
cl/simple_pages/templates/terms/2.html
cl/simple_pages/templates/terms/3.html
cl/simple_pages/templates/terms/4.html
cl/simple_pages/templates/terms/5.html
cl/simple_pages/templates/terms/6.html
cl/simple_pages/templates/terms/7.html
cl/simple_pages/templates/terms/8.html
cl/simple_pages/templates/terms/9.html

PR #1631 
This resolves two bugs, one for the disclosure testing.  
The second was a simple pages HTML path error.

1631 disclosure test failing

---

cl/scrapers/utils.py

Fixes: COURTLISTENER-1F2
Fixes: #1662

fix(scrapers): Add workaround for weird audio files

---

cl/api/urls.py
cl/api/utils.py
cl/recap/api_serializers.py
cl/recap/filters.py
cl/recap/migrations/0032_email_processing_queues.py
cl/recap/models.py
cl/recap/test_assets/recap_mail_receipt.json
cl/recap/tests.py
cl/recap/views.py
cl/users/migrations/0009_make_recap_email_user.py

* EmailProcessingQueueViewSet proposal.
* Validation in serializer.
* Model design.
* S3 upload from JSON text.
* Validation and creation tests.

Free look email handler

---

.github/workflows/tests.yml
cl/alerts/tests.py
cl/api/tests.py
cl/audio/tests.py
cl/citations/tests.py
cl/donate/tests.py
cl/favorites/tests.py
cl/lib/test_helpers.py
cl/opinion_page/tests.py
cl/scrapers/tests.py
cl/search/tests.py
cl/tests/test_feeds.py
cl/tests/test_issue412.py
cl/tests/test_visualizations.py
cl/users/tests.py

1684 parallel tests

---

cl/citations/match_citations.py
cl/citations/tests.py

Should fix #1683. This refactor is a bit overkill for the precise problem in that issue, but it foreshadows changes soon to be made that will bring the citator further in line with `eyecite`.

Issue 1683 fix antecedent guess

---

cl/opinion_page/templates/includes/rd_doc_search_button.html
cl/opinion_page/templates/includes/rd_download_button.html
cl/opinion_page/templates/includes/rd_metadata_headers.html
cl/opinion_page/templates/recap_document.html

feat(html): Add button for searching docs

---

cl/simple_pages/templates/help/delete_account_help.html
cl/users/templates/profile/delete.html
cl/users/views.py

fix(users): Properly disable donations and nuke tags

---

cl/citations/match_citations.py
cl/citations/tests.py
cl/lib/types.py

This should fix #1710 as to both Sentry errors. The newly-added tests reproduce those issues and fail without the included patch.

Issue 1710 fix no cluster error

---

DEVELOPING.md
cl/donate/templates/donate.html

Addresses further discussion in #975, should help make it clear to users that they are making a recurring donation.

Improve transparency with recurring donations

---

cl/corpus_importer/management/commands/harvard_opinions.py
cl/lib/string_diff.py
cl/scrapers/utils.py
poetry.lock

PR: 
Includes a medium updates to harvard importer.
Upped the matching text percentage to 60.
Add cosine similarity for case names - and compare against multiple case titles.
Deal with larger rote blocks of text 
And generally improve logging across the board.

Update harvard importer

---

cl/corpus_importer/management/commands/harvard_opinions.py

PR #1738 
PR fixes (atleast one) reason for slow Harvard Importer.

1738 slow importer

---

.github/workflows/tests.yml
cl/opinion_page/tests.py
cl/opinion_page/views.py

PR 
Fixes failing citations for our updates to citations.

Fix failing citation tests

---

cl/opinion_page/templates/volumes_for_reporter.html

PR Fixes layout bug found in volume reporter page for medium sized screens

fix(volumes_for_reporter): Fix layout for medium pages

---

cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py
cl/corpus_importer/tasks.py

Adds exception message to handle **ValueError** exception in task `get_and_save_free_document_report` and command `get_and_save_free_document_reports`.
Also, adds a default mesage for any othe exceptions in `get_and_save_free_document_reports`.
Closes: freelawproject/juriscraper#418

Added message for ValueError exception

---

cl/disclosures/migrations/0001_initial.py
cl/disclosures/models.py

Fixed Typo in the help_text of the page_number of investments in financial disclosures.

Fixed typo

---

cl/disclosures/tasks.py

Allow for seamless importation of nomination disclosures.
Add optional field in json file "report type"
to trigger uploading only without extraction

feat(disclosures): Add support for nomination disclosures

---

cl/search/templates/advanced.html
cl/simple_pages/templates/coverage.html
cl/simple_pages/templates/faq.html

feat(disclosures): Add Safari to CL pages

---

cl/corpus_importer/fixtures/court_test_asset.json
cl/corpus_importer/management/commands/harvard_opinions.py
cl/scrapers/management/commands/cl_scrape_opinions.py
docker/django/version.txt
docker/task-server/version.txt
poetry.lock
pyproject.toml

PR improves error logging and handling in Harvard Opinions
Fixes a potential bug in reporter-type extraction.
Bumps reporters-db

Improve error logging

---

cl/opinion_page/forms.py
cl/opinion_page/tests.py

PR Fixes #1876
Update citation field to citation
because we dropped neutral_citation
Add tests to validate citations on upload
Add warning logger if citations fail in future

fix(tenn): Fix tenn. uploader

---

cl/scrapers/management/commands/cl_back_scrape_opinions.py
cl/scrapers/management/commands/cl_scrape_opinions.py

Update backscraper docstrings/typing
Fix bug - overprocessing opinions
Update debug logging for help debugging on server

refactor(scraper/commands): Update scraper logging

---

cl/scrapers/management/commands/cl_scrape_opinions.py

feat(scraper): Add hack to tax court

---

cl/corpus_importer/management/commands/harvard_opinions.py

Add simple fixes to harvard opinions

feat(harvard): Integrate opinionated fixes

---

cl/citations/annotate_citations.py
cl/citations/fixtures/opinions_matching_citations.json
cl/citations/management/commands/cl_add_parallel_citations.py
cl/citations/match_citations.py
cl/citations/tests.py
cl/corpus_importer/import_columbia/populate_opinions.py
cl/corpus_importer/management/commands/anon_2020_import.py
cl/corpus_importer/management/commands/harvard_opinions.py
cl/corpus_importer/management/commands/update_scdb.py
cl/lib/search_utils.py
cl/lib/types.py
cl/scrapers/management/commands/cl_scrape_opinions.py
cl/search/models.py
poetry.lock
pyproject.toml

We never updated CL to reflect the API changes that were made in eyecite 2.2 and 2.3!

Upgrade to eyecite 2.3

---

cl/corpus_importer/management/commands/harvard_opinions.py

PR Fixes failing docker build and test that was created with an update to harvard opinion importer.

Fix failing harvard tests

---

cl/lib/argparse_types.py
cl/scrapers/management/commands/scrape_harvard_ia.py

Some volumes are large, added support for large volumes
split across multiple IA directories.

feat(scrape_harvard_ia): Add support for multiple volumes

---

cl/opinion_page/templates/includes/buy_pacer_modal.html

- Changed buttons position and color
- Add a recap archive link

fix(docket): Change style for recap modal buttons and add link to recap archive

---

cl/citations/description_score.py
cl/citations/tests.py

fix(parentheticals): Fix issue where citation_count=0 caused crash in description score

---

cl/disclosures/tasks.py
cl/scrapers/transformer_extractor_utils.py

Make errors in disclousre imports throw to sentry for
better debugging purposes
Additionally, we were not handling redis keys properly
when BTE failed in one instance.

fix(disclosures): Improve logging and failures

---

cl/disclosures/tasks.py

This is a small PR that fixes the import of financial
disclosures that are partially imported.
We were too sensitive and bailed out early.
Currently we are returning none if we find the
disclosure in the system or the page count fails
Neither should occur.
Also return page_count as int not bytes
although as you pointed out django handles it

fix(disclosure.tasks): Dont crash if we have partially processed FD

---

cl/search/tests.py

Added unit test coverage for opinion search operators

Advanced query operator test

---

poetry.lock
pyproject.toml

Adding dsl for django elasticsearch

Add django-elasticsearch-dsl package

---

cl/scrapers/utils.py

PR Fixes downed scrapers because of a bad micro service api call
More work is needed but this should help restart everything

fix(scrapers): Drop naked exception Fix Scrapers

---

docker/django/Dockerfile

Fixes #2021 
Dont reinstall poetry unless poetry changes
Move code COPYING behind poetry installation for development docker builds

refactor(dockerfile): Fix build speeds

---

cl/settings/django.py

feat(settings): Add replica DB

---

cl/simple_pages/templates/coverage_fds.html

Update FD coverage numbers from the latest import

feat(coverage_fds): Update 2019 and 2020 coverage page

---

cl/recap/management/commands/pacer_iquery_scraper.py

Fixes: 1393 by including tagged dockets in the iquery scraper.

1393 iquery tagged dockets

---

cl/people_db/models.py
cl/people_db/templates/financial_disclosures_viewer.html

Fix #2068 
Drop the Suffix handling for I (1)
Drop Numbers for Roman numerals

fix(disclosures/people): Fix Suffix handling

---

cl/recap/tasks.py

Increased retries from 3 to 5.

Increased retries for RECAP fetch tasks

---

cl/users/admin.py

Added raw ID key on stored_email field

Fixes FailedEmail admin

---

cl/corpus_importer/management/commands/import_patent.py

Adds a 1 second pause in pulling patent data
Adds better logging and fixes one bug.

feat(import): Improve patent import logging

---

poetry.lock
pyproject.toml

Bump Juriscraper to fix Michigan Supreme Court

feat(poetry): Update juriscraper

---

cl/scrapers/management/commands/scrape_harvard_ia.py

Adds backoff - for timeout errors with the IA scraper.

feat(ia): Add timeout backoff scaper

---

poetry.lock
pyproject.toml

feat(poetry): Bump juriscraper

---

cl/simple_pages/sitemap.py
cl/simple_pages/templates/help/index.html
cl/simple_pages/templates/help/recap_email_help.html

2248 fix recap dot email sign up instructions

---

cl/opinion_page/templates/docket_tabs.html
cl/opinion_page/templates/view_opinion.html
cl/settings/misc.py
cl/simple_pages/templates/help/alert_help.html
cl/simple_pages/templates/help/recap_email_help.html
cl/simple_pages/templates/robots.txt
cl/users/templates/register/login.html
cl/users/templates/register/register.html
scripts/make_bulk_data.sh

Just some small tweaks. These should be more correct than the last time I did a PR like this, because I tested each command in the terminal to make sure it works (hopefully no more typos!).

Remove BULK_DATA_DIR, update robots.txt, and add more bulk data types

---

.github/workflows/lint.yml
cl/lib/middleware.py

Seems that mypy isn't happy when trying to get the `private` context variable.
To solve it we just need to check before if `response.context_data` is set.

Fixes mypy issue on RobotsHeaderMiddleware

---

.github/dependabot.yml
cl/users/management/commands/cl_welcome_new_users.py
cl/users/tests.py
poetry.lock
pyproject.toml

This solves the welcome email issue described on #2313 related to time zones.

2313 Fix sending welcome email twice for some users.

---

cl/alerts/tasks.py

This fixes: #2327
Seems that two different users added the archive[arroba]recap.email address to the same case so we received the notification duplicated for the same user. This generated a race condition when creating the DocketAlert for archive[arroba]recap.email user.
Since we have a DB constraint the docket alert was not duplicated but the error was logged in Sentry.
So that, to avoid new similar errors I changed a bit the logic to check if a docket alert exists or if we need to create one for a user, using `select_for_update` and `transaction atomic` in order to create a lock and avoid the race condition.

Fixes race condition when creating a docket alert for a docket/case

---

cl/people_db/templates/view_person.html
cl/simple_pages/templates/robots.txt

2132 people display fixes

---

cl/people_db/templates/view_person.html

This is just a small fix to the people page to make sure it lays out correctly and links correctly.

2255 fix people page

---

cl/api/templates/webhooks-docs-vlatest.html
cl/users/templates/profile/webhooks_base.html

Here is the documentation for Search Alerts webhooks as I added in the Google doc.
Let me know if we need to add or modify something else.

2176 Added Search Alerts webhooks documentation

---

cl/api/templates/webhooks-docs-vlatest.html

feat(docs): Do better when lacking auth

---

cl/settings/third_party/rest_framework.py

Set throttle rate for me to perform tests, clone cases in local env(requires many requests to clone one case), etc.

Set throttle rate for user

---

cl/api/templates/docs.html
cl/api/templates/rest-docs-vlatest.html
cl/search/models.py

@ERosendo, this should fix the case ID issue and land a couple other little tweaks. Please review and if it looks good, hit the merge or auto-merge button. Thank you!

Recap 324 fix pacer url

---

cl/alerts/tests.py

Seems that the previous fix for this issue only worked until the month ended.
Now is failing again, this time due to something different. Since I mock the test date to day 15 when the tests are run on a day lower than 15, tests fail since the search query looks for items filed after the `cut-off` date so the items filed date and mock date didn't match.
In order to fix it I added the factory opinions creation under the mocked time.
This should be more reliable.

Fixes mock time for search alerts webhook failing tests

---

cl/alerts/templates/emails/old_alert_email.html
cl/alerts/templates/emails/old_alert_email.txt
cl/assets/static-global/css/override.css
cl/lib/model_helpers.py
cl/simple_pages/templates/help/tags_help.html

This just makes the docs a bit nicer for tagging and favorites, plus adds a couple little tweaks that have been in my change history.

Tweak tagging docs

---

cl/users/views.py

This will send it to Sentry instead, which is fine.
Fixes: #2450

fix(moosend): Don't log failing value, let it crash

---

cl/corpus_importer/management/commands/harvard_opinions.py

Update the harvard importer
Step one in the merger code 
Add and log the filepath json for the
associated opinions in the database

feat(harvard): Update Harvard importer

---

cl/api/templates/bulk-data.html
cl/api/templates/replication.html
cl/api/templates/webhooks-docs-vlatest.html
cl/api/templates/webhooks-getting-started.html
cl/simple_pages/templates/contribute.html
cl/simple_pages/templates/help/coverage.html
cl/simple_pages/templates/help/coverage_fds.html
cl/simple_pages/templates/help/delete_account_help.html
cl/simple_pages/templates/help/donation_help.html
cl/simple_pages/templates/help/recap_email_help.html
cl/simple_pages/templates/help/tags_help.html
cl/simple_pages/urls.py
cl/simple_pages/views.py
cl/users/views.py

Clean up and reformat help pages

---

cl/search/api_serializers.py

This PR adds the court_id to the `DocketSerializer` and resolves https://github.com/freelawproject/courtlistener/issues/2493.

feat(docket): Add court_id to the docket serializer

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml

This fixes the [broken pre-commit](https://results.pre-commit.ci/run/github/22257580/1675098199.C0T3FPU2Q76Wk1eJvU_kBw) action.
- `pre-commit` version updated
- `isort` updated in pre-commit  yaml

Fixes broken pre-commit action

---

cl/search/models.py

This PR adds a method to create the Appellate URL for cases related to the issue https://github.com/freelawproject/courtlistener/issues/2506

feat(docket): Add method to compute the Appellate URL using the caseNum

---

cl/api/templates/docs.html
cl/assets/static-global/css/override.css
cl/corpus_importer/management/commands/nywb_chapter_7.py
cl/opinion_page/templates/docket.html
cl/search/migrations/0011_add_event_tables_and_triggers.sql
cl/users/templates/emails/welcome_email.txt
cl/visualizations/static/js/scotus_map_new.js
docker/django/README.md

This is a bunch of little tweaks I've been saving + a few tweaks to a client script I'm about to run.

Little tweaks and client work

---

cl/favorites/views.py
cl/lib/pacer.py
cl/simple_pages/templates/help/recap_email_help.html

This fixes a small bug requested by a user on Mastodon, another requested via email, and refactors some code I found confusing.

Tweak order tags chronologically

---

cl/corpus_importer/management/commands/troller_bk.py
cl/corpus_importer/tests.py

- Log the last file processed into Redis
- Performance improvement by aborting the file when a cached item is hit.
The content of RSS files is usually the same in a large percentage from a previous file from the same court since they were crawled with a short time difference.
So that, RSS files have the following shape since they are in chronological order:
**w-DCCF03D3-BDBA-C444-1EA2D2D99D26D437-1399913590**
```
<title>2:12-bk-18537- FREDERICK CHARLES SCHROEDER and HEIDI KRISTINE SCHROEDER</title>
<title>4:09-ap-01072- SOVEREIGN v. Wells Fargo Financial National Bank, and is succes</title>
<title>2:13-bk-02150- SCOTTSDALE VENETIAN VILLAGE, LLC</title>
<title>2:14-bk-04069- TEMESGHEN EFREM</title>
```
**w-DCCF03D3-BDBA-C444-1EA2D2D99D26D437-1399916203**
```
<title>4:14-bk-05483- KAYLA R …
```

Troller BK performance improvement and log last file into Redis

---

cl/corpus_importer/management/commands/troller_bk.py

I profiled the memory usage of the importer specifically related to `Threads`.
Seems that there is not an actual memory leak, but there are certain conditions that affect memory usage.
- I removed a list that copied the set of threads and just ordered it in place, this is more memory efficient.
- In general, the garbage collector seems to work properly but sometimes it didn't clean memory as soon as a thread is completed, so now using the garbage collector to clean memory after each iteration, this is saving around 200MB in my tests from the peak memory.
- The memory seems to vary a lot depending on the number of threads that are running and the number of active threads depends on the download speed and the merging speed.  
There are two types of threads, a thread that starts a group of …

Improved Troller BK memory usage and safe KeyboardInterrupt

---

poetry.lock
pyproject.toml

Bump Juriscraper to 2.5.39 that fixes #2581

build(deps): bump juriscraper from 2.5.37 to 2.5.39

---

cl/api/tests.py
cl/api/utils.py

This PR adds support for tracking milestones for webhook events that have been successfully sent.
This feature is based on API milestones tracking, so the global count of successful webhook events sent and the event counter for every webhook user are stored in Redis.
- Debugging and failing events are omitted.
- Milestone events are created for every milestone from "XXS" to "XXXL."
- The milestones are included in the same event's daily email.

2533 Milestone tracking for webhook events sent

---

README.md

This is just to trigger a build.

feat(docs): Tweak readme

---

cl/opinion_page/templates/includes/de_filter.html
cl/opinion_page/views.py

2619 docket search order buttons

---

cl/corpus_importer/management/commands/troller_bk.py

As required in #2635 we'll skip RSS feeds with incorrect date formats like: `Mon, 05 Oct 2015 14:17:15 GM6 GMT` and continue the process.

2635 Skip RSS feeds due to incorrect date format

---

cl/custom_filters/templatetags/extras.py

I saw there `flynt` action is failing, this use of f-strings might solve the problem.

Use f-strings to fix flynt failing action

---

cl/users/views.py

NULLs are sorted in magic ways by RDBMS.  Often you get the correct answer.  When sorting by date it is more difficult, does a NULL date mean that it is so new that it doesn't have a date or so old that it doesn't have a date?
Django added a modifier to the `desc()` and `asc()` methods of an `F` filter.
We updated the code to use an `F()` filter so we can explicitly say where we want NULLS to sort in the Docket Alert List.
Fixes: #2648

Put "never" as the oldest item in a docket alert list

---

scripts/make_bulk_data.sh

Fixes: #2683
I'll need to deploy this to the cron job in k8s when it's ready.

fix(bulk): Add citations export

---

cl/users/views.py

It was wrong, it is better now.
Fixes: #2689

Fix the logic for Docket Alert Sort Order

---

DEVELOPING.md

This is really just to force a deploy.

feat(docs): Tweak dev guidelines

---

cl/api/views.py
cl/audio/feeds.py
cl/citations/match_citations.py
cl/corpus_importer/bulk_utils.py
cl/corpus_importer/management/commands/buried_alive_project.py
cl/corpus_importer/management/commands/invoice_project.py
cl/corpus_importer/management/commands/legal_robot.py
cl/lib/search_utils.py
cl/lib/test_helpers.py
cl/people_db/management/commands/cl_get_ftm_ids.py
cl/people_db/views.py
cl/search/feeds.py
cl/search/management/commands/cl_update_index.py
cl/search/tasks.py
cl/search/views.py
cl/tests/base.py

Fixes some remaining issues like the ones in #1414.

Ensure solr sessions are always closed using context managers

---

cl/tests/base.py
poetry.lock
pyproject.toml

Also update dependencies to be compatible with this version.

Update juriscraper to version 2.5.48

---

cl/stats/views.py

This reverts commit a5d507ace0846c564d20144b52376e19d3cb882e.

Revert "fix(checks): Set postgres to be perma-working"

---

cl/settings/third_party/rest_framework.py

They're paying more too, see emails from 2023-05-17

feat(api): Bump access for user

---

.github/workflows/docker-build-dev.yml
.github/workflows/docker-build.yml

Lets see if this fixes deploys for non-members.

Deploy on push to main instead of pull request close

---

cl/users/forms.py
cl/users/templates/register/register.html

Try this again, but show the captcha and the errors, I guess.

feat(forms): Make hcaptcha more visible

---

cl/opinion_page/templates/opinion.html
cl/search/templates/includes/search_result.html

Adjust indentation in `search_results` and correct invalid HTML in `opinion`.

chore(web): tweaks to opinion and search_results

---

poetry.lock
pyproject.toml

Changelog: https://github.com/jsocol/django-ratelimit/blob/main/CHANGELOG

Update django-ratelimit to version 4.1.0

---

poetry.lock
pyproject.toml

Changelog: https://github.com/django-ses/django-ses/blob/master/CHANGES.md

Update django-ses to version 3.5.0

---

poetry.lock
pyproject.toml

Changes: https://github.com/a1tus/django-admin-cursor-paginator/releases/tag/v0.1.4

Update django-admin-cursor-paginator to version 0.1.4

---

cl/recap/tasks.py

Hopefully fixes https://github.com/freelawproject/courtlistener/pull/3076#issuecomment-1710652680

Use delay instead of apply_async

---

cl/lib/pacer.py
cl/opinion_page/tests.py
cl/recap/mergers.py
cl/recap/tasks.py
cl/recap/tests.py
cl/recap_rss/tasks.py
cl/search/tests/tests.py

Should hopefully help performance.

Make add_docket_entries async

---

cl/opinion_page/views.py
cl/recap/mergers.py

fix(recap): Make og-info async

---

cl/recap/mergers.py

Fixes: https://github.com/freelawproject/courtlistener/issues/3180
Fixes: COURTLISTENER-4YM

fix(recap): Make og-info async 2

---

.pre-commit-config.yaml
cl/recap/mergers.py
cl/recap/test_assets/cand_7.html
cl/recap/tests.py
poetry.lock
pyproject.toml

Currently depends on https://github.com/freelawproject/juriscraper/pull/727 for tests to pass.

Add support for parsing attachments from dockets

---

cl/recap/mergers.py

Should fix https://github.com/freelawproject/courtlistener/pull/3172#issuecomment-1740370970

Use async for with aiterator()

---

cl/recap/mergers.py

Hopefully fixes https://github.com/freelawproject/courtlistener/pull/3172#issuecomment-1740370970

Use async for iterator for dupe_doc_ids

---

cl/api/views.py
cl/assets/static-global/css/override.css
cl/simple_pages/static/js/coverage-op.js
cl/simple_pages/templates/help/coverage_opinions.html
cl/simple_pages/views.py

PR to address issue #3222 
Updates for 
1. Performance enhancements using SOLR
2. Mobile - fixes for TOC and charts (hidden)
3. Architecture - dropped sending court names to API 
4. Content: has been added
Did not add spinner (hoping speed resolves that) 
Same for caching.  I think this may be fast enough.

3222 coverage follow up

---

cl/simple_pages/templates/includes/terms_history.html
cl/simple_pages/templates/terms/1.html
cl/simple_pages/templates/terms/10.html
cl/simple_pages/templates/terms/11.html
cl/simple_pages/templates/terms/12.html
cl/simple_pages/templates/terms/13.html
cl/simple_pages/templates/terms/14.html
cl/simple_pages/templates/terms/15.html
cl/simple_pages/templates/terms/16.html
cl/simple_pages/templates/terms/17.html
cl/simple_pages/templates/terms/18.html
cl/simple_pages/templates/terms/2.html
cl/simple_pages/templates/terms/3.html
cl/simple_pages/templates/terms/4.html
cl/simple_pages/templates/terms/5.html
cl/simple_pages/templates/terms/6.html
cl/simple_pages/templates/terms/7.html
cl/simple_pages/templates/terms/8.html
cl/simple_pages/templates/terms/9.html
cl/simple_pages/templates/terms/latest.html

Fixes: https://github.com/freelawproject/courtlistener/issues/3146

feat(tos): Update terms of service to add Neon

---

cl/assets/static-global/css/override.css
cl/simple_pages/static/js/coverage-op.js
cl/simple_pages/templates/help/coverage.html

Last couple things
@ERosendo @mlissner

3222 followup tasks

---

cl/search/admin.py

Fixes: #2733
Fixes: COURTLISTENER-3SD

fix(admin): Only do IA work if there's IA info

---

cl/opinion_page/views.py

feat(api): Make the citation lookup tool crsf exempt

---

scripts/make_bulk_data.sh

Add the people_db_person_race table to the list of tables to be exported

feat(bulk_script): Add people_db_person_race

---

poetry.lock
pyproject.toml

Probably a good idea to add the django extras(I don't think that option was available in the previous version).

Update sentry-sdk to version 1.34.0 and enable django extras

---

cl/api/templates/rest-docs-vlatest.html

Helps answer: https://github.com/freelawproject/courtlistener/discussions/3353

fix(docs): Provide clarity about which fields to use

---

cl/recap/views.py

Remove asyncio.create_task for shield

---

cl/recap/mergers.py

Lets see if this works for cleaning up duplicate `RECAPDocument`'s.

Try to clean duplicate RECAPDocument's when case is known

---

poetry.lock
pyproject.toml

A simple Poetry bump for Juriscraper

feat(poetry): Bump Juriscraper to fix things

---

poetry.lock
pyproject.toml

Bump Juriscraper to fix Scotus Slip

feat(poetry): Bump Juriscraper 2.5.63

---

poetry.lock
pyproject.toml

feat(poetry): Bump Juriscraper 2.5.66

---

cl/recap/mergers.py

Should hopefully help cleanup duplicate entries for #2877.

Attempt to handle broken document_number's

---

cl/recap/mergers.py

Should hopefully help cleanup duplicate entries for #2877.

Attempt to clean duplicate attachments with bad document_number's

---

poetry.lock
pyproject.toml

Fixes
- OklaAG
- ConnAppCt
- VI
- PR
- CoastGuard Crim
- CA2 OA
- Conn
- VA
- Ariz App dist 2

feat(poetry): Bump Juriscraper 2.5.69

---

poetry.lock
pyproject.toml

feat(poetry): Bump Juriscraper 2.5.70

---

cl/recap/management/commands/pacer_iquery_scraper.py

feat(iquery): Crawl fewer dockets

---

cl/alerts/tests.py
cl/api/tests.py
cl/audio/tests.py
cl/citations/tests.py
cl/donate/tests.py
cl/favorites/tests.py
cl/favorites/views.py
cl/lib/tests.py
cl/opinion_page/tests.py
cl/users/tests.py
cl/visualizations/tests.py
cl/visualizations/views.py

Various test/view improvements made possible by django 5.

More async test/view migrations

---

cl/alerts/tasks.py
cl/alerts/tests.py
cl/audio/models.py
cl/citations/tests.py
cl/corpus_importer/management/commands/columbia_merge.py
cl/corpus_importer/tests.py
cl/disclosures/tasks.py
cl/disclosures/tests.py
cl/search/views.py

This PR makes the following refactors:
* Removes f from some constant strings
* Removes unneeded imports
* Changes not X in Y to X not in Y
* Makes some parts more Pythonic

refactor(cl): Refactor and Make Code More Pythonic

---

cl/citations/group_parentheticals.py
cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py
cl/corpus_importer/management/commands/troller_bk.py
cl/donate/management/commands/cl_delete_failed_donations.py
cl/simple_pages/views.py
cl/users/urls.py

This PR does the following:
* Adds some type-hinting
* Removes the f from some constant strings
* Makes some bits more Pythonic
* Removes some unused imports
* Refactors a few complicated items
* Removes old, commented-out code.

refactor(cl): Refactor and Make Code More Pythonic 

---

cl/opinion_page/views.py

Fix view summaries

---

cl/favorites/views.py

Fix view_tag user

---

cl/opinion_page/views.py

Lets see if this is what was breaking parties.

Revert defaultdict

---

cl/opinion_page/views.py

In #3527, we encountered errors from the court homepage.
I've tested this solution, and it is working.

3527 Fix error loading court home page due to async context

---

cl/opinion_page/views.py

fix(docket): Handles the ObjectDoesNotExist exception in the idb view

---

poetry.lock
pyproject.toml

Juriscraper v2.5.75
Add Bankruptcy Appellate Panel 1st circuit

feat(poetry): Bump juriscraper take II

---

poetry.lock
pyproject.toml

feat(poetry): Bump juriscraper v2.5.76

---

cl/opinion_page/tests.py
cl/opinion_page/views.py
cl/search/models.py

This PR fixes #3537 by implementing a custom `asave` method. It also includes tests to verify that the issue is fixed and prevent regressions.

feat(opinions): Adds custom asave method to the OpinionCluster model

---

cl/opinion_page/views.py

Use TemplateResponse for citation_handler multiple result response

---

cl/opinion_page/views.py

Wrap paginator.num_pages in sync_to_async

---

cl/opinion_page/tests.py
cl/opinion_page/views.py

Wrap all paginate operations in a single sync_to_async

---

cl/opinion_page/views.py

Wrap CourtUploadForm init in sync_to_async

---

cl/simple_pages/urls.py
cl/simple_pages/views.py

Remove async incompatible ratelimiter

---

cl/api/views.py

fix(api): Use TemplateResponse instead of the render method

---

cl/donate/utils.py
cl/users/models.py

feat(user): Adds async properties to compute donations

---

cl/alerts/management/commands/cl_send_alerts.py
cl/alerts/management/commands/cl_send_scheduled_alerts.py
cl/alerts/tasks.py
cl/search/views.py
cl/stats/tests.py
cl/stats/utils.py
cl/users/views.py
cl/visualizations/utils.py
cl/visualizations/views.py

Make tally_stat async

---

cl/scrapers/utils.py

Catch httpx exceptions instead of requests exceptions for scrapers

---

poetry.lock

Update juriscraper/reporters-db

feat(poetry): Update reporters/juriscraper

---

poetry.lock
pyproject.toml

feat(poetry): Bump Juriscraper/Reporter-db

---

cl/donate/api_views.py
cl/donate/tests.py

This PR fixes #3674 by adding a new helper method to extract the address from the Neon API response if available.

feat(donate): Adds a helper to handle addresses from the Neon API

---

poetry.lock
pyproject.toml

Lets give this another try now that there's some more potential fixes.

Update asgiref to latest commit hash

---

cl/audio/filters.py
cl/disclosures/filters.py
cl/people_db/filters.py
cl/search/filters.py

This will help enable deep pagination on a
varity of object types.
Fixes: https://github.com/freelawproject/courtlistener/discussions/3436#discussioncomment-8387610

fix(api): Apply INTEGER_LOOKUPS to id fields

---

cl/users/forms.py
cl/users/templates/profile/settings.html

This PR updates the registration and profile forms to make the first and last name fields required. This PR fixes #3752.

feat(users): tweaks first and last name in registration form

---

.github/dependabot.yml
.github/workflows/lint.yml
cl/api/templates/bulk-data.html
cl/api/templates/rest-docs-vlatest.html
cl/citations/annotate_citations.py
cl/corpus_importer/import_columbia/columbia_utils.py
cl/corpus_importer/tests.py
cl/lib/auth.py
cl/lib/celery_utils.py
cl/lib/context_processors.py
cl/lib/neon_utils.py
cl/lib/string_utils.py
cl/people_db/import_judges/judge_utils.py
cl/people_db/models.py
cl/search/signals.py
cl/simple_pages/templates/contact_form.html
cl/simple_pages/templates/faq.html
cl/simple_pages/templates/help/coverage_opinions.html

Nothing noteworthy here - just some housekeeping.

chores(python): correct spellings, docstrings, and address `SyntaxWarning`

---

cl/lib/elasticsearch_utils.py
cl/search/tests/tests_es_recap.py

As described in https://github.com/freelawproject/courtlistener/issues/3660#issuecomment-1953357427 , this error has occurred 166 times.
It's related to search queries sorted by entry date filed (newest documents first) that match cases where their docket entries have values older than January 1, 1970 (epoch time). Consequently, their dates produce negative values, which are incompatible with the Elasticsearch score system.
For instance:
https://www.courtlistener.com/?q=&type=r&order_by=entry_date_filed%20desc&party_name=%22John%20Arthur%20Johnson%22
This query matches documents from the following docket: https://www.courtlistener.com/docket/30341940/united-states-v-johnson/
That contains entries from 1912 and 1913.
To solve the issue, an offset is added to all the dates when computing …

Fix negative scores when sorting cases by entry date filed

---

.github/workflows/docker-build.yml

In #3862 we merged a new sweep indexer. It has two parts: 
- A daemon that creates tasks to update Elastic
- A celery deployment that runs the tasks
This PR makes sure both are properly updated when changed.

feat(ci): Add sweep indexer to Github Action

---

cl/search/management/commands/cl_index_parent_and_child_docs.py
cl/search/tests/tests.py
cl/search/tests/tests_es_opinion.py

According to our plan to index missing opinions after the completion of #3901 run , I realized it would be easier to modify the `cl_index_parent_and_child_docs` command. It is already possible to choose a specific document type for indexing, instead of tweaking the `sweep_indexer` to run only for Opinions. Therefore, I introduced the `missing` flag to the cl_index_parent_and_child_docs command.
The command can be run as follows:
`manage.py cl_index_parent_and_child_docs --queue es_sweep --search-type o --document-type child --pk-offset 0 --chunk-size 100 --missing`
We could even use the same `--queue` as the sweep indexer in order to share the throttling rate with the `sweep_indexer`.

3897 Introduced missing flag to cl_index_parent_and_child_docs command

---

cl/assets/templates/base.html
cl/users/utils.py

This PR updates the newsletter link in the base HTML template and confirmation account email template to make sure it directs users to the correct location.

fix(template): Updates the newsletter link

---

cl/citations/api_views.py
cl/citations/tests.py

This PR implements logic to skip citations lacking page information. Additionally, it introduces a dedicated test to prevent future regressions.

feat(citations): Adds logic to filter out citations with no page

---

cl/corpus_importer/management/commands/recap_into_opinions.py
cl/lib/decorators.py

Add retry functionality for recap-extract micro service call

Update recap-into-op with retry 

---

cl/audio/management/commands/transcribe.py

By default, the command tries to transcribe all audio_audio rows With --limit LIMIT, it will only try to transcribe LIMIT audio files

feat(audio.transcribe): add optional limit argument

---

cl/corpus_importer/management/commands/recap_into_opinions.py

Update logging to verify celery process started for slow db queries
Improve court filtering code to allow for skip-until restarts for courts
Add error logging for courts without clusters

fix(recap->op): fix count trigger

---

cl/corpus_importer/management/commands/recap_into_opinions.py
cl/corpus_importer/tasks.py
cl/search/constants.py

Fix and features 
Include precedential status in saving
Add - add-to-solr flag 
Update constants to include new trial court document type

feat(recap->op): Update recap into opinions

---

cl/audio/tasks.py

This PR introduces retry functionality for calls made to the `downsize-audio` service from the Doctor. This will improve the robustness of the transcription process by automatically retrying requests that encounter specific known errors.

feat(audio): Adds retries to the downsize service

---

cl/corpus_importer/management/commands/make_aws_manifest_files.py

This PR updates the filtering condition logic to ensure comprehensive updates to all valid OA records previously included during the initial execution of this command.

feat(manifest): Update filtering clause to retrieve all valid OA records

---

cl/opinion_page/views.py

This PR introduces logic to handle missing arguments with defaults, ensuring the function operates smoothly even when not provided all inputs. Additionally, it enforces argument validation by limiting accepted arguments to those explicitly declared in the function's signature, preventing unexpected behavior.
Fixes #4174

fix(citation): Improves robustness by handling missing arguments with defaults

---

cl/api/templates/recap-api-docs-vlatest.html

This PR updates the recap API documentation to provide clearer instructions for uploading documents originating from ACMS courts.

feat(docs): Updates document upload requirements for ACMS courts

---

cl/opinion_page/templates/docket_tabs.html
cl/users/templates/profile/deleted.html

2024 07 22 tweak language on deletion html 4224

---

scripts/make_bulk_data.sh

fix(bulk): Escape the backtick some more

---

cl/citations/match_citations_queries.py
cl/search/tests/tests_es_opinion.py

Following #4211, I applied a fix to address the issue where an alert was not shown when a query citation matched a single cluster containing more than one sibling Opinion.
The approach I chose is to query by `opinion_cluster` if the query method is called by `es_get_query_citation`. This is better than choosing only one opinion if the results belong to the same cluster.
I also tested the latter approach but realized there could be issues if, for instance, there is a cluster with two sibling opinions that matched and also a different cluster that matched. In those cases, we'd show the alert even though there is a different cluster with the same exact citation. This is because the query only retrieves two results to determine if there is more than one match, and it's possible that beyond …

4211 Fixed query citation alert for clusters with multiple sibling opinions.

---

cl/corpus_importer/tasks.py
cl/recap/mergers.py
poetry.lock
pyproject.toml

Should make attachment matching more robust.

Fallback to looking up attachments based on pacer_doc_id

---

cl/recap/factories.py
cl/recap/mergers.py
cl/recap/tests.py

Should fix https://github.com/freelawproject/courtlistener/pull/4352#issuecomment-2318548798

Add missing pacer_doc_id param

---

cl/recap/mergers.py

Fix docket_entry arg

---

cl/simple_pages/templates/includes/terms_history.html
cl/simple_pages/templates/terms/19.html
cl/simple_pages/templates/terms/latest.html

This commit addresses issue #203 by updating our privacy policy. The main goals achieved are:
1. Simplification of the privacy policy language
2. Updated list of third parties we share data with
3. Clarification on the use of search queries for improving algorithms 
These changes aim to provide users with clearer, more accurate information  about our data practices, addressing the concerns raised in issue #203. 
Fixes: #203

fix(privacy): Simplify privacy policy and update third-party list

---

cl/settings/django.py

Fixes: #4456 by removing connection pools. 
I did some research prior to this, but couldn't find anybody with similar problems that was using gunicorn, so I figured I better land the fix and we can continue researching (or simply not bother) on Monday.

4456 fix connection pool problems

---

cl/search/management/commands/import_harvard_pdfs.py
cl/search/tests/test_import_harvard_pdfs.py

I added the crosswalk directory argument for the CAP import command because it was not possible to specify it, i also made it required.
Related tests have been updated.
Usage example:
`docker exec -it cl-django python /opt/courtlistener/manage.py import_harvard_pdfs --crosswalk_dir /storage/tmp/crosswalk`

Add crosswalk_dir as argument in CAP import

---

cl/favorites/tests.py

It seems this needs to be converted to avoid a date mismatch depending on if utc and local timezone dates differ.

Convert to naive timezone before formatting with template_date

---

.env.example
cl/api/urls.py
cl/assets/static-global/css/override.css
cl/assets/templates/base.html
cl/favorites/api_serializers.py
cl/favorites/api_views.py
cl/favorites/filters.py
cl/favorites/templates/top_prayers.html
cl/favorites/tests.py
cl/favorites/urls.py
cl/favorites/utils.py
cl/favorites/views.py
cl/opinion_page/static/js/pay_and_pray.js
cl/opinion_page/templates/docket.html
cl/opinion_page/templates/docket_tabs.html
cl/opinion_page/templates/includes/de_list.html
cl/opinion_page/templates/includes/pray_and_pay_htmx/pray_button.html
cl/opinion_page/views.py

This PR reverts freelawproject/courtlistener#4582 and addresses issue https://github.com/freelawproject/courtlistener/issues/4581.

4507 pray and pay api with fix

---

cl/assets/react/DisclosureViewer.tsx
cl/assets/react/TagList.tsx
cl/assets/react/_disclosure_helpers.tsx
cl/assets/react/_useTags.ts
cl/corpus_importer/templates/ca_judges_input.html
cl/favorites/static/js/tag-utils.js
cl/visualizations/static/js/scotus_map_new.js

This PR updates React and JavaScript files to use the new v4 API endpoints
Fixes #4658.

fix(assets): Updates react and js component to v4 API

---

cl/recap/tasks.py

Hopefully improves subprocess error tracing.

Try to improve subprocess exception handling

---

cl/api/tests.py

This PR addresses a flaky test identified in issue #4624. The test was failing because the number of database queries was lower than expected.
Django's caching mechanism can sometimes reduce the number of database queries, leading to unexpected results. To resolve this, we've implemented a solution suggested in Django tickets [#11505](https://code.djangoproject.com/ticket/11505) and [#23746](https://code.djangoproject.com/ticket/23746). By clearing the cache before counting the queries, we ensure accurate results and prevent the test from failing.
Since applying this fix, the test has been consistently passing.
Links:
- [#11505 - Django's TestCase should reset the cache](https://code.djangoproject.com/ticket/11505)
- [#23746 - Allow assertNumQueries to clear caches before it …

test(api): Clear cache before counting number of queries

---

cl/api/templates/pacer-api-docs-vlatest.html
cl/search/api_views.py

feat(api): Enable ordering docket entries by recap_sequence_number and entry_number

---

cl/custom_filters/templatetags/extras.py
cl/users/templates/includes/webhook-event-detail.html
cl/users/templates/includes/webhooks_htmx/webhook-logs-list.html
cl/users/tests.py

feat(webhook_logs): Display timezone in all datetimes

---

.github/workflows/docker-build.yml
cl/api/templates/migration-guide.html
cl/settings/third_party/rest_framework.py

This updates our CD to add the iquery roll out commands, so it stays up to date. It also has a few little tweaks I've been saving up.

Infrastructure add iquery rollout

---

cl/opinion_page/templates/opinions.html

Fixes #4763 
Fix url for v|lex logo

fix(opinions.html): Fix sponored logo url

---

cl/corpus_importer/management/commands/update_casenames_wl_dataset.py

Incorrect counting fix for case name updates

fix(update_case_names): Logging counter bug

---

cl/search/models.py
cl/simple_pages/templates/help/prayer_help.html

Related to https://github.com/freelawproject/courtlistener/issues/4845, this tunes up the help page a bit.
I also discovered some stray Solr code, so I removed that too. Sorry for the mess; didn't seem worth a separate PR.

Pray and Pay help page revisions

---

cl/favorites/admin.py
cl/favorites/templates/top_prayers.html

Key changes: 
- Improves prayer list in admin panel by displaying  submitting user and associated document.
- Adds admin action in top prayers page
Here's a GIF showing the new action button and the prayer list in the admin panel: 
Fixes #4888

feat(prayers): Adds admin action in top prayers page

---

cl/api/templates/recap-api-docs-vlatest.html
cl/api/templates/rest-docs-vlatest.html

docs(api): update API docs to make it easier to find docket entries endpoint

---

cl/assets/templates/base.html

Hiding pray-and-pay tab from dropdown

---

cl/corpus_importer/management/commands/make_aws_manifest_files.py

This PR refactors the `make_aws_manifest` command to enable the creation of manifest files for **Judges** and **Financial disclosures**.

feat(corpus_importer): Adds support for new record types

---

cl/opinion_page/templates/docket_authorities.html
cl/opinion_page/templates/includes/docket_authorities_list.html
cl/opinion_page/views.py

fix(authorities): restore authorities tab in docket authorities page

---

cl/corpus_importer/management/commands/make_aws_manifest_files.py

This PR updates `make_aws_manifest_files.py` to include Harvard opinions in the case law manifest.
The new query will include opinion with the following sources: 
- `HARVARD_CASELAW`
- `COURT_M_HARVARD`
- `ANON_2020_M_HARVARD`
- `COURT_M_RESOURCE_M_HARVARD`
- `DIRECT_COURT_INPUT_M_HARVARD`
-`LAWBOX_M_HARVARD`
- `LAWBOX_M_COURT_M_HARVARD`
- `LAWBOX_M_RESOURCE_M_HARVARD`
- `LAWBOX_M_COURT_RESOURCE_M_HARVARD`
- `MANUAL_INPUT_M_HARVARD`
- `PUBLIC_RESOURCE_M_HARVARD`
- `COLUMBIA_ARCHIVE_M_HARVARD`
- `COLUMBIA_M_LAWBOX_M_HARVARD`
- `COLUMBIA_M_DIRECT_COURT_INPUT_M_HARVARD`
- `COLUMBIA_M_LAWBOX_M_RESOURCE_M_HARVARD`
- `COLUMBIA_M_LAWBOX_M_COURT_RESOURCE_M_HARVARD` 
- `COLUMBIA_M_COURT_M_HARVARD` 
- `COLUMBIA_M_MANUAL_INPUT_M_HARVARD` 
- `COLUMBIA_M_PUBLIC_RESOURCE_M_HARVARD` 
- …

feat(corpus_importer): Adds Harvard opinions to manifest files

---

cl/opinion_page/templates/includes/rd_metadata_headers.html

feat(templates): add time uploaded to document page

---

cl/citations/tests.py
poetry.lock

Update reporters-db and the test in citations that is affected by the regex change

feat(citations): Update reporters-db and test

---

cl/citations/match_citations.py
cl/citations/match_citations_queries.py

Update resolve_fullcase_citation
In elastic collapse search queries around
cluster ids
Use backup method get_clusters_from_citation_str
if no citation is found.

feat(match_citations): resolve_fullcase_citation

---

cl/settings/third_party/rest_framework.py

These (this?) folk(s) have already made over 100k requests in the last day — per account.

feat(api): Block users

---

cl/citations/match_citations.py
cl/citations/tasks.py
cl/citations/tests.py
cl/search/selectors.py

Remove self links in backup method
Check if volume is digit to avoid bug
Use corrected reporter to lookup citations

fix(match_citations): Update find cites

---

cl/citations/management/commands/find_citations.py

Add filter to query older modification dates
Add date modified before argument to process missing ny cases

feat(find_citations): add filter modified before

---

cl/assets/templates/base.html
cl/opinion_page/templates/docket_tabs.html
cl/opinion_page/templates/includes/de_list.html
cl/opinion_page/templates/includes/redirect_to_pacer_modal.html
cl/opinion_page/templates/recap_document.html
cl/opinion_page/views.py

feat(pnp): removing pray-and-pay waffle flag

---

cl/api/templates/recap-api-docs-vlatest.html

Small PR - Commit 45adafb510fa04531a1190e306f5ee20b0355ae7 moved the tests suite source file. This PR adjusts sources to changes.

docs: update tests suite reference

---

cl/opinion_page/utils.py

This PR introduces the `citing_and_related_enabled` flag. When enabled, it will render the related and citing clusters normally either from the database cache or ES in `view_opinion_old` (which is the current public view).
If the flag is disabled, citing and related clusters will not be shown (and no queries are performed). Instead, buttons will be displayed to allow users to perform the queries.
By default, this setting is enabled. To disable it, it should be set to No.

Disable citing and related clusters on the opinion page via waffle

---

cl/citations/tasks.py

Fix latest changes which didnt account for no citations.  
When no citations were found, we were crashing beacuse there was no document object to use to generate html with citations

feat(citation.tasks): Need to account for no citations found

---

cl/favorites/templates/top_prayers.html

fix(favorites): adding logged out modal to pray-and-pay community leaderboard

---

cl/corpus_importer/management/commands/make_aws_manifest_files.py

This PR implements a helper function that generates and uploads a CSV manifest, enabling users to easily discover and download new or updated records. The manifest provides a mapping between the record ID and its S3 key for download.
Unlike PR #5447, which focused on a manifest for Lambda functions, this version is specifically designed for user consumption. An example of the manifest content is:
```
10000005,ai_case_law_dataset/o_10000005.json
10000032,ai_case_law_dataset/o_10000032.json
```
After downloading the CSV, users can employ scripting tools, such as the following Bash script, to automate the retrieval of records from S3 based on the provided information:
```
awk -F ',' '{print $1, $2}' new_or_updated_4_2025.csv | while read -r record_id s3_key_raw; do
s3_key=$(echo …
```

feat(corpus_importer): Enable user retrieval of new/updated records via csv

---

cl/citations/management/commands/find_citations.py

fix(find_citations): Set opinions-per-task as int

---

.github/workflows/codeql-analysis.yml
.github/workflows/docker-build.yml
.github/workflows/lint.yml
.github/workflows/semgrep.yml
.github/workflows/tests.yml

Copy of https://github.com/freelawproject/awscloud/pull/22 for this repository.
Before, tests run twice on each PR:
After, just once:

chore(ci): Prevent duplicate GitHub Actions runs

---

.github/workflows/flp-dependencies-pr.yml

fix(workflows): recreate flp-dependencies-pr.yml

---

.github/workflows/flp-dependencies-pr.yml

Related to #5569
This is now working, when running the [action](https://github.com/freelawproject/courtlistener/actions/runs/15032660268/job/42248309957) from the branch of this PR, it produces the expected [PR](https://github.com/freelawproject/courtlistener/pull/5572/files)

fix(workflows): debug flp-dependencies-pr.yml action

---

.github/workflows/docker-build.yml

The cl:github-only has been updated to allow HPA changes

[353] Patch HPA during deployments

---

cl/citations/tasks.py

Solves a bug introduced in #5656

fix(citations.tasks): fix retry argument name

---

cl/search/management/commands/cl_index_embeddings.py
cl/search/tests/tests_semantic_search_opinion.py

This PR updates `cl_index_embeddings` to read the inventory file from local storage instead of S3, in order to prevent S3-related errors.
The file should be mounted in a directory under `MEDIA_ROOT`.
It can be run using:
`manage.py cl_index_embeddings --indexing-queue batch2 --retrieval-queue batch3 --batch-size 5 --inventory-file inventory/bf22253e-8d7f-49fb-9aa5-677e081d8384.csv --inventory-rows 2374114`

Tweaked cl_index_embeddings command to load the inventory file from MEDIA_ROOT

---

cl/lib/pacer_session.py

This PR overrides the `_get_saml_auth_request_parameters` method to ensure that cookies obtained during the SAML authentication workflow are compatible with proxy connections that do not use HTTPS. Specifically, it disables the `secure` flag on cookies so they are not stripped when routed through our proxy.
Fixes #5921 
----
Once this PR is merged, you can verify that ACMS authentication works as expected by running the following script. It should execute without raising any exceptions:
```python
from django.conf import settings
from cl.lib.pacer_session import ProxyPacerSession
session = ProxyPacerSession(
username=settings.PACER_USERNAME,
password=settings.PACER_PASSWORD,
get_acms_tokens=True,
)
session.login()
```

feat(pacer_session): Tweaks SAML auth cookie settings for proxy compatibility

---

cl/scrapers/management/commands/merge_opinion_versions.py

Fixes #5991
Ensures version OpinionDocument removal by using `remove_document_from_es_index`, which uses the routing key that was missing

fix(merge_opinion_versions): fix OpinionDocument ES removal

---

.github/ISSUE_TEMPLATE/bug_report.yml

Just tweaks our issue tmeplate

fix(github): tweak issue template

---

cl/alerts/forms.py
cl/alerts/management/commands/cl_send_alerts.py
cl/alerts/management/commands/cl_send_recap_alerts.py
cl/alerts/tasks.py
cl/alerts/templates/includes/search_alerts/table_row.html
cl/alerts/tests/tests.py
cl/alerts/tests/tests_recap_alerts.py
cl/assets/static-global/js/search-alerts.js
cl/search/views.py
cl/users/models.py
cl/users/templates/profile/alerts.html

This PR fixes #3470 
This PR introduces the following changes: 
- Updates validations in the `CreateAlertForm` class to support users with unlimited search alerts.
- Adds a new hasUnlimitedAlerts flag to the `alerts_context` object.
- Integrates the `hasUnlimitedAlerts` flag into the existing `search-alerts.js` logic 

feat(search): Adds support for unlimited search alerts 

---

cl/recap_rss/management/commands/scrape_rss.py

Fixes: #6038
Make the chain expire after `RSS_MAX_PROCESSING_DURATION`, which is the threshold after which a new chain for the court will be scheduled. This prevents tasks for the same court, scheduled after `RSS_MAX_PROCESSING_DURATION`, from piling up in case workers become busy.

6038 Set expiration time for scrape_rss task chain

---

cl/lib/elasticsearch_utils.py
cl/search/tests/tests_es_recap.py

#6118 
While working on #6118 to add the search micro-cache to the Search API, I noticed the same inconsistent scores in my local environment. Specifically, scores changed slightly between requests, even though the local `cl-es` instance had only one node, a single shard, and no indexing activity. So, scores between requests shouldn't change.
After investigating the issue further, I discovered the cause: it's related to the date decay relevance function score. This method computes a document’s date relevance based on the request’s timestamp, with millisecond precision.
As a result, scores can slightly vary between requests, even for the same documents. This variation can shift result ordering and affect cursor pagination, which relies on consistent scores.
To fix this, I modified …

6118 Make decay relevance scores for Search API cursor pagination results stable

---

.github/PULL_REQUEST_TEMPLATE.md

Indents the template a bit. I think it'll make it more clear.

Tweak PR template

---

cl/lib/search_utils.py

Fixes: #6006
This PR removes outdated code related to backward compatibility for the search micro-cache. Now that old cached items have expired, it's safe to do this.

6006 Removed search micro cache outdated code

---

cl/search/admin.py

This PR adds a new admin page for ClusterRedirection model. 
Displays the fields pk, deleted_cluster_id, and cluster. 
The reason is added as a filter.
<details open>
<summary><h4>Desktop</h4></summary>
</details>

Add admin page for ClusterRedirection model

---

cl/scrapers/management/commands/delete_duplicates.py

Fixes bug not accounted for in #6164
Takes into account the case when duplicated same hash opinions are already grouped in a single cluster due to versioning. In that case, we can't delete the cluster, since doing that would delete all the opinions already grouped together, even then ones we want to keep
Labelling this as `skip-*` because 
- I will run it in my maintenace pod which I update manually
- doesn't affect any code used by any of the automated processes

fix(delete_duplicates): handle versioned cluster

---

cl/settings/third_party/rest_framework.py

Blocks a user that's non-responsive to email

feat(api): Block user

---

cl/search/selectors.py
cl/search/utils.py

This fixes #6199.
This PR sets default values for statistics shown on the homepage.
1. To deploy...

Set default values for statistics

---

cl/api/templates/rest-change-log.html
cl/api/templates/rest-docs-vlatest.html

This PR updates the API changelog to list all V4 endpoints that require authentication. Anonymous requests are no longer supported and will return a 401 Unauthorized response.
This PR depends on https://github.com/freelawproject/courtlistener/pull/6249

feat(docs): update API version to v4.3 in documentation

---

cl/api/templates/rest-docs-vlatest.html

Updates the API documentation to align with the changes we made to remove anonymous users.

fix(docs): Update throttling details

---

cl/corpus_importer/management/commands/recap_into_opinions.py

This PR fixes a values_list() method call in `recap_into_opinions` command, it removes the flat=True param because we are passing two fields. and this is causing a TypeError exception.

fix(recap_into_opinions): remove flat=True in values_list()

---

cl/scrapers/management/commands/cl_scrape_opinions.py

Fixes #6357
During a scrape, if an opinion fails downloading with BadContentError or InvalidDocumentError, do not update the site hash to ensure a retry on the next scrape

fix(cl_scrape_opinions): do not update site hash if an opinion fails downloading
